/* Società, conti e staff: il presidente, il direttore sportivo, gli sponsor,
   lo stadio, le persone che lavorano con te. */

export default [
  {
    id: 'bd_president_lineup', cat: 'board', w: 5, repeat: 25,
    when: { mdMin: 3, winless: 2 },
    o: [
      { fx: { trust: 6, teamMorale: -5, reputation: -2 } },
      { odds: { base: 0.55, trust: 0.004, good: { trust: 3, reputation: 2 }, bad: { trust: -10 } } },
      { fx: { trust: -3, teamMorale: 4 } },
    ],
    it: ['Il presidente fa la formazione', 'Dopo due partite senza vittorie il presidente ti chiama: vorrebbe vedere in campo i giocatori che ha voluto lui in estate.',
      ['Lo accontento', 'Il presidente è soddisfatto. Lo spogliatoio però ha capito chi comanda davvero.'],
      ['Gli spiego con calma le mie scelte', 'Il presidente apprezza la chiarezza e ti lascia lavorare.', 'Il presidente la prende come un affronto e lo fa sapere in giro.'],
      ['Gli dico che la formazione la faccio io', 'I giocatori ti vedono difenderli. In sede molto meno contenti.']],
    en: ['The chairman picks the team', 'After two games without a win the chairman calls you: he would like to see the players he wanted in the summer on the pitch.',
      ['Go along with him', 'The chairman is pleased. The dressing room, though, has seen who really is in charge.'],
      ['Calmly explain my choices', 'The chairman appreciates the clarity and lets you get on with it.', 'The chairman takes it as an insult and lets everyone know.'],
      ['Tell him I pick the team', 'The players see you standing up for them. The boardroom is far less happy.']],
  },
  {
    id: 'bd_budget_cut', cat: 'finance', w: 4, repeat: 60,
    when: { mdMin: 8, budgetMin: 3 },
    o: [
      { fx: { budgetPct: -0.35, trust: 6 } },
      { odds: { base: 0.45, trust: 0.006, good: { budgetPct: -0.1, trust: 2 }, bad: { budgetPct: -0.45, trust: -6 } } },
      { fx: { budgetPct: -0.2, fans: -4, trust: 3 } },
    ],
    it: ['I conti non tornano', 'Il bilancio è in rosso: la società deve tagliare il budget per il mercato. Chiede la tua collaborazione.',
      ['Accetto il taglio senza discutere', 'Il budget scende di un terzo, ma in società ti considerano un uomo di club.'],
      ['Tratto per un taglio più piccolo', 'Convinci tutti: il taglio è minimo.', 'Il braccio di ferro irrita il consiglio: il taglio sarà ancora più pesante.'],
      ['Propongo di alzare il prezzo dei biglietti', 'Il taglio si riduce, ma la curva protesta per i prezzi.']],
    en: ['The books don’t balance', 'The accounts are in the red: the club has to cut the transfer budget and asks for your cooperation.',
      ['Accept the cut without argument', 'The budget drops by a third, but the club sees you as a company man.'],
      ['Negotiate a smaller cut', 'You win them over: the cut is minimal.', 'The tug of war annoys the board: the cut will be even bigger.'],
      ['Suggest raising ticket prices', 'The cut is smaller, but the fans protest about the prices.']],
  },
  {
    id: 'bd_sponsor_betting', cat: 'finance', w: 4, repeat: 80,
    when: { mdMin: 2 },
    o: [
      { fx: { budget: 4, fans: -6, reputation: -2 } },
      { fx: { fans: 4, trust: -3 } },
      { fx: { budget: 1.5, fans: -1 } },
    ],
    it: ['Lo sponsor delle scommesse', 'Un’azienda di scommesse offre un contratto ricco per comparire sulle maglie di allenamento. Il presidente vuole il tuo parere.',
      ['Soldi sono soldi: accettiamo', 'Il budget cresce, ma una parte dei tifosi non la prende bene.'],
      ['Mi oppongo: non è l’immagine del club', 'I tifosi ti applaudono. In sede qualcuno pensa che i soldi servissero.'],
      ['Solo sui cartelloni dello stadio', 'Un compromesso che fa storcere il naso a pochi e porta qualcosa in cassa.']],
    en: ['The betting sponsor', 'A betting company offers a lucrative deal to appear on the training kit. The chairman wants your opinion.',
      ['Money is money: accept', 'The budget grows, but some fans don’t like it.'],
      ['Oppose it: it’s not the club’s image', 'The fans applaud you. Some in the boardroom think the money was needed.'],
      ['Only on the stadium boards', 'A compromise that bothers few people and brings in something.']],
  },
  {
    id: 'bd_stadium_works', cat: 'board', w: 3, repeat: 100,
    when: { mdMin: 5 },
    o: [
      { fx: { budgetPct: -0.15, fans: 6, nextMatch: { control: 0.97 } } },
      { fx: { fans: -3 } },
    ],
    it: ['Lavori allo stadio', 'La società vuole rifare il manto erboso e la tribuna a stagione in corso: per un mese si giocherà su un campo irregolare.',
      ['Via ai lavori', 'I tifosi apprezzano lo stadio nuovo; per qualche partita il pallone rimbalza male.'],
      ['Meglio aspettare l’estate', 'Si rimanda: qualche tifoso lamenta l’ennesimo rinvio.']],
    en: ['Stadium works', 'The club wants to relay the pitch and rebuild a stand mid-season: for a month the team will play on an uneven surface.',
      ['Start the works', 'The fans love the new stadium; for a few matches the ball bounces badly.'],
      ['Better wait for the summer', 'It’s postponed: some fans moan about yet another delay.']],
  },
  {
    id: 'bd_sporting_director', cat: 'staff', w: 4, repeat: 60,
    when: { mdMin: 4, trustMax: 60 },
    o: [
      { fx: { trust: 4, staff: -6 } },
      { odds: { base: 0.5, rep: 0.008, good: { trust: 6, staff: 6 }, bad: { trust: -8 } } },
    ],
    it: ['Il direttore sportivo rema contro', 'Voci dalla sede: il direttore sportivo parla male del tuo lavoro con il presidente e spinge per un altro allenatore.',
      ['Faccio finta di niente', 'Eviti lo scontro. Ma lo staff capisce che non ti farai valere.'],
      ['Chiedo un chiarimento a tre, con il presidente', 'Il chiarimento ti rafforza: il direttore fa un passo indietro.', 'Il presidente dà ragione al direttore: sei più solo di prima.']],
    en: ['The sporting director works against you', 'Word from the offices: the sporting director badmouths your work to the chairman and pushes for another manager.',
      ['Pretend nothing is happening', 'You avoid the clash. But the staff see you won’t stand your ground.'],
      ['Ask for a three-way meeting with the chairman', 'The meeting strengthens you: the director backs off.', 'The chairman sides with the director: you are more isolated than before.']],
  },
  {
    id: 'bd_contract_extension', cat: 'board', w: 5, repeat: 40,
    when: { mdMin: 12, trustMin: 70, gapMax: 0 },
    o: [
      { fx: { trust: 8, reputation: 2, setFlag: 'coachRenewed' } },
      { odds: { base: 0.5, rep: 0.006, good: { trust: 4, budgetPct: 0.2 }, bad: { trust: -6 } } },
      { fx: { reputation: 3, trust: -4 } },
    ],
    it: ['Il presidente vuole blindarti', 'Le cose vanno bene: il presidente ti offre il rinnovo del contratto prima di fine stagione.',
      ['Firmo subito', 'Rinnovo firmato: la società ti considera il suo allenatore per gli anni a venire.'],
      ['Firmo se il budget cresce', 'Il presidente accetta: più soldi per il mercato.', 'La richiesta non piace: il rinnovo resta nel cassetto.'],
      ['Aspetto: ho altre offerte', 'La tua reputazione cresce, ma il presidente si sente messo in attesa.']],
    en: ['The chairman wants to tie you down', 'Things are going well: the chairman offers you a new contract before the end of the season.',
      ['Sign right away', 'Contract signed: the club sees you as its manager for years to come.'],
      ['Sign if the budget grows', 'The chairman agrees: more money for transfers.', 'The demand goes down badly: the new deal stays in the drawer.'],
      ['Wait: I have other offers', 'Your reputation grows, but the chairman feels kept waiting.']],
  },
  {
    id: 'bd_preseason_tour', cat: 'finance', w: 5, repeat: 45,
    when: { mdMax: 1 },
    o: [
      { fx: { budget: 3, teamFitness: -12, fans: 2 } },
      { fx: { teamFitness: 6, familiarity: 6, budget: -0.3 } },
    ],
    it: ['Tournée all’estero', 'Il reparto marketing ha organizzato una tournée estiva dall’altra parte del mondo: incassi importanti, voli lunghi.',
      ['Si parte', 'La tournée porta soldi e visibilità. La squadra torna stanca.'],
      ['Ritiro in montagna, come si faceva una volta', 'Niente soldi extra, ma la squadra lavora sulla condizione e sul gioco.']],
    en: ['An overseas tour', 'The marketing department has organised a summer tour on the other side of the world: big revenue, long flights.',
      ['Let’s go', 'The tour brings money and visibility. The team comes back tired.'],
      ['A mountain training camp, old school', 'No extra money, but the team works on fitness and on its game.']],
  },
  {
    id: 'bd_analyst_hire', cat: 'staff', w: 5, repeat: 80,
    when: { mdMin: 2, noFlag: 'analystHired' },
    o: [
      { fx: { budget: -0.8, staff: 12, setFlag: 'analystHired' } },
      { fx: { familiarity: 3 } },
    ],
    it: ['Un analista dei dati', 'Il club può assumere un analista che viene da una grande squadra: video, dati, report sugli avversari.',
      ['Assumiamolo', 'Lo staff è più preparato: il vice sbaglierà meno i suoi consigli e le stime sui giovani saranno più precise.'],
      ['Preferisco il lavoro sul campo', 'Si continua con i metodi di sempre.']],
    en: ['A data analyst', 'The club can hire an analyst from a big team: video, data, reports on the opponents.',
      ['Hire him', 'The staff are better prepared: your assistant’s advice will be sharper and youth estimates more accurate.'],
      ['I prefer work on the pitch', 'The usual methods continue.']],
  },
  {
    id: 'bd_assistant_leaves', cat: 'staff', w: 3, repeat: 90,
    when: { mdMin: 10 },
    o: [
      { fx: { staff: -10, budget: 0.2 } },
      { fx: { budget: -0.6, staff: 2 } },
    ],
    it: ['Il vice riceve un’offerta', 'Il tuo vice allenatore ha ricevuto un’offerta per fare il primo allenatore in una squadra minore.',
      ['Lo lascio andare con un abbraccio', 'Parte con la tua benedizione. Il suo sostituto ci metterà un po’ a entrare nei meccanismi.'],
      ['Chiedo al club di aumentargli lo stipendio', 'Resta, felice di essere stato trattenuto.']],
    en: ['Your assistant gets an offer', 'Your assistant has been offered a head coach job at a smaller club.',
      ['Let him go with a hug', 'He leaves with your blessing. His replacement will take a while to settle in.'],
      ['Ask the club to give him a raise', 'He stays, happy to have been kept.']],
  },
  {
    id: 'bd_owner_style', cat: 'style', w: 5, repeat: 40,
    when: { mdMin: 4, styles: ['catenaccio', 'pullman', 'contropiede', 'verticale'] },
    o: [
      { fx: { trust: 5, familiarity: -15, fans: 3 } },
      { odds: { base: 0.5, good: { trust: 2 }, bad: { trust: -8 } } },
    ],
    it: ['“Voglio un calcio spettacolare”', 'La proprietà ti chiede di giocare un calcio più offensivo: dice che il pubblico si annoia e gli sponsor anche.',
      ['Cambio impostazione', 'Proprietà e tifosi contenti. La squadra dovrà reimparare parecchie cose.'],
      ['Spiego che i risultati vengono prima', 'La proprietà si fida del tuo metodo.', 'La proprietà non è convinta e te lo farà pesare alla prima sconfitta.']],
    en: ['“I want spectacular football”', 'The owners ask you to play more attacking football: they say the crowd is bored, and so are the sponsors.',
      ['Change approach', 'Owners and fans are happy. The team will have to relearn a lot.'],
      ['Explain that results come first', 'The owners trust your method.', 'The owners aren’t convinced and will hold it against you at the first defeat.']],
  },
  {
    id: 'bd_takeover_rumours', cat: 'board', w: 3, repeat: 90,
    when: { mdMin: 6 },
    o: [
      { fx: { teamMorale: -3, trust: 2 } },
      { fx: { reputation: 2, trust: -4, fans: 3 } },
    ],
    it: ['Il club è in vendita?', 'Circola la voce di un fondo straniero pronto a comprare il club. I giornalisti ti chiedono cosa ne pensi.',
      ['Nessun commento: penso alla squadra', 'Risposta professionale, ma l’incertezza pesa sul gruppo.'],
      ['Dico che una nuova proprietà farebbe bene', 'La frase piace ai tifosi. Molto meno all’attuale presidente.']],
    en: ['Is the club for sale?', 'A rumour says a foreign fund is ready to buy the club. Journalists ask you what you think.',
      ['No comment: I’m focused on the team', 'A professional answer, but the uncertainty weighs on the group.'],
      ['Say new owners would do the club good', 'The fans like it. The current chairman, much less.']],
  },
  {
    id: 'bd_training_ground', cat: 'finance', w: 3, repeat: 100,
    when: { budgetMin: 4 },
    o: [
      { fx: { budgetPct: -0.25, teamFitness: 5, staff: 5, youngsters: { potential: 1 } } },
      { fx: { trust: 2 } },
    ],
    it: ['Il centro sportivo', 'Il centro di allenamento è vecchio: campi rovinati, palestra piccola. Rifarlo costa una parte del budget per il mercato.',
      ['Investiamo nel centro sportivo', 'Strutture nuove: si lavora meglio e i giovani crescono più in fretta.'],
      ['I soldi servono per i giocatori', 'La società apprezza la prudenza.']],
    en: ['The training ground', 'The training centre is old: worn pitches, a small gym. Rebuilding it costs part of the transfer budget.',
      ['Invest in the training ground', 'New facilities: better work, and the youngsters develop faster.'],
      ['The money is for players', 'The club appreciates the caution.']],
  },
  {
    id: 'bd_academy_funds', cat: 'youth', w: 4, repeat: 100,
    when: { noFlag: 'academyFunds' },
    o: [
      { fx: { budgetPct: -0.2, academyInvest: true, setFlag: 'academyFunds' } },
      { fx: { trust: 1 } },
    ],
    it: ['Soldi al vivaio?', 'Il responsabile del settore giovanile chiede fondi per osservatori e allenatori nuovi. I risultati si vedrebbero tra qualche anno.',
      ['Sì, il futuro si costruisce adesso', 'Il vivaio si rafforza: dalla prossima estate saliranno ragazzi migliori.'],
      ['Adesso servono risultati', 'Il settore giovanile resta com’è.']],
    en: ['Money for the academy?', 'The head of the academy asks for funds for new scouts and coaches. Results would show in a few years.',
      ['Yes, the future is built now', 'The academy gets stronger: from next summer better youngsters will come through.'],
      ['Right now we need results', 'The academy stays as it is.']],
  },
  {
    id: 'bd_ultimatum_meeting', cat: 'board', w: 6, repeat: 20,
    when: { mdMin: 8, trustMax: 35 },
    o: [
      { odds: { base: 0.5, rep: 0.006, fans: 0.004, good: { trust: 12 }, bad: { trust: -6 } } },
      { fx: { trust: 4, teamMorale: -4, familiarity: -8 } },
      { fx: { trust: -2, teamMorale: 5, nextMatch: { attack: 1.04 } } },
    ],
    it: ['Riunione d’urgenza', 'Il consiglio di amministrazione ti convoca: i risultati non arrivano e vogliono sapere cosa pensi di fare.',
      ['Presento un piano dettagliato', 'Il piano convince: il consiglio ti concede tempo.', 'Il piano non convince nessuno: l’aria si fa pesante.'],
      ['Prometto di cambiare tutto', 'Il consiglio apprezza, ma i giocatori sono spaesati dalle novità.'],
      ['Difendo i giocatori: il gioco c’è, manca la fortuna', 'La squadra si stringe intorno a te. Il consiglio meno.']],
    en: ['Emergency meeting', 'The board summons you: results aren’t coming and they want to know what you plan to do.',
      ['Present a detailed plan', 'The plan convinces them: the board gives you time.', 'The plan convinces nobody: the atmosphere gets heavy.'],
      ['Promise to change everything', 'The board likes it, but the players are unsettled by the changes.'],
      ['Defend the players: the football is there, luck isn’t', 'The team rallies around you. The board less so.']],
  },
  {
    id: 'bd_bonus_dispute', cat: 'finance', w: 4, repeat: 50,
    when: { mdMin: 5, streakW: 2 },
    o: [
      { fx: { budget: -0.8, teamMorale: 8 } },
      { fx: { teamMorale: -6, trust: 3 } },
      { odds: { base: 0.6, teamMorale: 0.004, good: { teamMorale: 4, budget: -0.3 }, bad: { teamMorale: -8 } } },
    ],
    it: ['I premi partita', 'I senatori chiedono premi più alti per le vittorie. La società dice che il budget non lo permette e chiede a te di mediare.',
      ['Sto con i giocatori: i premi vanno pagati', 'La società paga, i giocatori sono carichi.'],
      ['Sto con la società', 'Il club ringrazia. Lo spogliatoio si sente tradito.'],
      ['Propongo premi legati all’obiettivo', 'Compromesso accettato da tutti.', 'La proposta scontenta tutti.']],
    en: ['Win bonuses', 'The senior players want bigger win bonuses. The club says the budget won’t allow it and asks you to mediate.',
      ['Side with the players: pay the bonuses', 'The club pays, the players are fired up.'],
      ['Side with the club', 'The club thanks you. The dressing room feels betrayed.'],
      ['Propose bonuses tied to the season target', 'Compromise accepted by everyone.', 'The proposal pleases nobody.']],
  },
  {
    id: 'bd_kit_launch', cat: 'finance', w: 4, repeat: 80,
    when: { mdMax: 3 },
    o: [
      { fx: { fans: 3, budget: 1, teamFitness: -3 } },
      { fx: { fans: -2 } },
    ],
    it: ['La presentazione della maglia', 'Lo sponsor tecnico vuole la squadra al completo per la presentazione della nuova maglia, in piazza, il giorno prima di un allenamento importante.',
      ['Tutti in piazza', 'Grande festa, vendite di maglie alle stelle.'],
      ['Mando solo tre giocatori', 'Evento sottotono: lo sponsor e i tifosi restano delusi.']],
    en: ['The kit launch', 'The kit supplier wants the whole squad at the launch of the new shirt, in the town square, the day before an important session.',
      ['Everyone to the square', 'A great party, shirt sales through the roof.'],
      ['Send only three players', 'A low-key event: the sponsor and the fans are disappointed.']],
  },
  {
    id: 'bd_goalkeeper_coach', cat: 'staff', w: 4, repeat: 70,
    when: { mdMin: 3 },
    o: [
      { fx: { budget: -0.4, staff: 4, nextMatch: { keeper: 1.04 } } },
      { fx: {} },
    ],
    it: ['Un preparatore dei portieri', 'Un ex portiere famoso si offre come preparatore. Costa, ma i suoi metodi sono rinomati.',
      ['Lo prendiamo', 'I portieri lavorano meglio fin dalla prima settimana.'],
      ['Va bene quello che abbiamo', 'Nessun cambio nello staff.']],
    en: ['A goalkeeping coach', 'A famous former goalkeeper offers himself as goalkeeping coach. He’s expensive, but his methods are renowned.',
      ['Take him on', 'The keepers work better from the first week.'],
      ['The one we have is fine', 'No change to the staff.']],
  },
  {
    id: 'bd_physio_conflict', cat: 'staff', w: 4, repeat: 45,
    when: { injuredMin: 3 },
    o: [
      { fx: { staff: -4, budget: -0.5, teamFitness: 6 } },
      { fx: { teamFitness: -4, trust: 1 } },
    ],
    it: ['Troppi infortuni', 'Tre giocatori fermi insieme: il preparatore atletico accusa lo staff medico e viceversa.',
      ['Cambio il preparatore atletico', 'Metodi nuovi e carichi più leggeri: la squadra respira. Qualche malumore nello staff.'],
      ['Nessun cambio: è sfortuna', 'Il gruppo di lavoro resta unito, ma i carichi restano pesanti.']],
    en: ['Too many injuries', 'Three players out at once: the fitness coach blames the medical staff and vice versa.',
      ['Replace the fitness coach', 'New methods and lighter workloads: the team breathes again. Some grumbling among the staff.'],
      ['No change: it’s bad luck', 'The staff stay together, but the workloads stay heavy.']],
  },
  {
    id: 'bd_scout_network', cat: 'staff', w: 3, repeat: 80,
    when: { budgetMin: 2 },
    o: [
      { fx: { budget: -1, staff: 8 } },
      { fx: {} },
    ],
    it: ['La rete di osservatori', 'Il direttore sportivo propone di aprire una rete di osservatori in Sudamerica e Africa.',
      ['Sì, investiamo', 'Più occhi nel mondo: i report sui giocatori diventano più precisi.'],
      ['Non è il momento', 'Si resta con gli osservatori attuali.']],
    en: ['The scouting network', 'The sporting director proposes opening a scouting network in South America and Africa.',
      ['Yes, let’s invest', 'More eyes around the world: player reports become more accurate.'],
      ['Not the right time', 'The current scouts stay.']],
  },
  {
    id: 'bd_ticket_prices', cat: 'fans', w: 4, repeat: 60,
    when: { fansMax: 55 },
    o: [
      { fx: { fans: 8, budget: -0.8 } },
      { fx: { fans: -4, budget: 0.6 } },
    ],
    it: ['Biglietti popolari', 'Lo stadio è mezzo vuoto. Il tuo capitano ti chiede di convincere la società a fare biglietti a prezzi popolari.',
      ['Parlo con la società', 'Stadio pieno e caldo nelle partite successive. Meno incassi.'],
      ['Non è compito mio', 'I prezzi restano alti. I tifosi continuano a disertare.']],
    en: ['Cheap tickets', 'The stadium is half empty. Your captain asks you to persuade the club to sell cheap tickets.',
      ['Talk to the club', 'A full, loud stadium in the following matches. Less revenue.'],
      ['It’s not my job', 'Prices stay high. The fans keep staying away.']],
  },
  {
    id: 'bd_president_interview', cat: 'press', w: 4, repeat: 40,
    when: { mdMin: 5, streakL: 2 },
    o: [
      { fx: { trust: 3, reputation: -2, teamMorale: -2 } },
      { odds: { base: 0.45, rep: 0.006, good: { trust: 2, reputation: 3 }, bad: { trust: -10, fans: 2 } } },
    ],
    it: ['Il presidente parla ai giornali', 'In un’intervista il presidente dice che “l’allenatore non è in discussione, per ora”. Quel “per ora” fa il giro dei giornali.',
      ['Rispondo che ha ragione a pretendere di più', 'La risposta umile calma le acque, ma ti fa sembrare debole.'],
      ['Rispondo che il “per ora” se lo poteva risparmiare', 'La risposta piace: sei un allenatore con carattere.', 'Il presidente si infuria: la frattura è pubblica.']],
    en: ['The chairman talks to the papers', 'In an interview the chairman says “the manager is not under discussion, for now”. That “for now” makes every paper.',
      ['Reply that he’s right to demand more', 'The humble answer calms things, but makes you look weak.'],
      ['Reply that he could have spared us the “for now”', 'The answer lands well: a manager with character.', 'The chairman is furious: the rift is now public.']],
  },
  {
    id: 'bd_women_team', cat: 'board', w: 2, repeat: 120,
    when: {},
    o: [
      { fx: { reputation: 2, fans: 3, budget: -0.3 } },
      { fx: {} },
    ],
    it: ['La squadra femminile', 'La società chiede al tuo staff di condividere il centro sportivo e qualche metodologia con la squadra femminile.',
      ['Con piacere', 'Una bella collaborazione: il club ne esce con un’immagine migliore.'],
      ['Preferisco strutture separate', 'Ognuno per la sua strada.']],
    en: ['The women’s team', 'The club asks your staff to share the training ground and some methods with the women’s team.',
      ['With pleasure', 'A fine collaboration: the club’s image improves.'],
      ['I prefer separate facilities', 'Each goes their own way.']],
  },
  {
    id: 'bd_financial_fair_play', cat: 'finance', w: 3, repeat: 90,
    when: { mdMin: 15, budgetMin: 10 },
    o: [
      { fx: { budgetPct: -0.4, trust: 3 } },
      { odds: { base: 0.5, good: { budgetPct: -0.1 }, bad: { budgetPct: -0.5, reputation: -3, trust: -5 } } },
    ],
    it: ['Controlli sui conti', 'La federazione avvia un controllo sui conti del club: potrebbero arrivare limiti al mercato.',
      ['Collaboriamo e riduciamo le spese', 'Niente sanzioni, ma il budget si riduce parecchio.'],
      ['Gli avvocati del club faranno ricorso', 'Il ricorso funziona: quasi nessuna conseguenza.', 'Il ricorso peggiora le cose: sanzione pesante e cattiva stampa.']],
    en: ['Financial checks', 'The federation opens an investigation into the club’s accounts: transfer limits could follow.',
      ['Cooperate and cut spending', 'No sanctions, but the budget shrinks a lot.'],
      ['The club’s lawyers will appeal', 'The appeal works: almost no consequences.', 'The appeal makes it worse: a heavy sanction and bad press.']],
  },
  {
    id: 'bd_captain_board', cat: 'board', w: 3, repeat: 60,
    when: { mdMin: 6, player: { captain: true } },
    o: [
      { fx: { trust: 4, bond: -12, morale: -8 } },
      { fx: { trust: -4, bond: 15, morale: 8, teamMorale: 3 } },
    ],
    it: ['Il capitano contro la società', '{player} ha criticato pubblicamente la società per come tratta i giocatori. Il presidente vuole che tu gli tolga la fascia.',
      ['Gli tolgo la fascia', 'La società apprezza la fermezza. {player} non te lo perdonerà facilmente.'],
      ['Difendo il mio capitano', 'Lo spogliatoio è con te. Il presidente se lo lega al dito.']],
    en: ['The captain against the club', '{player} publicly criticised the club over how it treats players. The chairman wants you to take away his armband.',
      ['Take the armband away', 'The club likes the firmness. {player} won’t forgive you easily.'],
      ['Stand by my captain', 'The dressing room is with you. The chairman won’t forget it.']],
  },
  {
    id: 'bd_youth_quota', cat: 'youth', w: 4, repeat: 45,
    when: { mdMin: 3, player: { ageMax: 20, starter: false } },
    o: [
      { fx: { trust: 5, promiseStarts: { need: 2, within: 6 }, morale: 10 } },
      { fx: { trust: -4 } },
    ],
    it: ['“Più spazio ai giovani”', 'La società ti chiede di far giocare {player}, uno dei talenti del vivaio: vogliono valorizzarlo.',
      ['Gli darò due partite da titolare', 'La società è soddisfatta. Ora quelle due partite vanno date davvero.'],
      ['Gioca chi merita', 'Scelta coerente, ma la società avrebbe voluto un’altra risposta.']],
    en: ['“More room for youngsters”', 'The club asks you to play {player}, one of the academy talents: they want to raise his value.',
      ['I’ll give him two starts', 'The club is satisfied. Now those two starts really have to happen.'],
      ['Whoever deserves it plays', 'A consistent choice, but the club wanted a different answer.']],
  },
  {
    id: 'bd_bus_breakdown', cat: 'staff', w: 3, repeat: 60,
    when: { mdMin: 1 },
    o: [
      { fx: { nextMatch: { tempo: 0.95, control: 0.97 }, teamFitness: -4 } },
      { fx: { budget: -0.15, teamMorale: 2 } },
    ],
    it: ['Il pullman si rompe', 'Alla vigilia della trasferta il pullman della squadra si guasta: si rischia di arrivare in albergo a notte fonda.',
      ['Aspettiamo il meccanico', 'Arrivate alle due di notte: la squadra dorme poco.'],
      ['Treno ad alta velocità, subito', 'Costa qualcosa, ma la squadra arriva riposata e di buon umore.']],
    en: ['The coach breaks down', 'The night before the away trip the team coach breaks down: you risk reaching the hotel in the middle of the night.',
      ['Wait for the mechanic', 'You arrive at two in the morning: the team barely sleeps.'],
      ['High-speed train, right now', 'It costs a bit, but the team arrives rested and in good spirits.']],
  },
  {
    id: 'bd_president_son', cat: 'board', w: 2, repeat: 120,
    when: { mdMin: 2 },
    o: [
      { fx: { trust: 5, teamMorale: -3 } },
      { fx: { trust: -5, reputation: 1 } },
    ],
    it: ['Il nipote del presidente', 'Il presidente chiede di far allenare con la prima squadra il nipote, diciassettenne di talento “a sentire lui”.',
      ['Va bene, qualche allenamento', 'Il presidente è contento. I giocatori ridono sotto i baffi.'],
      ['Prima deve passare dalla Primavera', 'Risposta corretta. Il presidente però ci resta male.']],
    en: ['The chairman’s nephew', 'The chairman asks you to let his nephew train with the first team: a seventeen-year-old talent, “according to him”.',
      ['Fine, a few sessions', 'The chairman is happy. The players snigger.'],
      ['He has to go through the youth team first', 'The right answer. The chairman is still hurt.']],
  },
  {
    id: 'bd_naming_rights', cat: 'finance', w: 3, repeat: 150,
    when: {},
    o: [
      { fx: { budget: 5, fans: -7 } },
      { fx: { fans: 5, trust: -2 } },
    ],
    it: ['Il nome dello stadio', 'Un’azienda offre molti soldi per dare il suo nome allo stadio storico. I tifosi sono in allarme.',
      ['Diciamo di sì', 'Arriva una bella cifra. I tifosi però non chiameranno mai lo stadio con il nuovo nome.'],
      ['Lo stadio non si tocca', 'I tifosi ti adorano. La società rinuncia a malincuore ai soldi.']],
    en: ['The stadium name', 'A company offers a lot of money to put its name on the historic stadium. The fans are alarmed.',
      ['Say yes', 'A big sum arrives. The fans will never call the stadium by its new name.'],
      ['The stadium stays as it is', 'The fans adore you. The club reluctantly gives up the money.']],
  },
  {
    id: 'bd_pitch_invasion_fine', cat: 'fans', w: 3, repeat: 60,
    when: { last: 'W', mdMin: 3 },
    o: [
      { fx: { budget: -0.5, fans: 2 } },
      { fx: { fans: -5, trust: 3 } },
    ],
    it: ['Multa per l’invasione', 'Dopo la vittoria alcuni tifosi sono entrati in campo per festeggiare. Arriva una multa salata.',
      ['Il club paga e chiude la questione', 'I tifosi apprezzano che il club non li abbia attaccati.'],
      ['Chiedo al club di individuare i responsabili', 'Linea dura: la società approva, la curva no.']],
    en: ['Fine for the pitch invasion', 'After the win some fans ran onto the pitch to celebrate. A hefty fine arrives.',
      ['The club pays and moves on', 'The fans appreciate that the club didn’t turn on them.'],
      ['Ask the club to identify those responsible', 'A hard line: the board approves, the ultras don’t.']],
  },
  {
    id: 'bd_loan_policy', cat: 'market', w: 3, repeat: 80,
    when: { window: true },
    o: [
      { fx: { budget: 2, youngsters: { potential: 1, morale: -2 } } },
      { fx: { youngsters: { morale: 4 } } },
    ],
    it: ['La politica dei prestiti', 'Il direttore sportivo vuole mandare in prestito a pagamento i giovani che giocano poco, per fare cassa e farli crescere.',
      ['D’accordo', 'Qualche soldo in cassa e minuti per i ragazzi altrove. Alcuni non volevano partire.'],
      ['Li voglio tenere qui ad allenarsi con me', 'I ragazzi restano e si sentono considerati.']],
    en: ['The loan policy', 'The sporting director wants to loan out, for a fee, the youngsters who hardly play: money in and minutes for them.',
      ['Agreed', 'Some money in and minutes for the kids elsewhere. A few didn’t want to go.'],
      ['I want to keep them here training with me', 'The youngsters stay and feel valued.']],
  },
  {
    id: 'bd_medical_tech', cat: 'medical', w: 3, repeat: 90,
    when: {},
    o: [
      { fx: { budget: -0.7, teamFitness: 5, staff: 3 } },
      { fx: {} },
    ],
    it: ['Tecnologia per il recupero', 'Lo staff medico chiede una criosauna e sensori GPS per monitorare i carichi di lavoro.',
      ['Compriamo tutto', 'La squadra recupera meglio tra una partita e l’altra.'],
      ['Si recupera come sempre', 'Nessuna spesa extra.']],
    en: ['Recovery technology', 'The medical staff ask for a cryo-chamber and GPS sensors to monitor workloads.',
      ['Buy it all', 'The team recovers better between matches.'],
      ['We recover the way we always have', 'No extra spending.']],
  },
  {
    id: 'bd_friendly_money', cat: 'finance', w: 4, repeat: 40,
    when: { mdMin: 6, window: false },
    o: [
      { fx: { budget: 1.5, teamFitness: -8 } },
      { fx: { teamFitness: 2 } },
    ],
    it: ['Un’amichevole ricca', 'Durante la sosta arriva l’invito a un’amichevole all’estero con un ingaggio importante.',
      ['Accettiamo: soldi facili', 'Il budget cresce, le gambe un po’ meno fresche.'],
      ['La sosta serve per riposare', 'La squadra ricarica le energie.']],
    en: ['A lucrative friendly', 'During the international break an invitation arrives for a friendly abroad with a big appearance fee.',
      ['Accept: easy money', 'The budget grows, the legs are a little less fresh.'],
      ['The break is for resting', 'The team recharges.']],
  },
  {
    id: 'bd_social_media_team', cat: 'press', w: 3, repeat: 80,
    when: {},
    o: [
      { fx: { fans: 4, teamMorale: -2 } },
      { fx: { teamMorale: 2 } },
    ],
    it: ['Le telecamere nello spogliatoio', 'L’ufficio comunicazione vuole girare contenuti dietro le quinte, anche negli spogliatoi prima delle partite.',
      ['Va bene, i tifosi apprezzeranno', 'I video spopolano. Qualche giocatore però si sente osservato.'],
      ['Lo spogliatoio resta privato', 'I giocatori apprezzano la privacy.']],
    en: ['Cameras in the dressing room', 'The communications office wants to film behind-the-scenes content, including in the dressing room before matches.',
      ['Fine, the fans will love it', 'The videos go viral. Some players feel watched, though.'],
      ['The dressing room stays private', 'The players appreciate the privacy.']],
  },
  {
    id: 'bd_documentary', cat: 'press', w: 3, repeat: 150,
    when: { mdMax: 3 },
    o: [
      { fx: { budget: 2, reputation: 3, teamMorale: -3, setFlag: 'documentary' } },
      { fx: { teamMorale: 1 } },
    ],
    it: ['Un documentario sulla stagione', 'Una piattaforma di streaming vuole seguire la squadra per tutta la stagione e farne una serie.',
      ['Accettiamo', 'Soldi e fama: tutti conosceranno il tuo metodo. Le telecamere però non si spengono mai.'],
      ['No, grazie', 'Si lavora lontano dai riflettori.']],
    en: ['A season documentary', 'A streaming platform wants to follow the team all season and turn it into a series.',
      ['Accept', 'Money and fame: everyone will know your methods. But the cameras never switch off.'],
      ['No, thank you', 'Work continues away from the spotlight.']],
  },
  {
    id: 'bd_documentary_scene', cat: 'press', w: 4, repeat: 30,
    when: { flag: 'documentary', streakL: 1 },
    o: [
      { fx: { reputation: 2, teamMorale: -4 } },
      { fx: { reputation: -1, budget: -0.5 } },
    ],
    it: ['La scena della sfuriata', 'Le telecamere hanno ripreso la tua sfuriata all’intervallo. La produzione vuole metterla nella prima puntata.',
      ['Va bene, è la verità', 'La scena diventa virale: sembri un allenatore vero. Qualche giocatore si sente esposto.'],
      ['Pago la penale per tagliarla', 'La scena sparisce, e un po’ di soldi con lei.']],
    en: ['The rant scene', 'The cameras caught your half-time rant. The producers want it in the first episode.',
      ['Fine, it’s the truth', 'The scene goes viral: you look like a real manager. Some players feel exposed.'],
      ['Pay the penalty to cut it', 'The scene disappears, and some money with it.']],
  },
  {
    id: 'bd_ceo_budget_bonus', cat: 'finance', w: 4, repeat: 60,
    when: { mdMin: 10, gapMax: -2 },
    o: [
      { fx: { budgetPct: 0.3, trust: 3 } },
      { fx: { teamMorale: 5, budget: -0.5 } },
    ],
    it: ['Premio della società', 'La stagione va oltre le attese: la società vuole premiarti. Puoi scegliere come.',
      ['Più budget per il mercato di gennaio', 'La società aumenta il budget.'],
      ['Una cena di squadra e un premio ai giocatori', 'Il gruppo festeggia: il clima è splendido.']],
    en: ['A reward from the club', 'The season is going beyond expectations: the club wants to reward you. You can choose how.',
      ['More budget for the January window', 'The club increases the budget.'],
      ['A team dinner and a bonus for the players', 'The squad celebrates: the atmosphere is superb.']],
  },
  {
    id: 'bd_travel_policy', cat: 'staff', w: 3, repeat: 60,
    when: {},
    o: [
      { fx: { budget: -0.3, teamFitness: 4 } },
      { fx: { budget: 0.2, teamFitness: -3 } },
    ],
    it: ['Voli charter', 'Per le trasferte lontane lo staff chiede voli charter invece dei voli di linea con scalo.',
      ['Charter per tutte le trasferte lunghe', 'Viaggi più brevi, squadra più fresca.'],
      ['Voli di linea: si risparmia', 'Qualche ora in più negli aeroporti, qualche euro in più in cassa.']],
    en: ['Charter flights', 'For long away trips the staff ask for charter flights instead of scheduled flights with layovers.',
      ['Charter for all long trips', 'Shorter journeys, fresher team.'],
      ['Scheduled flights: save money', 'A few more hours in airports, a few more euros in the bank.']],
  },
  {
    id: 'bd_nutritionist_chef', cat: 'staff', w: 3, repeat: 90,
    when: {},
    o: [
      { fx: { budget: -0.4, teamFitness: 3, teamMorale: -1 } },
      { fx: { teamMorale: 2 } },
    ],
    it: ['Il cuoco del centro sportivo', 'Il nutrizionista vuole cambiare il menù della mensa: niente pasta a pranzo, solo cibi calibrati.',
      ['Si cambia menù', 'I giocatori mugugnano, ma i test fisici migliorano.'],
      ['La pasta non si tocca', 'I giocatori ringraziano.']],
    en: ['The training ground chef', 'The nutritionist wants to change the canteen menu: no pasta at lunch, only measured meals.',
      ['Change the menu', 'The players grumble, but the fitness tests improve.'],
      ['Leave the pasta alone', 'The players are grateful.']],
  },
  {
    id: 'bd_referee_complaint', cat: 'board', w: 4, repeat: 30,
    when: { last: 'L', mdMin: 2 },
    o: [
      { fx: { fans: 5, reputation: -2, suspendCoach: 1 } },
      { fx: { reputation: 2, fans: -2 } },
    ],
    it: ['Il presidente contro l’arbitro', 'Dopo la sconfitta il presidente vuole che tu attacchi l’arbitro in conferenza stampa: “Dì quello che pensi”.',
      ['Attacco l’arbitro', 'I tifosi esultano. Il giudice sportivo ti squalifica per una giornata.'],
      ['Parlo solo della partita', 'Risposta signorile: guadagni rispetto, ma la piazza voleva sangue.']],
    en: ['The chairman against the referee', 'After the defeat the chairman wants you to attack the referee at the press conference: “Say what you think”.',
      ['Attack the referee', 'The fans cheer. The disciplinary judge bans you for one match.'],
      ['Talk only about the match', 'A classy answer: you earn respect, but the fans wanted blood.']],
  },
  {
    id: 'bd_old_legend_role', cat: 'staff', w: 3, repeat: 120,
    when: {},
    o: [
      { fx: { fans: 5, staff: -2, teamMorale: 2 } },
      { fx: { fans: -2 } },
    ],
    it: ['Una bandiera nello staff', 'La società vuole inserire nello staff una vecchia bandiera del club, amatissimo dai tifosi ma senza esperienza da allenatore.',
      ['Benvenuto', 'I tifosi sono entusiasti e lo spogliatoio lo ascolta. Tecnicamente aiuta poco.'],
      ['Lo staff lo scelgo io', 'Scelta professionale. I tifosi la vivono come uno sgarbo.']],
    en: ['A club legend on the staff', 'The club wants to add an old club legend to your staff: adored by fans, but no coaching experience.',
      ['Welcome aboard', 'The fans are thrilled and the dressing room listens to him. Technically he helps little.'],
      ['I choose my staff', 'A professional choice. The fans see it as a snub.']],
  },
  {
    id: 'bd_pitch_winter', cat: 'staff', w: 3, repeat: 40,
    when: { mdMin: 14, mdMax: 24 },
    o: [
      { fx: { budget: -0.3, nextMatch: { control: 1.03 } } },
      { fx: { nextMatch: { control: 0.95, direct: 1.05 } } },
    ],
    it: ['Campo ghiacciato', 'Il freddo ha gelato il campo di casa: il pallone non rotola. Il custode propone un riscaldamento del terreno d’urgenza.',
      ['Paghiamo il riscaldamento del prato', 'Il campo torna giocabile: si potrà fare il proprio gioco.'],
      ['Adattiamoci: palla lunga', 'Campo pesante: meno palleggio, più lanci.']],
    en: ['A frozen pitch', 'The cold has frozen the home pitch: the ball won’t roll. The groundsman proposes emergency pitch heating.',
      ['Pay for the pitch heating', 'The pitch is playable again: you can play your own game.'],
      ['Adapt: go long', 'Heavy pitch: less passing, more long balls.']],
  },
  {
    id: 'bd_agent_influence', cat: 'market', w: 3, repeat: 60,
    when: { window: true },
    o: [
      { fx: { trust: 4, teamMorale: -3, budget: -0.5 } },
      { fx: { trust: -4, reputation: 2 } },
    ],
    it: ['Il procuratore amico del presidente', 'Un procuratore molto vicino al presidente propone tre giocatori mediocri a prezzi alti. Il presidente “consiglia” di prenderne uno.',
      ['Ne prendo uno per quieto vivere', 'Il presidente è contento. Un giocatore inutile in rosa e soldi sprecati.'],
      ['Non mi servono', 'Hai detto di no a un amico del presidente: la tua indipendenza fa notizia.']],
    en: ['The chairman’s friend, the agent', 'An agent very close to the chairman offers three mediocre players at high prices. The chairman “suggests” signing one.',
      ['Sign one to keep the peace', 'The chairman is happy. A useless player in the squad and money wasted.'],
      ['I don’t need them', 'You said no to the chairman’s friend: your independence makes the news.']],
  },
  {
    id: 'bd_away_fans_trip', cat: 'fans', w: 3, repeat: 60,
    when: {},
    o: [
      { fx: { fans: 6, budget: -0.3 } },
      { fx: {} },
    ],
    it: ['I pullman per i tifosi', 'Per la prossima trasferta il club può offrire i pullman ai tifosi. Il capitano dice che sentirli vicini farebbe la differenza.',
      ['Il club offre i pullman', 'Il settore ospiti è pieno: la squadra sente la spinta.'],
      ['Non è una spesa necessaria', 'Settore ospiti semivuoto.']],
    en: ['Coaches for the fans', 'For the next away game the club can provide coaches for the fans. The captain says having them close would make a difference.',
      ['The club pays for the coaches', 'The away end is packed: the team feels the push.'],
      ['Not a necessary expense', 'A half-empty away end.']],
  },
  {
    id: 'bd_ethics_code', cat: 'board', w: 3, repeat: 90,
    when: {},
    o: [
      { fx: { trust: 3, teamMorale: -3, teamFitness: 2 } },
      { fx: { teamMorale: 3, trust: -1 } },
    ],
    it: ['Il codice di comportamento', 'La società vuole introdurre un codice di comportamento: coprifuoco, niente social dopo le 22, multe salate.',
      ['Lo firmo e lo faccio rispettare', 'Più disciplina e più riposo. Qualche giocatore si sente trattato da ragazzino.'],
      ['I miei giocatori sono professionisti', 'Lo spogliatoio apprezza la fiducia.']],
    en: ['The code of conduct', 'The club wants to introduce a code of conduct: curfew, no social media after 10pm, hefty fines.',
      ['Sign it and enforce it', 'More discipline and more rest. Some players feel treated like kids.'],
      ['My players are professionals', 'The dressing room appreciates the trust.']],
  },
  {
    id: 'bd_president_dinner', cat: 'board', w: 4, repeat: 40,
    when: { mdMin: 4 },
    o: [
      { fx: { trust: 5, teamFitness: -2 } },
      { fx: { trust: -2 } },
    ],
    it: ['Cena con il presidente', 'Il presidente ti invita a cena con gli sponsor la sera prima di un allenamento a porte chiuse.',
      ['Ci vado', 'Serata utile: il presidente ti presenta come il suo uomo di fiducia.'],
      ['Declino: il lavoro prima di tutto', 'Il presidente capisce, ma ci resta male.']],
    en: ['Dinner with the chairman', 'The chairman invites you to dinner with the sponsors the night before a closed training session.',
      ['Go', 'A useful evening: the chairman introduces you as his trusted man.'],
      ['Decline: work comes first', 'The chairman understands, but he’s hurt.']],
  },
  {
    id: 'bd_budget_bonus_winter', cat: 'finance', w: 4, repeat: 50,
    when: { window: true, trustMin: 55, mdMin: 10 },
    o: [
      { fx: { budgetPct: 0.25 } },
      { fx: { trust: 4 } },
    ],
    it: ['Un tesoretto per gennaio', 'La società ha chiuso un buon accordo commerciale: ti chiede se vuoi usare i soldi sul mercato o metterli da parte.',
      ['Sul mercato: servono rinforzi', 'Budget aumentato per la finestra di gennaio.'],
      ['Mettiamoli da parte', 'La società apprezza la prudenza.']],
    en: ['A little treasure for January', 'The club has closed a good commercial deal: it asks if you want to use the money in the window or save it.',
      ['In the window: we need reinforcements', 'Budget increased for the January window.'],
      ['Let’s save it', 'The club appreciates the caution.']],
  },
  {
    id: 'bd_video_room', cat: 'staff', w: 3, repeat: 90,
    when: { mdMin: 3 },
    o: [
      { fx: { budget: -0.3, familiarity: 6, teamFitness: -2 } },
      { fx: { teamFitness: 2 } },
    ],
    it: ['La sala video', 'Il tuo vice propone una sessione video di un’ora ogni giorno per studiare i movimenti del tuo gioco.',
      ['Tutti in sala video', 'La squadra capisce il gioco più in fretta.'],
      ['Meglio correre che guardare video', 'Più campo, meno teoria.']],
    en: ['The video room', 'Your assistant proposes an hour of video every day to study the movements of your system.',
      ['Everyone to the video room', 'The team grasps the system faster.'],
      ['Better running than watching videos', 'More pitch, less theory.']],
  },
];
