/* Catene: una scelta oggi, il conto fra qualche settimana. Ogni evento di
   partenza apre un seguito (chainOnly) che arriva `in` giornate dopo, a volte
   solo se la prima scelta è andata bene o male (chainOn). */

export default [
  {
    id: 'ch_painkiller_star', cat: 'medical', w: 4, repeat: 30,
    when: { mdMin: 3, player: { rankMax: 5, injured: false, fitnessMax: 92 } },
    o: [
      { fx: { flag: 'playingHurt', morale: 4, nextMatch: { attack: 1.03 } }, chain: { id: 'ch_painkiller_after', in: 3 } },
      { fx: { fitness: 12, morale: -3, nextMatch: { attack: 0.97 } } },
    ],
    it: ['Il dolore di {player}', '{player} ha un fastidio al flessore. Il medico dice che con le infiltrazioni può giocare, ma il rischio c’è.',
      ['Gioca con le infiltrazioni', '{player} stringe i denti ed è in campo.'],
      ['Riposo: prima la salute', '{player} salta l’allenamento e recupera. Non è contento.']],
    en: ['{player}’s pain', '{player} has a hamstring niggle. The doctor says he can play with injections, but there is a risk.',
      ['He plays with injections', '{player} grits his teeth and plays.'],
      ['Rest: health comes first', '{player} skips training and recovers. He isn’t happy.']],
  },
  {
    id: 'ch_painkiller_after', cat: 'medical', w: 1, chainOnly: true,
    when: { player: {} },
    o: [
      { odds: { base: 0.55, age: -0.02, good: { unflag: 'playingHurt', form: 3, bond: 6 }, bad: { unflag: 'playingHurt', injury: 5, injuryProne: 8, bond: -4 } } },
      { fx: { unflag: 'playingHurt', fitness: 10, form: -2 } },
    ],
    it: ['Le infiltrazioni di {player}', 'Sono settimane che {player} gioca sul dolore. Lo staff medico chiede se continuare.',
      ['Ancora una partita, poi si vede', 'Il fastidio passa: {player} è in forma e ti è grato.', 'Il flessore cede: {player} starà fuori più di un mese.'],
      ['Basta così: si ferma', '{player} si ferma in tempo. Perde un po’ di ritmo.']],
    en: ['{player}’s injections', '{player} has been playing through pain for weeks. The medical staff ask whether to carry on.',
      ['One more match, then we’ll see', 'The pain eases: {player} is in form and grateful.', 'The hamstring gives way: {player} is out for over a month.'],
      ['That’s enough: he stops', '{player} stops in time. He loses a little rhythm.']],
  },
  {
    id: 'ch_referee_rant', cat: 'press', w: 4, repeat: 25,
    when: { last: 'L', mdMin: 2 },
    o: [
      { fx: { teamMorale: 5, fans: 4 }, chain: { id: 'ch_referee_hearing', in: 2 } },
      { fx: { reputation: 2, teamMorale: -2 } },
    ],
    it: ['L’arbitraggio', 'Il {club} ha perso con un rigore molto dubbio contro. I microfoni sono accesi.',
      ['Attacco l’arbitro senza giri di parole', 'Lo spogliatoio e i tifosi sono con te. La procura federale prende nota.'],
      ['“Abbiamo sbagliato noi”', 'Risposta da signore. Qualcuno nello spogliatoio avrebbe voluto più grinta.']],
    en: ['The refereeing', '{club} lost to a very dubious penalty. The microphones are on.',
      ['Attack the referee without mincing words', 'The dressing room and fans are with you. The disciplinary committee takes note.'],
      ['“We made the mistakes”', 'A gentleman’s answer. Some in the dressing room wanted more fight.']],
  },
  {
    id: 'ch_referee_hearing', cat: 'board', w: 1, chainOnly: true,
    when: {},
    o: [
      { odds: { base: 0.45, rep: 0.008, good: { reputation: 1 }, bad: { suspendCoach: 1, budget: -0.2, trust: -3 } } },
      { fx: { reputation: -2, trust: 2 } },
    ],
    it: ['La procura federale', 'Le tue parole sull’arbitro sono finite davanti al giudice sportivo. Puoi difenderti o chiedere scusa.',
      ['Mi difendo: ho detto la verità', 'Il giudice archivia: nessuna sanzione.', 'Una giornata di squalifica e una multa: in panchina andrà il vice.'],
      ['Chiedo scusa pubblicamente', 'Nessuna squalifica. La tua immagine ne esce un po’ ammaccata.']],
    en: ['The disciplinary hearing', 'Your words about the referee have reached the disciplinary judge. You can defend yourself or apologise.',
      ['Defend myself: I told the truth', 'The judge drops the case: no sanction.', 'A one-match touchline ban and a fine: your assistant will be on the bench.'],
      ['Apologise publicly', 'No ban. Your image takes a slight knock.']],
  },
  {
    id: 'ch_teen_agent', cat: 'youth', w: 4, repeat: 60,
    when: { player: { ageMax: 20, potentialGap: 8 } },
    o: [
      { fx: { wage: 0.8, contract: 2, morale: 8, bond: 6, budget: -0.2 } },
      { fx: { morale: -6 }, chain: { id: 'ch_teen_agent_offer', in: 6 } },
    ],
    it: ['Il procuratore di {player}', 'Il procuratore di {player} chiede un contratto da professionista vero, altrimenti “valuteremo altre proposte”.',
      ['Rinnovo e aumento subito', '{player} firma felice: il talento resta a casa.'],
      ['Nessun ricatto: deve meritarselo', '{player} è deluso. Il procuratore esce sbattendo la porta.']],
    en: ['{player}’s agent', '{player}’s agent wants a proper professional contract, or else “we’ll consider other offers”.',
      ['Renew with a raise right away', '{player} signs happily: the talent stays home.'],
      ['No blackmail: he has to earn it', '{player} is disappointed. The agent storms out.']],
  },
  {
    id: 'ch_teen_agent_offer', cat: 'market', w: 1, chainOnly: true,
    when: { player: {} },
    o: [
      { fx: { sell: 1.3 } },
      { fx: { wage: 1.2, contract: 3, morale: 2, budget: -0.6 } },
      { odds: { base: 0.4, pers: { professionista: 0.25, leader: 0.1, ambizioso: -0.25 }, bond: 0.008, good: { morale: 6, bond: 10 }, bad: { morale: -15, bond: -15, flag: 'wantsOut' } } },
    ],
    it: ['Un grande club su {player}', 'Come promesso dal procuratore, un grande club offre molto più del valore di {player} ({value}).',
      ['Vendo: offerta irripetibile', '{player} parte. Nelle casse entra una cifra importante.'],
      ['Pareggio l’ingaggio e lo blindo', 'Contratto lungo e stipendio da titolare: {player} resta.'],
      ['Lo convinco a restare senza soldi', '{player} sceglie il progetto: resta e si lega al club.', '{player} si sente trattenuto contro la sua volontà e chiede la cessione.']],
    en: ['A big club wants {player}', 'Just as the agent warned, a big club offers far more than {player}’s value ({value}).',
      ['Sell: an offer you can’t refuse', '{player} leaves. A big fee comes in.'],
      ['Match the wages and tie him down', 'A long contract and a starter’s salary: {player} stays.'],
      ['Convince him to stay without money', '{player} buys into the project: he stays and commits to the club.', '{player} feels held against his will and asks to leave.']],
  },
  {
    id: 'ch_style_revolution', cat: 'style', w: 3, repeat: 45,
    when: { mdMin: 4, mdMax: 28, winless: 2 },
    o: [
      { fx: { familiarity: -10, teamMorale: 3 }, chain: { id: 'ch_style_revolution_review', in: 5 } },
      { fx: { familiarity: 4, trust: -2 } },
    ],
    it: ['La rivoluzione tattica', 'Il vice propone di stravolgere il modo di giocare: nuove distanze, nuovi movimenti, due settimane di lavoro intenso.',
      ['Rivoluzione: si ricomincia', 'La squadra riparte da zero sui principi di gioco. Serve pazienza.'],
      ['Si insiste su quello che sappiamo fare', 'Più automatismi, ma la dirigenza si aspettava una scossa.']],
    en: ['The tactical revolution', 'Your assistant proposes overhauling the way you play: new distances, new movements, two weeks of intense work.',
      ['Revolution: start again', 'The team starts from scratch on its principles. Patience needed.'],
      ['Stick with what we know', 'Better automatisms, but the board expected a jolt.']],
  },
  {
    id: 'ch_style_revolution_review', cat: 'style', w: 1, chainOnly: true,
    when: {},
    o: [
      { odds: { base: 0.5, teamMorale: 0.01, good: { familiarity: 22, teamMorale: 5, trust: 3 }, bad: { familiarity: 5, teamMorale: -5, trust: -4 } } },
    ],
    it: ['Il bilancio della rivoluzione', 'Sono passate cinque giornate dalla svolta tattica. È il momento di capire se la squadra l’ha assorbita.',
      ['Vediamo in allenamento', 'I giocatori si muovono a memoria: il nuovo calcio funziona.', 'Troppa confusione: metà squadra non ha capito i movimenti.']],
    en: ['The revolution’s verdict', 'Five matchdays have passed since the tactical overhaul. Time to see if the team has absorbed it.',
      ['Let’s see in training', 'The players move by memory: the new football works.', 'Too much confusion: half the team hasn’t understood the movements.']],
  },
  {
    id: 'ch_ultras_tickets', cat: 'fans', w: 3, repeat: 50,
    when: { mdMin: 2 },
    o: [
      { fx: { budget: -0.4, fans: 6 }, chain: { id: 'ch_ultras_away_day', in: 6 } },
      { fx: { fans: -5, trust: 2 } },
    ],
    it: ['I biglietti della curva', 'Il gruppo organizzato chiede al club di pagare metà dei biglietti per le trasferte.',
      ['Il club paga', 'La curva ringrazia con uno striscione. In trasferta saranno tanti.'],
      ['Non è compito del club', 'La società approva. La curva no.']],
    en: ['The ultras’ tickets', 'The organised supporters ask the club to pay half the cost of away tickets.',
      ['The club pays', 'The ultras say thanks with a banner. There’ll be plenty of them away from home.'],
      ['That’s not the club’s job', 'The board approves. The ultras don’t.']],
  },
  {
    id: 'ch_ultras_away_day', cat: 'fans', w: 1, chainOnly: true,
    when: {},
    o: [
      { odds: { base: 0.6, fans: 0.005, good: { teamMorale: 6, nextMatch: { attack: 1.04 } }, bad: { budget: -0.5, trust: -4, fans: -2 } } },
      { fx: { fans: -3, trust: 1 } },
    ],
    it: ['La trasferta dei tifosi', 'Grazie ai biglietti pagati dal club, in trasferta arriveranno migliaia di tifosi. La questura chiede garanzie.',
      ['Ci fidiamo dei nostri tifosi', 'Settore ospiti pieno e colorato: la squadra vola.', 'Fumogeni e scontri: multa salata e dirigenza furiosa.'],
      ['Riduciamo i biglietti per sicurezza', 'Trasferta tranquilla, tifosi delusi.']],
    en: ['The fans’ away day', 'Thanks to the club-funded tickets, thousands of fans will travel. The police ask for guarantees.',
      ['We trust our fans', 'A full, colourful away end: the team flies.', 'Flares and clashes: a heavy fine and a furious board.'],
      ['Cut the tickets for safety', 'A quiet away day, disappointed fans.']],
  },
  {
    id: 'ch_senior_feud', cat: 'dressing', w: 4, repeat: 35,
    when: { mdMin: 3, player: { rankMax: 10, ageMin: 27, captain: false } },
    o: [
      { fx: { morale: -8, bond: -8, senior: { morale: 3 } }, chain: { id: 'ch_senior_feud_after', in: 4 } },
      { fx: { morale: 6, bond: 6, senior: { morale: -4 }, teamMorale: -2 } },
      { odds: { base: 0.5, pers: { leader: 0.15, ribelle: -0.2 }, good: { morale: 3, teamMorale: 4 }, bad: { morale: -5, teamMorale: -4 } } },
    ],
    it: ['Lite fra senatori', '{player} e il capitano sono venuti alle mani in allenamento. Tutti guardano te.',
      ['Do ragione al capitano', 'La gerarchia è salva. {player} se la lega al dito.'],
      ['Do ragione a {player}', '{player} si sente capito. Gli altri senatori storcono il naso.'],
      ['Li chiudo in una stanza finché non fanno pace', 'Si stringono la mano: il gruppo ne esce più forte.', 'La pace è finta: il clima resta pesante.']],
    en: ['Senior players’ feud', '{player} and the captain came to blows in training. Everyone is looking at you.',
      ['Side with the captain', 'The hierarchy holds. {player} won’t forget it.'],
      ['Side with {player}', '{player} feels understood. The other senior players frown.'],
      ['Lock them in a room until they make peace', 'They shake hands: the group comes out stronger.', 'The peace is fake: the atmosphere stays heavy.']],
  },
  {
    id: 'ch_senior_feud_after', cat: 'dressing', w: 1, chainOnly: true,
    when: { player: {} },
    o: [
      { odds: { base: 0.45, bond: 0.01, pers: { professionista: 0.2, ribelle: -0.2 }, good: { bond: 12, morale: 8 }, bad: { flag: 'wantsOut', morale: -10 } } },
      { fx: { bond: -5, morale: -5, suspended: 1 } },
    ],
    it: ['{player} non dimentica', 'Dopo la lite con il capitano, {player} si allena in disparte e parla poco.',
      ['Lo prendo da parte e chiarisco', '{player} apprezza il gesto: la ferita si chiude.', '{player} chiede al procuratore di trovargli un’altra squadra.'],
      ['Lo lascio in tribuna una partita', '{player} capisce il messaggio, ma il rapporto si raffredda.']],
    en: ['{player} doesn’t forget', 'After the fight with the captain, {player} trains apart and barely speaks.',
      ['Take him aside and clear the air', '{player} appreciates it: the wound heals.', '{player} asks his agent to find him another club.'],
      ['Leave him in the stands for a match', '{player} gets the message, but the relationship cools.']],
  },
  {
    id: 'ch_money_friendly', cat: 'finance', w: 3, repeat: 45,
    when: { mdMin: 6, mdMax: 30 },
    o: [
      { fx: { budget: 1.2, teamFitness: -4 }, chain: { id: 'ch_money_friendly_after', in: 2 } },
      { fx: { teamFitness: 3, trust: -1 } },
    ],
    it: ['L’amichevole milionaria', 'Uno sceicco offre un milione e duecentomila euro per un’amichevole all’estero durante la sosta.',
      ['Accettiamo: i soldi servono', 'Soldi in cassa, ma dodici ore di volo nelle gambe.'],
      ['Rifiutiamo: la sosta serve a riposare', 'Squadra riposata. La società ci ha rinunciato a malincuore.']],
    en: ['The money-spinning friendly', 'A sheikh offers €1.2 million for a friendly abroad during the international break.',
      ['Accept: we need the money', 'Money in the bank, but twelve hours of flying in the legs.'],
      ['Decline: the break is for resting', 'A rested team. The board gave up the money reluctantly.']],
  },
  {
    id: 'ch_money_friendly_after', cat: 'medical', w: 1, chainOnly: true,
    when: {},
    o: [
      { odds: { base: 0.55, good: { teamMorale: 4 }, bad: { teamFitness: -6, nextMatch: { control: 0.95, press: 0.93 } } } },
      { fx: { teamFitness: 6, familiarity: -2 } },
    ],
    it: ['Il ritorno dal viaggio', 'La squadra è appena rientrata dall’amichevole all’estero. Il preparatore atletico teme il fuso orario.',
      ['Allenamento normale', 'Il viaggio ha unito il gruppo, nessuna conseguenza.', 'Gambe pesanti e testa altrove: la squadra è stanca.'],
      ['Due giorni di solo recupero', 'Energie recuperate, qualche lavoro tattico saltato.']],
    en: ['Back from the trip', 'The team has just returned from the friendly abroad. The fitness coach fears jet lag.',
      ['Normal training', 'The trip brought the group together, no consequences.', 'Heavy legs and minds elsewhere: the team is tired.'],
      ['Two days of recovery only', 'Energy restored, some tactical work skipped.']],
  },
  {
    id: 'ch_investor_visit', cat: 'board', w: 3, repeat: 80,
    when: { mdMin: 5, mdMax: 24 },
    o: [
      { fx: { teamMorale: -2, reputation: 1 }, chain: { id: 'ch_investor_decision', in: 7 } },
      { fx: { teamMorale: 2, trust: -3 } },
    ],
    it: ['Un investitore al campo', 'Un fondo straniero valuta di entrare nel {club}. Il presidente vuole che tu faccia da guida durante la visita.',
      ['Faccio gli onori di casa', 'Mezza giornata tolta al lavoro, ma l’investitore resta colpito.'],
      ['Io alleno: se ne occupi la società', 'Il gruppo apprezza. Il presidente molto meno.']],
    en: ['An investor at training', 'A foreign fund is considering buying into {club}. The chairman wants you to host the visit.',
      ['Play host', 'Half a day lost to work, but the investor is impressed.'],
      ['I coach: the club can handle it', 'The squad appreciates it. The chairman much less.']],
  },
  {
    id: 'ch_investor_decision', cat: 'finance', w: 1, chainOnly: true,
    when: {},
    o: [
      { odds: { base: 0.35, rep: 0.006, trust: 0.006, good: { budgetPct: 0.35, budget: 2, trust: 5 }, bad: { trust: -2 } } },
    ],
    it: ['La decisione del fondo', 'Il fondo straniero ha preso la sua decisione sul {club}. Il presidente ti convoca.',
      ['Sentiamo', 'Il fondo entra: più soldi per il mercato e una società più ambiziosa.', 'Il fondo si ritira. Il presidente è di cattivo umore.']],
    en: ['The fund’s decision', 'The foreign fund has made its decision about {club}. The chairman calls you in.',
      ['Let’s hear it', 'The fund buys in: more money for transfers and a more ambitious club.', 'The fund pulls out. The chairman is in a foul mood.']],
  },
  {
    id: 'ch_striker_backing', cat: 'press', w: 4, repeat: 30,
    when: { mdMin: 4, player: { depts: ['ATT'], rankMax: 12, formMax: 1 } },
    o: [
      { fx: { morale: 8, bond: 8 }, chain: { id: 'ch_striker_backing_verdict', in: 3 } },
      { fx: { morale: -6, form: -1, teamMorale: 1 } },
    ],
    it: ['Il digiuno di {player}', 'In conferenza ti chiedono se {player}, che non segna da settimane, sia ancora l’uomo giusto.',
      ['“Segnerà nelle prossime tre partite”', '{player} ti ringrazia con lo sguardo. Ora però la frase è sui giornali.'],
      ['“Deve fare di più”', '{player} ci resta male. Il messaggio arriva a tutto il gruppo.']],
    en: ['{player}’s drought', 'At the press conference you’re asked whether {player}, who hasn’t scored for weeks, is still the right man.',
      ['“He’ll score in the next three matches”', '{player} thanks you with a look. But now the quote is in the papers.'],
      ['“He needs to do more”', '{player} is hurt. The message reaches the whole group.']],
  },
  {
    id: 'ch_striker_backing_verdict', cat: 'press', w: 1, chainOnly: true,
    when: { player: {} },
    o: [
      { odds: { base: 0.45, form: 0.03, morale: 0.004, good: { reputation: 2, morale: 6, attrs: { finishing: 1, composure: 1 } }, bad: { reputation: -2, morale: -8, trust: -2 } } },
    ],
    it: ['La profezia su {player}', 'Sono passate tre partite da quando hai garantito i gol di {player}. I giornalisti hanno tenuto il conto.',
      ['Vediamo chi aveva ragione', '{player} ti ha dato ragione: sblocco, fiducia e un attaccante rinato.', '{player} non ha segnato: la frase ti si ritorce contro e lui è a pezzi.']],
    en: ['The {player} prophecy', 'Three matches have passed since you guaranteed goals from {player}. The journalists kept count.',
      ['Let’s see who was right', '{player} proved you right: the drought is over and the striker is reborn.', '{player} didn’t score: the quote backfires and he is devastated.']],
  },
  {
    id: 'ch_keeper_rotation', cat: 'player', w: 3, repeat: 45,
    when: { mdMin: 6, player: { roles: ['POR'], starter: false, ovrMin: 55 } },
    o: [
      { fx: { morale: 10, bond: 8 }, promise: { type: 'starts', need: 2, within: 5 } },
      { fx: { morale: -8, bond: -4 } },
    ],
    it: ['Il secondo portiere', '{player} ti chiede spazio: si allena bene e vuole almeno qualche partita.',
      ['Gli prometto due partite nelle prossime cinque', '{player} è raggiante. Ora però va mantenuta.'],
      ['Il titolare non si tocca', '{player} accetta, ma è deluso.']],
    en: ['The second goalkeeper', '{player} asks for game time: he is training well and wants at least a few matches.',
      ['Promise him two of the next five matches', '{player} is beaming. Now you have to keep your word.'],
      ['The starter stays', '{player} accepts, but is disappointed.']],
  },
  {
    id: 'ch_physio_method', cat: 'staff', w: 3, repeat: 60,
    when: { injuredMin: 2 },
    o: [
      { fx: { budget: -0.5, staff: 3 }, chain: { id: 'ch_physio_method_result', in: 8 } },
      { fx: {} },
    ],
    it: ['Il nuovo metodo di prevenzione', 'Un preparatore propone un programma di prevenzione degli infortuni basato sui dati. Costa, e i risultati si vedono solo col tempo.',
      ['Lo adottiamo', 'Nuovi sensori e nuove routine: vedremo fra qualche settimana.'],
      ['Restiamo sul metodo attuale', 'Nessun cambiamento.']],
    en: ['The new prevention method', 'A fitness coach proposes a data-driven injury prevention programme. It’s expensive, and results only show over time.',
      ['Adopt it', 'New sensors and new routines: we’ll see in a few weeks.'],
      ['Stick with the current method', 'No changes.']],
  },
  {
    id: 'ch_physio_method_result', cat: 'staff', w: 1, chainOnly: true,
    when: {},
    o: [
      { odds: { base: 0.6, good: { teamFitness: 8, staff: 6, youngsters: { injuryProne: -6 }, senior: { injuryProne: -6 } }, bad: { staff: -3, teamMorale: -2 } } },
    ],
    it: ['I numeri della prevenzione', 'Il preparatore presenta i dati delle ultime otto settimane.',
      ['Mostrami i numeri', 'Meno affaticamenti e muscoli più resistenti: il programma funziona.', 'Nessun miglioramento: i giocatori si lamentano delle routine in più.']],
    en: ['The prevention figures', 'The fitness coach presents the data from the last eight weeks.',
      ['Show me the numbers', 'Less fatigue and tougher muscles: the programme works.', 'No improvement: the players complain about the extra routines.']],
  },
];
