/* I tifosi: la curva, lo stadio, la città. */

export default [
  {
    id: 'fn_ultras_meeting', cat: 'fans', w: 5, repeat: 20,
    when: { mdMin: 4, fansMax: 45 },
    o: [
      { odds: { base: 0.55, rep: 0.005, good: { fans: 10, teamMorale: 2 }, bad: { fans: -4, teamMorale: -4 } } },
      { fx: { fans: -5, trust: 3 } },
      { fx: { fans: 4, teamMorale: -3 } },
    ],
    it: ['La curva vuole parlare', 'I capi della curva chiedono un incontro con squadra e allenatore al centro sportivo, dopo i risultati deludenti.',
      ['Ci vado io, da solo', 'Parli chiaro e ti prendi le responsabilità: la curva apprezza.', 'L’incontro si scalda: volano parole grosse.'],
      ['Nessun incontro: il club non tratta con la curva', 'La società approva. La curva prepara la contestazione.'],
      ['Mando la squadra a parlare con loro', 'I tifosi apprezzano, ma alcuni giocatori tornano scossi.']],
    en: ['The ultras want to talk', 'The ultras’ leaders ask for a meeting with the team and manager at the training ground after poor results.',
      ['I go, alone', 'You speak plainly and take responsibility: the fans respect it.', 'The meeting gets heated: harsh words fly.'],
      ['No meeting: the club doesn’t deal with ultras', 'The board approves. The ultras plan a protest.'],
      ['Send the team to talk to them', 'The fans appreciate it, but some players come back shaken.']],
  },
  {
    id: 'fn_training_protest', cat: 'fans', w: 4, repeat: 25,
    when: { streakL: 2, fansMax: 50 },
    o: [
      { fx: { teamMorale: -4, fans: 3 } },
      { fx: { teamMorale: 2, fans: -4, budget: -0.1 } },
    ],
    it: ['Contestazione all’allenamento', 'Un gruppo di tifosi si presenta ai cancelli del centro sportivo con cori contro la squadra.',
      ['Allenamento aperto: ci mettiamo la faccia', 'I tifosi apprezzano il coraggio, ma i giocatori soffrono i fischi.'],
      ['Ci alleniamo in un campo lontano', 'La squadra lavora in pace. I tifosi si sentono snobbati.']],
    en: ['Protest at training', 'A group of fans turns up at the training ground gates chanting against the team.',
      ['Open training: we face them', 'The fans respect the courage, but the players suffer the jeers.'],
      ['Train at a pitch far away', 'The team works in peace. The fans feel snubbed.']],
  },
  {
    id: 'fn_kids_visit', cat: 'fans', w: 4, repeat: 40,
    when: {},
    o: [
      { fx: { fans: 5, teamMorale: 3, teamFitness: -2 } },
      { fx: {} },
    ],
    it: ['I bambini delle scuole calcio', 'Duecento bambini delle scuole calcio della città vogliono assistere a un allenamento e fare foto con i giocatori.',
      ['Venite pure', 'Una mattinata di sorrisi: la città parla bene della squadra.'],
      ['Magari a fine stagione', 'Rimandato.']],
    en: ['Kids from the football schools', 'Two hundred kids from the city’s football schools want to watch a training session and take photos with the players.',
      ['Come along', 'A morning of smiles: the city speaks well of the team.'],
      ['Maybe at the end of the season', 'Postponed.']],
  },
  {
    id: 'fn_away_heroes', cat: 'fans', w: 4, repeat: 30,
    when: { last: 'W', mdMin: 3 },
    o: [
      { fx: { fans: 6, teamFitness: -2 } },
      { fx: { fans: 1 } },
    ],
    it: ['Sotto il settore ospiti', 'Dopo la vittoria in trasferta i tifosi chiamano squadra e allenatore sotto il settore ospiti.',
      ['Tutti sotto la curva, maglie ai tifosi', 'Scena bellissima: i tifosi tornano a casa innamorati.'],
      ['Saluto veloce e negli spogliatoi', 'Un saluto educato.']],
    en: ['In front of the away end', 'After the away win the fans call team and manager over to the away end.',
      ['Everyone to the fans, shirts thrown in', 'A beautiful scene: the fans go home in love.'],
      ['A quick wave and into the tunnel', 'A polite wave.']],
  },
  {
    id: 'fn_chant_player', cat: 'fans', w: 4, repeat: 30,
    when: { player: { avgMax: 6.1, appsMin: 4, starter: true } },
    o: [
      { fx: { morale: 6, fans: -3 } },
      { fx: { morale: -8, fans: 2, form: -1 } },
      { odds: { base: 0.5, pers: { leader: 0.2, professionista: 0.1, fragile: -0.25 }, good: { morale: 6, form: 3, fans: 3 }, bad: { morale: -10, form: -3 } } },
    ],
    it: ['I fischi a {player}', 'Allo stadio fischiano {player} a ogni pallone toccato.',
      ['Chiedo ai tifosi di sostenerlo', '{player} si sente protetto. Qualche tifoso non gradisce la lezione.'],
      ['Lo tolgo dalla formazione per un po’', 'I tifosi approvano. {player} è a pezzi.'],
      ['Lo lascio in campo: deve reagire', '{player} risponde con una grande prestazione.', 'I fischi lo schiacciano.']],
    en: ['The jeers for {player}', 'At the stadium {player} is jeered every time he touches the ball.',
      ['Ask the fans to support him', '{player} feels protected. Some fans don’t like the lecture.'],
      ['Take him out of the team for a while', 'The fans approve. {player} is crushed.'],
      ['Keep him on: he has to react', '{player} answers with a great performance.', 'The jeers crush him.']],
  },
  {
    id: 'fn_fan_favourite', cat: 'fans', w: 4, repeat: 30,
    when: { player: { starter: false, ageMin: 27 } },
    o: [
      { fx: { fans: 5, promiseStarts: { need: 1, within: 4 }, morale: 8 } },
      { fx: { fans: -4 } },
    ],
    it: ['“Fate giocare {player}”', 'La curva ha preparato uno striscione per chiedere di far giocare {player}, idolo dei tifosi.',
      ['Lo farò giocare presto', 'La curva esulta. Ora una maglia da titolare va data.'],
      ['La formazione non la fanno gli striscioni', 'Coerenza, ma la curva ci resta male.']],
    en: ['“Play {player}”', 'The fans have made a banner asking for {player}, a fan favourite, to play.',
      ['I’ll play him soon', 'The fans cheer. Now a start has to come.'],
      ['Banners don’t pick the team', 'Consistent, but the fans are disappointed.']],
  },
  {
    id: 'fn_stadium_empty', cat: 'fans', w: 3, repeat: 40,
    when: { fansMax: 35 },
    o: [
      { fx: { fans: 7, teamMorale: 2, budget: -0.2 } },
      { fx: { fans: -2 } },
    ],
    it: ['Lo stadio si svuota', 'Nell’ultima partita in casa c’erano solo diecimila persone. Il club vuole una lettera ai tifosi firmata da te.',
      ['Scrivo una lettera sincera', 'Le parole toccano i tifosi: allo stadio si torna.'],
      ['Parlerà il campo', 'Lo stadio resta mezzo vuoto.']],
    en: ['An emptying stadium', 'At the last home game there were only ten thousand people. The club wants a letter to the fans signed by you.',
      ['Write a sincere letter', 'The words touch the fans: they come back to the stadium.'],
      ['The pitch will do the talking', 'The stadium stays half empty.']],
  },
  {
    id: 'fn_choreography', cat: 'fans', w: 4, repeat: 25,
    when: { derbyNext: true },
    o: [
      { fx: { fans: 4, nextMatch: { attack: 1.03, discipline: 1.1 } } },
      { fx: { nextMatch: { control: 1.01 } } },
    ],
    it: ['La coreografia del derby', 'La curva prepara una coreografia gigantesca per il derby e chiede ai giocatori di uscire dal tunnel insieme a te.',
      ['Usciamo tutti insieme davanti alla curva', 'Brividi: la squadra entra in campo trascinata.'],
      ['Riscaldamento normale, testa alla partita', 'Concentrazione, meno emozione.']],
    en: ['The derby choreography', 'The ultras prepare a giant display for the derby and ask the players to come out of the tunnel with you.',
      ['We all go out in front of the fans', 'Goosebumps: the team takes the field on a wave.'],
      ['A normal warm-up, heads on the game', 'Focus, less emotion.']],
  },
  {
    id: 'fn_crowdfunding', cat: 'fans', w: 2, repeat: 100,
    when: { level: 2 },
    o: [
      { fx: { fans: 8, budget: 1 } },
      { fx: { fans: -2 } },
    ],
    it: ['La raccolta fondi', 'I tifosi organizzano una raccolta fondi per aiutare il club a comprare un rinforzo.',
      ['Accettiamo con gratitudine', 'Arrivano soldi e un legame speciale con la città.'],
      ['Il club non può accettare', 'I tifosi non capiscono il rifiuto.']],
    en: ['The fundraiser', 'The fans organise a fundraiser to help the club buy a new signing.',
      ['Accept with gratitude', 'Money comes in, and a special bond with the city.'],
      ['The club can’t accept', 'The fans don’t understand the refusal.']],
  },
  {
    id: 'fn_supporter_vote', cat: 'fans', w: 3, repeat: 60,
    when: {},
    o: [
      { fx: { fans: 5, teamMorale: -1 } },
      { fx: {} },
    ],
    it: ['Il voto dei tifosi', 'Il club propone che i tifosi votino il giocatore del mese sull’app ufficiale, con premio in campo.',
      ['Ottima idea', 'I tifosi partecipano in massa. Qualcuno nello spogliatoio conta i voti.'],
      ['Meglio evitare classifiche interne', 'Nessuna iniziativa.']],
    en: ['The fans’ vote', 'The club proposes letting fans vote for player of the month on the official app, with an award on the pitch.',
      ['Great idea', 'The fans take part in droves. Some in the dressing room count the votes.'],
      ['Better avoid internal rankings', 'No initiative.']],
  },
  {
    id: 'fn_banner_coach', cat: 'fans', w: 4, repeat: 30,
    when: { fansMin: 70 },
    o: [
      { fx: { reputation: 2, teamMorale: 2 } },
      { fx: { fans: 2 } },
    ],
    it: ['Lo striscione per te', 'Allo stadio compare uno striscione con il tuo nome: “Un allenatore, un condottiero”.',
      ['Vado a salutare la curva', 'Momento emozionante: il tuo nome gira ovunque.'],
      ['Ringrazio, ma il merito è dei giocatori', 'I giocatori apprezzano.']],
    en: ['A banner for you', 'A banner appears at the stadium with your name: “A manager, a leader”.',
      ['Go and salute the fans', 'An emotional moment: your name spreads everywhere.'],
      ['Thank them, but the credit goes to the players', 'The players appreciate it.']],
  },
  {
    id: 'fn_car_attack', cat: 'fans', w: 2, repeat: 100,
    when: { streakL: 3, player: { rankMax: 10 } },
    o: [
      { fx: { morale: 6, bond: 10, teamMorale: 4, fans: -2 } },
      { fx: { morale: -8, trust: 2 } },
    ],
    it: ['L’auto di {player}', 'Dopo tre sconfitte, qualche teppista ha danneggiato l’auto di {player} davanti a casa sua.',
      ['Mi schiero pubblicamente con lui', 'Squadra compatta intorno al compagno.'],
      ['Lascio parlare la società', 'Silenzio prudente, ma {player} si sente solo.']],
    en: ['{player}’s car', 'After three defeats, some thugs damaged {player}’s car outside his home.',
      ['Stand with him publicly', 'The team rallies around its teammate.'],
      ['Let the club speak', 'A cautious silence, but {player} feels alone.']],
  },
  {
    id: 'fn_legend_return', cat: 'fans', w: 2, repeat: 100,
    when: {},
    o: [
      { fx: { fans: 6, teamMorale: 3 } },
      { fx: {} },
    ],
    it: ['La leggenda allo stadio', 'Un ex capitano storico torna allo stadio per una celebrazione. Vuole parlare alla squadra prima della partita.',
      ['Sì, parli alla squadra', 'Le sue parole restano nella testa dei giocatori.'],
      ['Solo una foto nel prepartita', 'Celebrazione sobria.']],
    en: ['The legend at the stadium', 'A legendary former captain returns for a celebration. He wants to address the team before the match.',
      ['Yes, let him speak to the team', 'His words stay in the players’ heads.'],
      ['Just a photo before the game', 'A low-key celebration.']],
  },
  {
    id: 'fn_ticket_scandal', cat: 'fans', w: 2, repeat: 100,
    when: { player: {} },
    o: [
      { fx: { suspended: 1, fans: 3, morale: -8 } },
      { fx: { fans: -5, morale: 2 } },
    ],
    it: ['I biglietti rivenduti', 'Si scopre che {player} rivendeva a prezzo gonfiato i biglietti omaggio della società.',
      ['Squalifica interna e scuse ai tifosi', 'I tifosi apprezzano la fermezza.'],
      ['Chiudo la questione in privato', 'La vicenda esce comunque sui giornali.']],
    en: ['The resold tickets', 'It emerges that {player} was reselling the club’s complimentary tickets at inflated prices.',
      ['Internal ban and apology to fans', 'The fans appreciate the firmness.'],
      ['Close it privately', 'The story reaches the papers anyway.']],
  },
  {
    id: 'fn_rain_match', cat: 'fans', w: 3, repeat: 40,
    when: { mdMin: 8 },
    o: [
      { fx: { fans: 4, teamFitness: -3 } },
      { fx: {} },
    ],
    it: ['I tifosi sotto la pioggia', 'Nella partita sotto il diluvio i tifosi non hanno mai smesso di cantare. Vorrebbero un gesto.',
      ['Doppio giro di campo sotto la pioggia', 'I tifosi apprezzano: legame più forte.'],
      ['Un ringraziamento sui social', 'Un gesto piccolo.']],
    en: ['Fans in the rain', 'In the match played in a downpour the fans never stopped singing. They’d like a gesture.',
      ['A double lap of honour in the rain', 'The fans love it: a stronger bond.'],
      ['A thank-you on social media', 'A small gesture.']],
  },
  {
    id: 'fn_rival_fans_provocation', cat: 'rival', w: 3, repeat: 30,
    when: { derbyNext: true },
    o: [
      { fx: { fans: 3, nextMatch: { discipline: 1.25, attack: 1.03 } } },
      { fx: { nextMatch: { control: 1.02 }, reputation: 1 } },
    ],
    it: ['La provocazione dei rivali', 'I tifosi avversari hanno appeso sotto il vostro centro sportivo uno striscione di scherno.',
      ['Lo faccio vedere alla squadra', 'La squadra è furiosa: carica ma nervosa.'],
      ['Faccio togliere lo striscione in silenzio', 'Nessuna distrazione.']],
    en: ['The rivals’ provocation', 'Rival fans hung a mocking banner outside your training ground.',
      ['Show it to the team', 'The team is furious: fired up but edgy.'],
      ['Have it quietly removed', 'No distraction.']],
  },
  {
    id: 'fn_fans_kit_design', cat: 'fans', w: 2, repeat: 120,
    when: { mdMax: 5 },
    o: [
      { fx: { fans: 5, budget: 0.4 } },
      { fx: {} },
    ],
    it: ['La maglia disegnata dai tifosi', 'Il club propone un concorso: la terza maglia la disegneranno i tifosi.',
      ['Mi piace', 'Migliaia di disegni: i tifosi si sentono parte del club.'],
      ['Lasciamo fare ai professionisti', 'Nessun concorso.']],
    en: ['A kit designed by fans', 'The club proposes a contest: the fans will design the third kit.',
      ['I like it', 'Thousands of designs: the fans feel part of the club.'],
      ['Leave it to professionals', 'No contest.']],
  },
  {
    id: 'fn_hospital_visit', cat: 'fans', w: 3, repeat: 60,
    when: {},
    o: [
      { fx: { fans: 4, teamMorale: 4, teamFitness: -1 } },
      { fx: { fans: 1 } },
    ],
    it: ['La visita in ospedale', 'Un tifoso bambino, ricoverato, sogna di conoscere la squadra.',
      ['Andiamo tutti a trovarlo', 'Una giornata che nessuno dimenticherà.'],
      ['Mando una maglia firmata', 'Un bel gesto a distanza.']],
    en: ['The hospital visit', 'A young fan in hospital dreams of meeting the team.',
      ['We all go to visit him', 'A day nobody will forget.'],
      ['Send a signed shirt', 'A nice gesture from afar.']],
  },
  {
    id: 'fn_supporters_trust_style', cat: 'fans', w: 3, repeat: 40,
    when: { mdMin: 5, styles: ['catenaccio', 'pullman'] },
    o: [
      { fx: { fans: 5, familiarity: -8 } },
      { fx: { fans: -5 } },
    ],
    it: ['“Calcio noioso”', 'L’associazione dei tifosi scrive una lettera aperta: la squadra gioca un calcio troppo difensivo.',
      ['Prometto più coraggio', 'I tifosi apprezzano, la squadra deve adattarsi.'],
      ['Contano i risultati', 'Coerenza, ma lo stadio mormora.']],
    en: ['“Boring football”', 'The supporters’ association writes an open letter: the team plays too defensively.',
      ['Promise more courage', 'The fans appreciate it; the team must adapt.'],
      ['Results are what matter', 'Consistent, but the stadium murmurs.']],
  },
  {
    id: 'fn_pitch_invader_hug', cat: 'fans', w: 2, repeat: 100,
    when: { player: { rankMax: 3 } },
    o: [
      { fx: { fans: 4, morale: 4 } },
      { fx: { reputation: 1 } },
    ],
    it: ['Il tifoso in campo', 'Un ragazzino è entrato in campo per abbracciare {player}. Gli steward lo hanno trascinato via in malo modo.',
      ['Invitiamo il ragazzo al centro sportivo', 'Il gesto commuove la città.'],
      ['Le regole di sicurezza vanno rispettate', 'Posizione rigorosa.']],
    en: ['The pitch invader', 'A young boy ran onto the pitch to hug {player}. The stewards dragged him off roughly.',
      ['Invite the boy to the training ground', 'The gesture moves the city.'],
      ['Safety rules must be respected', 'A strict stance.']],
  },
  {
    id: 'fn_debt_protest', cat: 'fans', w: 2, repeat: 100,
    when: { budgetMax: 3 },
    o: [
      { fx: { fans: 4, trust: -3 } },
      { fx: { trust: 2, fans: -2 } },
    ],
    it: ['Tifosi contro i conti', 'I tifosi protestano: il club non investe. Ti chiedono se la rosa sia all’altezza.',
      ['“Servono rinforzi, è evidente”', 'I tifosi ti danno ragione. La società no.'],
      ['“Lavoro con quello che ho”', 'La società apprezza la lealtà.']],
    en: ['Fans against the finances', 'The fans protest: the club isn’t investing. They ask if the squad is good enough.',
      ['“We clearly need reinforcements”', 'The fans agree with you. The board doesn’t.'],
      ['“I work with what I have”', 'The board appreciates the loyalty.']],
  },
  {
    id: 'fn_anniversary', cat: 'fans', w: 2, repeat: 150,
    when: {},
    o: [
      { fx: { fans: 6, teamMorale: 2, nextMatch: { attack: 1.02 } } },
      { fx: { fans: 1 } },
    ],
    it: ['L’anniversario del club', 'Il club compie gli anni: per la partita di casa si gioca con una maglia storica.',
      ['Grande festa allo stadio', 'Atmosfera magica: la squadra si sente parte della storia.'],
      ['Una celebrazione sobria', 'Festeggiamento discreto.']],
    en: ['The club anniversary', 'It’s the club’s anniversary: for the home match the team wears a historic kit.',
      ['A big party at the stadium', 'A magical atmosphere: the team feels part of history.'],
      ['A modest celebration', 'A low-key celebration.']],
  },
  {
    id: 'fn_signing_request', cat: 'fans', w: 3, repeat: 40,
    when: { window: true },
    o: [
      { fx: { fans: 5, trust: -2, budgetPct: -0.1 } },
      { fx: { fans: -3 } },
    ],
    it: ['“Vogliamo un nome”', 'I tifosi chiedono un acquisto di grido. Sui social impazza l’hashtag contro la società.',
      ['Chiedo alla società uno sforzo', 'I tifosi ti sentono dalla loro parte; parte del budget va in un’operazione d’immagine.'],
      ['Il mercato non si fa con gli hashtag', 'Posizione ferma, tifosi delusi.']],
    en: ['“We want a big name”', 'The fans demand a marquee signing. A hashtag against the club trends online.',
      ['Ask the club for an effort', 'The fans feel you’re with them; part of the budget goes on a showpiece deal.'],
      ['Transfers aren’t made by hashtags', 'A firm stance, disappointed fans.']],
  },
  {
    id: 'fn_minute_silence', cat: 'fans', w: 2, repeat: 120,
    when: {},
    o: [
      { fx: { fans: 4, teamMorale: 3 } },
      { fx: {} },
    ],
    it: ['Un lutto in città', 'È scomparso uno storico magazziniere del club. I tifosi chiedono un ricordo speciale.',
      ['Lutto al braccio e minuto di silenzio', 'Un momento che unisce squadra e città.'],
      ['Un comunicato del club', 'Un ricordo discreto.']],
    en: ['Mourning in the city', 'A long-time club kit man has passed away. The fans ask for a special tribute.',
      ['Black armbands and a minute’s silence', 'A moment that unites team and city.'],
      ['A club statement', 'A quiet tribute.']],
  },
  {
    id: 'fn_scarf_ban', cat: 'fans', w: 2, repeat: 80,
    when: {},
    o: [
      { fx: { fans: 4, trust: -2 } },
      { fx: { trust: 2, fans: -3 } },
    ],
    it: ['Divieti allo stadio', 'La questura vieta bandiere e tamburi per ragioni di sicurezza. I tifosi minacciano lo sciopero del tifo.',
      ['Mi schiero con i tifosi', 'La curva ti ringrazia.'],
      ['Chiedo rispetto delle regole', 'Posizione istituzionale.']],
    en: ['Stadium bans', 'The police ban flags and drums for safety reasons. The fans threaten to stay silent.',
      ['Side with the fans', 'The ultras thank you.'],
      ['Ask for rules to be respected', 'An institutional stance.']],
  },
  {
    id: 'fn_fan_trains', cat: 'fans', w: 2, repeat: 100,
    when: {},
    o: [
      { fx: { fans: 5, teamMorale: 2 } },
      { fx: {} },
    ],
    it: ['Un tifoso in allenamento', 'Un tifoso ha vinto un concorso: allenarsi un giorno con la squadra.',
      ['Lo facciamo giocare anche nella partitella', 'Il tifoso segna un gol tra le risate di tutti: video virale.'],
      ['Solo il riscaldamento', 'Esperienza più tranquilla.']],
    en: ['A fan at training', 'A fan won a contest: to train with the team for a day.',
      ['Let him play in the practice match too', 'The fan scores amid everyone’s laughter: a viral video.'],
      ['Warm-up only', 'A calmer experience.']],
  },
  {
    id: 'fn_old_rival_fans', cat: 'fans', w: 3, repeat: 40,
    when: { last: 'W', derbyNext: false },
    o: [
      { fx: { fans: 3, reputation: -1 } },
      { fx: { reputation: 1 } },
    ],
    it: ['La battuta sui rivali', 'Durante la festa per la vittoria, ti passano un microfono davanti ai tifosi. Vogliono una battuta sui rivali di sempre.',
      ['La dico', 'La curva impazzisce. I rivali se la segnano.'],
      ['Ringrazio e basta', 'Stile.']],
    en: ['The joke about the rivals', 'At the victory celebration you’re handed a microphone in front of the fans. They want a joke about the old rivals.',
      ['Tell it', 'The fans go wild. The rivals take note.'],
      ['Just say thank you', 'Class.']],
  },
  {
    id: 'fn_player_fan_club', cat: 'fans', w: 2, repeat: 100,
    when: { player: { ageMax: 24, avgMin: 6.6 } },
    o: [
      { fx: { morale: 6, fans: 3, fitness: -4 } },
      { fx: { morale: -2 } },
    ],
    it: ['Il fan club di {player}', 'È nato un fan club dedicato a {player}. Lo invitano alla festa di inaugurazione.',
      ['Vai pure', '{player} è felicissimo e i tifosi lo adorano.'],
      ['Meglio dopo la partita', '{player} rinvia, un po’ deluso.']],
    en: ['{player}’s fan club', 'A fan club dedicated to {player} has been founded. They invite him to the launch party.',
      ['Go ahead', '{player} is thrilled and the fans adore him.'],
      ['Better after the match', '{player} postpones, a little disappointed.']],
  },
  {
    id: 'fn_empty_stadium_penalty', cat: 'fans', w: 2, repeat: 100,
    when: { mdMin: 5 },
    o: [
      { fx: { fans: 3, budget: -0.3, nextMatch: { control: 0.98 } } },
      { fx: { fans: -4 } },
    ],
    it: ['Porte chiuse', 'Per un coro discriminatorio di pochi, il giudice sportivo ha disposto una partita a porte chiuse. Il club può fare ricorso.',
      ['Ricorso: non puniamo tutti per pochi', 'Il ricorso fallisce e costa, ma i tifosi apprezzano la battaglia.'],
      ['Accettiamo e condanniamo il coro', 'Posizione giusta, ma la curva si sente punita.']],
    en: ['Behind closed doors', 'Because of discriminatory chants by a few, the judge has ordered a match behind closed doors. The club can appeal.',
      ['Appeal: don’t punish everyone for a few', 'The appeal fails and costs money, but the fans appreciate the fight.'],
      ['Accept and condemn the chants', 'The right stance, but the ultras feel punished.']],
  },
  {
    id: 'fn_supporters_awards', cat: 'fans', w: 2, repeat: 100,
    when: { mdMin: 30 },
    o: [
      { fx: { fans: 4, teamMorale: 2 } },
      { fx: {} },
    ],
    it: ['La cena dei club di tifosi', 'I club di tifosi organizzano la cena di fine stagione e ti invitano insieme alla squadra.',
      ['Ci andiamo tutti', 'Serata calorosa: tifosi e squadra si abbracciano.'],
      ['Va una delegazione', 'Presenza minima.']],
    en: ['The supporters’ clubs dinner', 'The supporters’ clubs host their end-of-season dinner and invite you with the team.',
      ['We all go', 'A warm evening: fans and team embrace.'],
      ['Send a delegation', 'A token presence.']],
  },
];
