/* Staff medico e condizione fisica: infortuni, recuperi, rischi. */

export default [
  {
    id: 'md_flu', cat: 'medical', w: 4, repeat: 30,
    when: { mdMin: 10, mdMax: 26 },
    o: [
      { fx: { teamFitness: -10, nextMatch: { tempo: 0.95 } } },
      { fx: { budget: -0.3, teamFitness: -4 } },
    ],
    it: ['L’influenza nello spogliatoio', 'Un virus influenzale gira nello spogliatoio: sei giocatori con la febbre a pochi giorni dalla partita.',
      ['Si stringono i denti', 'Si gioca con qualche giocatore debilitato.'],
      ['Isolamento e medico a domicilio', 'Il contagio si ferma prima.']],
    en: ['Flu in the dressing room', 'A flu virus is going round: six players with a fever a few days before the match.',
      ['Grit our teeth', 'Some weakened players will have to play.'],
      ['Isolation and home visits', 'The spread stops earlier.']],
  },
  {
    id: 'md_surgery_choice', cat: 'medical', w: 5, repeat: 30,
    when: { player: { injured: true, rankMax: 8 } },
    o: [
      { fx: { injury: 6, injuryProne: -15, attrs: { pace: 1 } } },
      { odds: { base: 0.55, pers: { professionista: 0.15, fragile: -0.2 }, good: { injury: -2 }, bad: { injury: 5, injuryProne: 12, attrs: { pace: -3 } } } },
    ],
    it: ['Operare {player}?', 'Il chirurgo propone di operare {player}: stop più lungo, ma problema risolto per sempre. In alternativa, terapia conservativa.',
      ['Operazione', '{player} starà fuori di più, ma tornerà come nuovo.'],
      ['Terapia conservativa', 'La terapia funziona: {player} torna presto.', 'La terapia non basta: ricaduta, e il problema resta.']],
    en: ['Surgery for {player}?', 'The surgeon proposes operating on {player}: a longer lay-off, but the problem solved for good. Or conservative treatment.',
      ['Surgery', '{player} will be out longer, but return as good as new.'],
      ['Conservative treatment', 'The treatment works: {player} is back soon.', 'The treatment isn’t enough: a relapse, and the problem remains.']],
  },
  {
    id: 'md_gps_warning', cat: 'medical', w: 5, repeat: 15,
    when: { player: { fitnessMax: 70, starter: true, rankMax: 8 } },
    o: [
      { fx: { fitness: 20, form: -1 } },
      { odds: { base: 0.55, age: -0.02, good: { form: 1 }, bad: { injury: 3, injuryProne: 8 } } },
    ],
    it: ['Il semaforo rosso dei dati', 'I dati GPS dicono che {player} è in zona rossa: rischio infortunio muscolare altissimo.',
      ['Riposo per una partita', '{player} recupera: meglio un turno fuori che un mese.'],
      ['Gioca: mi serve', 'Regge e gioca bene.', 'Il muscolo cede: stiramento.']],
    en: ['The data’s red light', 'The GPS data say {player} is in the red zone: a very high risk of muscle injury.',
      ['Rest for one match', '{player} recovers: better one match out than a month.'],
      ['He plays: I need him', 'He holds up and plays well.', 'The muscle gives way: a strain.']],
  },
  {
    id: 'md_second_opinion', cat: 'medical', w: 3, repeat: 40,
    when: { player: { injured: true } },
    o: [
      { odds: { base: 0.5, good: { injury: -2 }, bad: {} }, fx: { budget: -0.1 } },
      { fx: {} },
    ],
    it: ['Un secondo parere', 'Il procuratore di {player} chiede un secondo parere medico all’estero: non si fida della diagnosi del club.',
      ['Accetto: serenità prima di tutto', 'Il secondo medico accorcia i tempi di recupero.', 'Il secondo parere conferma il primo: tempo e soldi persi.'],
      ['Mi fido del nostro staff', 'Lo staff apprezza. Il procuratore meno.']],
    en: ['A second opinion', '{player}’s agent asks for a second medical opinion abroad: he doesn’t trust the club’s diagnosis.',
      ['Agree: peace of mind first', 'The second doctor shortens the recovery time.', 'The second opinion confirms the first: time and money lost.'],
      ['I trust our staff', 'The staff appreciate it. The agent less so.']],
  },
  {
    id: 'md_heat_wave', cat: 'medical', w: 3, repeat: 30,
    when: { mdMax: 4 },
    o: [
      { fx: { teamFitness: 5, familiarity: -2 } },
      { fx: { teamFitness: -8, familiarity: 3 } },
    ],
    it: ['Il caldo', 'Quaranta gradi: lo staff propone di spostare gli allenamenti all’alba e alla sera.',
      ['Allenamenti all’alba', 'La squadra soffre meno il caldo.'],
      ['Orari normali: ci si abitua', 'Allenamenti pesanti, gambe svuotate.']],
    en: ['The heat', 'Forty degrees: the staff suggest moving training to dawn and evening.',
      ['Train at dawn', 'The team suffers less from the heat.'],
      ['Normal hours: they’ll get used to it', 'Heavy sessions, drained legs.']],
  },
  {
    id: 'md_sleep_specialist', cat: 'medical', w: 3, repeat: 80,
    when: {},
    o: [
      { fx: { budget: -0.3, teamFitness: 4, teamForm: 1 } },
      { fx: {} },
    ],
    it: ['L’esperto del sonno', 'Uno specialista del sonno propone un programma per la squadra: orari, stanze buie, niente schermi la sera.',
      ['Lo proviamo', 'I giocatori dormono meglio e recuperano di più.'],
      ['Non ne abbiamo bisogno', 'Nessun programma.']],
    en: ['The sleep expert', 'A sleep specialist proposes a programme for the team: routines, dark rooms, no screens at night.',
      ['Try it', 'The players sleep better and recover more.'],
      ['We don’t need it', 'No programme.']],
  },
  {
    id: 'md_rushed_return', cat: 'medical', w: 5, repeat: 20,
    when: { player: { injured: true, rankMax: 5 } },
    o: [
      { odds: { base: 0.5, pers: { professionista: 0.1, fragile: -0.2 }, good: { injury: -9, bond: 5 }, bad: { injury: 4, injuryProne: 10 } } },
      { fx: { morale: -4 } },
    ],
    it: ['Accelerare il rientro di {player}?', '{player} vuole tornare subito: dice di sentirsi bene. Lo staff medico consiglia prudenza.',
      ['Lo porto in panchina già dalla prossima', '{player} rientra e sta bene.', 'Ricaduta: si ricomincia da capo.'],
      ['Si rispettano i tempi', '{player} scalpita, ma tornerà al cento per cento.']],
    en: ['Rush {player} back?', '{player} wants to return right away: he says he feels fine. The medical staff advise caution.',
      ['Put him on the bench next match', '{player} returns and is fine.', 'A relapse: back to square one.'],
      ['Respect the timeline', '{player} is restless, but he’ll return at a hundred per cent.']],
  },
  {
    id: 'md_painkillers', cat: 'medical', w: 3, repeat: 40,
    when: { player: { ageMin: 29, rankMax: 10, fitnessMax: 85 } },
    o: [
      { fx: { form: 2, injuryProne: 10, fitness: 6 } },
      { fx: { fitness: 10, form: -1 } },
    ],
    it: ['Antidolorifici', '{player} convive con un dolore cronico e chiede antidolorifici prima di ogni partita.',
      ['Va bene, sotto controllo medico', '{player} gioca meglio, ma il fisico si logora.'],
      ['Meglio fermarsi e curarsi', '{player} salta qualche allenamento e sta meglio.']],
    en: ['Painkillers', '{player} lives with chronic pain and asks for painkillers before every match.',
      ['Fine, under medical supervision', '{player} plays better, but his body wears down.'],
      ['Better stop and treat it', '{player} misses a few sessions and feels better.']],
  },
  {
    id: 'md_bad_pitch_injuries', cat: 'medical', w: 3, repeat: 40,
    when: { injuredMin: 2 },
    o: [
      { fx: { budget: -0.5, teamFitness: 3 } },
      { fx: { teamFitness: -3 } },
    ],
    it: ['Il campo di allenamento', 'Lo staff medico sospetta che il campo di allenamento rovinato stia causando infortuni.',
      ['Rifacciamo il campo subito', 'Spesa necessaria: meno acciacchi.'],
      ['Aspettiamo fine stagione', 'Il campo resta com’è.']],
    en: ['The training pitch', 'The medical staff suspect the worn training pitch is causing injuries.',
      ['Relay the pitch now', 'A necessary expense: fewer knocks.'],
      ['Wait until the end of the season', 'The pitch stays as it is.']],
  },
  {
    id: 'md_concussion', cat: 'medical', w: 3, repeat: 40,
    when: { player: { depts: ['DIF', 'ATT'], starter: true } },
    o: [
      { fx: { injury: 1, bond: 5 } },
      { odds: { base: 0.7, good: {}, bad: { injury: 4, attrs: { composure: -2 }, trust: -3 } } },
    ],
    it: ['Il colpo alla testa', 'In allenamento {player} ha preso una botta alla testa. Dice di stare bene, ma il protocollo prevede riposo.',
      ['Protocollo rispettato: stop', '{player} salta una partita per sicurezza.'],
      ['Se sta bene, gioca', 'Nessuna conseguenza.', 'I sintomi tornano in partita: stop più lungo e polemiche.']],
    en: ['The blow to the head', 'In training {player} took a knock to the head. He says he’s fine, but protocol requires rest.',
      ['Follow the protocol: stop', '{player} misses one match to be safe.'],
      ['If he’s fine, he plays', 'No consequences.', 'The symptoms return during the match: a longer lay-off and controversy.']],
  },
  {
    id: 'md_new_physio_method', cat: 'medical', w: 3, repeat: 60,
    when: { injuredMin: 1 },
    o: [
      { odds: { base: 0.55, good: { teamFitness: 5, staff: 3 }, bad: { teamFitness: -3, budget: -0.2 } } },
      { fx: {} },
    ],
    it: ['Un metodo di recupero nuovo', 'Un fisioterapista propone un metodo sperimentale di recupero muscolare.',
      ['Lo proviamo', 'Funziona: i giocatori recuperano prima.', 'Non funziona e fa perdere tempo.'],
      ['Metodi collaudati', 'Nessun cambio.']],
    en: ['A new recovery method', 'A physio proposes an experimental muscle recovery method.',
      ['Try it', 'It works: the players recover faster.', 'It doesn’t work and wastes time.'],
      ['Proven methods', 'No change.']],
  },
  {
    id: 'md_ankle_brace', cat: 'medical', w: 3, repeat: 40,
    when: { player: { injuryProneMin: 55, rankMax: 12 } },
    o: [
      { fx: { injuryProne: -12, attrs: { dribbling: -1 } } },
      { fx: {} },
    ],
    it: ['La cavigliera', 'Lo staff vuole che {player} giochi con una cavigliera rigida dopo le distorsioni passate. Lui dice che gli toglie sensibilità.',
      ['Obbligatoria', 'Meno rischi, un po’ meno agilità.'],
      ['Decide lui', 'Nessun cambiamento.']],
    en: ['The ankle brace', 'The staff want {player} to play with a rigid ankle brace after past sprains. He says it takes away his feel.',
      ['Mandatory', 'Less risk, a little less agility.'],
      ['His call', 'No change.']],
  },
  {
    id: 'md_travel_fatigue', cat: 'medical', w: 3, repeat: 30,
    when: { mdMin: 3 },
    o: [
      { fx: { teamFitness: 6, familiarity: -2 } },
      { fx: { familiarity: 3, teamFitness: -4 } },
    ],
    it: ['Stanchezza accumulata', 'I test mostrano stanchezza generale. Il preparatore propone una settimana di scarico.',
      ['Settimana di scarico', 'La squadra si rigenera.'],
      ['Si lavora sulla tattica', 'Più intesa, meno energie.']],
    en: ['Accumulated fatigue', 'Tests show general fatigue. The fitness coach proposes a recovery week.',
      ['Recovery week', 'The team regenerates.'],
      ['Work on tactics', 'Better understanding, less energy.']],
  },
  {
    id: 'md_old_injury_flare', cat: 'medical', w: 4, repeat: 30,
    when: { player: { ageMin: 30, starter: true } },
    o: [
      { fx: { injury: 2 } },
      { odds: { base: 0.5, good: { fitness: -5 }, bad: { injury: 5 } } },
    ],
    it: ['Il vecchio infortunio', 'A {player} si è rifatto sentire un vecchio problema al ginocchio.',
      ['Due partite di stop precauzionale', 'Riposo e il ginocchio si calma.'],
      ['Gioca e monitoriamo', 'Il ginocchio regge.', 'Il ginocchio cede: stop lungo.']],
    en: ['The old injury', 'An old knee problem has flared up for {player}.',
      ['Two matches out as a precaution', 'Rest, and the knee settles.'],
      ['He plays and we monitor', 'The knee holds up.', 'The knee gives way: a long lay-off.']],
  },
  {
    id: 'md_doping_test', cat: 'medical', w: 2, repeat: 100,
    when: { player: {} },
    o: [
      { fx: { reputation: 1, morale: 4 } },
      { fx: { morale: -4 } },
    ],
    it: ['Il controllo a sorpresa', 'Controllo antidoping a sorpresa al centro sportivo alle sei del mattino: tocca a {player}, che era stato male la notte.',
      ['Accompagno io {player}', '{player} apprezza la vicinanza. Tutto regolare.'],
      ['Se ne occupa lo staff', 'Tutto regolare, ma {player} si sente solo.']],
    en: ['The surprise test', 'A surprise doping control at the training ground at six in the morning: it’s {player}’s turn, and he was ill during the night.',
      ['I go with {player}', '{player} appreciates the support. All clear.'],
      ['The staff handle it', 'All clear, but {player} feels alone.']],
  },
  {
    id: 'md_food_poisoning', cat: 'medical', w: 2, repeat: 80,
    when: { mdMin: 2 },
    o: [
      { fx: { teamFitness: -8, nextMatch: { tempo: 0.94 } } },
      { fx: { budget: -0.2, teamFitness: -3 } },
    ],
    it: ['L’intossicazione', 'Dopo la cena in albergo in trasferta molti giocatori stanno male.',
      ['Si gioca lo stesso', 'Squadra debilitata in campo.'],
      ['Medico, flebo e riposo fino all’ultimo', 'La squadra si riprende un po’.']],
    en: ['Food poisoning', 'After dinner at the away hotel many players are ill.',
      ['We play anyway', 'A weakened team takes the field.'],
      ['Doctor, drips and rest until the last minute', 'The team partly recovers.']],
  },
  {
    id: 'md_mental_fatigue', cat: 'medical', w: 3, repeat: 40,
    when: { player: { moraleMax: 40, starter: true } },
    o: [
      { fx: { morale: 15, fitness: 10, form: -2 } },
      { fx: { morale: -5 } },
    ],
    it: ['Stanchezza mentale', 'Lo psicologo dello staff segnala che {player} è mentalmente esausto.',
      ['Tre giorni lontano dal calcio', '{player} torna sereno.'],
      ['Il lavoro è la miglior cura', '{player} peggiora.']],
    en: ['Mental fatigue', 'The staff psychologist reports that {player} is mentally exhausted.',
      ['Three days away from football', '{player} returns at peace.'],
      ['Work is the best cure', '{player} gets worse.']],
  },
  {
    id: 'md_blood_tests', cat: 'medical', w: 3, repeat: 60,
    when: {},
    o: [
      { fx: { budget: -0.2, teamFitness: 3, staff: 2 } },
      { fx: {} },
    ],
    it: ['Esami del sangue', 'Lo staff propone esami del sangue mensili per calibrare alimentazione e integrazione di ogni giocatore.',
      ['Sì, individualizziamo tutto', 'Piani su misura: la squadra ne beneficia.'],
      ['Troppo costoso', 'Nessun cambiamento.']],
    en: ['Blood tests', 'The staff propose monthly blood tests to tailor each player’s diet and supplements.',
      ['Yes, individualise everything', 'Tailored plans: the team benefits.'],
      ['Too expensive', 'No change.']],
  },
  {
    id: 'md_hamstring_epidemic', cat: 'medical', w: 3, repeat: 40,
    when: { injuredMin: 3, styles: ['gegenpressing', 'totale', 'quinti'] },
    o: [
      { fx: { familiarity: -6, teamFitness: 8 } },
      { fx: { teamFitness: -4 } },
    ],
    it: ['Troppi muscoli rotti', 'Lo staff medico collega gli infortuni muscolari al tuo stile di gioco dispendioso.',
      ['Abbasso i ritmi per qualche settimana', 'Meno infortuni, ma il gioco perde intensità.'],
      ['Il calcio moderno è questo', 'Nessuna modifica: i muscoli continuano a soffrire.']],
    en: ['Too many torn muscles', 'The medical staff link the muscle injuries to your demanding style of play.',
      ['Lower the intensity for a few weeks', 'Fewer injuries, but the play loses intensity.'],
      ['This is modern football', 'No change: muscles keep suffering.']],
  },
  {
    id: 'md_young_growth', cat: 'medical', w: 3, repeat: 60,
    when: { player: { ageMax: 19 } },
    o: [
      { fx: { fitness: -10, injuryProne: -10, potential: 1 } },
      { fx: { injuryProne: 6 } },
    ],
    it: ['La crescita di {player}', '{player} è cresciuto di sette centimetri in un anno: lo staff vuole ridurre i carichi per proteggere le articolazioni.',
      ['Carichi ridotti', '{player} si allena meno, ma cresce sano.'],
      ['Carichi normali', '{player} si allena con tutti, con qualche rischio.']],
    en: ['{player}’s growth spurt', '{player} has grown seven centimetres in a year: the staff want to reduce his loads to protect his joints.',
      ['Reduced loads', '{player} trains less, but grows up healthy.'],
      ['Normal loads', '{player} trains with everyone, with some risk.']],
  },
  {
    id: 'md_keeper_finger', cat: 'medical', w: 3, repeat: 40,
    when: { player: { roles: ['POR'], starter: true } },
    o: [
      { fx: { injury: 2 } },
      { odds: { base: 0.6, good: { attrs: { handling: -1 } }, bad: { injury: 4, attrs: { handling: -2 } } } },
    ],
    it: ['Il dito del portiere', '{player} si è lussato un dito in allenamento. Può giocare con una fasciatura, ma rischia.',
      ['Fermo due partite', 'Tocca al secondo portiere.'],
      ['Gioca con la fasciatura', 'Stringe i denti e regge.', 'Il dito non regge: stop più lungo.']],
    en: ['The goalkeeper’s finger', '{player} dislocated a finger in training. He can play strapped up, but it’s risky.',
      ['Out for two matches', 'The back-up keeper plays.'],
      ['He plays strapped up', 'He grits his teeth and holds up.', 'The finger can’t take it: a longer lay-off.']],
  },
  {
    id: 'md_altitude', cat: 'medical', w: 2, repeat: 100,
    when: { mdMax: 2 },
    o: [
      { fx: { teamFitness: 8, budget: -0.4, familiarity: -2 } },
      { fx: {} },
    ],
    it: ['Ritiro in altura', 'Il preparatore propone dieci giorni di ritiro in altura per aumentare la resistenza.',
      ['Si va in altura', 'Resistenza migliorata per mesi.'],
      ['Ritiro classico', 'Nessun cambio.']],
    en: ['Altitude camp', 'The fitness coach proposes a ten-day altitude camp to boost endurance.',
      ['Up to altitude', 'Endurance improved for months.'],
      ['A classic camp', 'No change.']],
  },
  {
    id: 'md_physio_leak', cat: 'medical', w: 2, repeat: 100,
    when: { player: { injured: true } },
    o: [
      { fx: { staff: -3, trust: 1 } },
      { fx: { reputation: -1 } },
    ],
    it: ['La cartella clinica sui giornali', 'La diagnosi di {player} è finita sui giornali prima che il club la comunicasse.',
      ['Allontano il responsabile', 'Lo staff si riduce, la fiducia della società cresce.'],
      ['Chiudo un occhio', 'Il caso si ripeterà?']],
    en: ['Medical records in the papers', '{player}’s diagnosis reached the papers before the club announced it.',
      ['Dismiss the person responsible', 'The staff shrinks, the board’s trust grows.'],
      ['Turn a blind eye', 'Will it happen again?']],
  },
  {
    id: 'md_ice_bath_refusal', cat: 'medical', w: 2, repeat: 60,
    when: { player: { personality: ['ribelle', 'pigro'] } },
    o: [
      { fx: { morale: -4, fitness: 8 } },
      { fx: { fitness: -6 } },
    ],
    it: ['Niente ghiaccio', '{player} si rifiuta di fare il bagno nel ghiaccio dopo gli allenamenti: “Lo odio”.',
      ['Obbligatorio per tutti', '{player} esegue brontolando e recupera meglio.'],
      ['Lasciamo perdere', '{player} recupera peggio.']],
    en: ['No ice bath', '{player} refuses to take ice baths after training: “I hate it”.',
      ['Mandatory for everyone', '{player} complies, grumbling, and recovers better.'],
      ['Let it go', '{player} recovers worse.']],
  },
  {
    id: 'md_marathon_run', cat: 'medical', w: 2, repeat: 60,
    when: { mdMin: 4 },
    o: [
      { fx: { teamFitness: -6, teamMorale: 3 } },
      { fx: {} },
    ],
    it: ['La corsa benefica', 'La città organizza una corsa benefica e chiede alla squadra di partecipare.',
      ['Corriamo tutti', 'Bella immagine e gruppo unito, gambe un po’ stanche.'],
      ['Partecipa solo lo staff', 'Squadra a riposo.']],
    en: ['The charity run', 'The city organises a charity run and asks the team to take part.',
      ['We all run', 'A good image and a united group, slightly tired legs.'],
      ['Only the staff take part', 'The team rests.']],
  },
  {
    id: 'md_knee_scan', cat: 'medical', w: 3, repeat: 30,
    when: { player: { rankMax: 6, fitnessMax: 80 } },
    o: [
      { fx: { fitness: 10, budget: -0.1 } },
      { odds: { base: 0.65, good: {}, bad: { injury: 3 } } },
    ],
    it: ['Un fastidio al ginocchio', '{player} sente un fastidio al ginocchio. Una risonanza costerebbe una settimana di stop precauzionale.',
      ['Risonanza e riposo', 'Nulla di grave: {player} torna riposato.'],
      ['Nessun esame, gioca', 'Il fastidio passa.', 'Era qualcosa di serio: stop.']],
    en: ['A niggle in the knee', '{player} feels a niggle in his knee. A scan would mean a precautionary week off.',
      ['Scan and rest', 'Nothing serious: {player} returns rested.'],
      ['No scan, he plays', 'The niggle goes away.', 'It was serious: out.']],
  },
  {
    id: 'md_vitamin_drip', cat: 'medical', w: 2, repeat: 80,
    when: { mdMin: 10 },
    o: [
      { fx: { teamFitness: 3, reputation: -1 } },
      { fx: { reputation: 1 } },
    ],
    it: ['Le flebo di vitamine', 'Il medico propone flebo di vitamine prima delle partite. Tutto legale, ma sui giornali potrebbe sembrare altro.',
      ['Facciamole', 'Qualche beneficio, e qualche malignità sui giornali.'],
      ['Meglio l’alimentazione', 'Nessun rischio d’immagine.']],
    en: ['Vitamin drips', 'The doctor proposes vitamin drips before matches. All legal, but in the papers it might look like something else.',
      ['Do it', 'Some benefit, and some snide press.'],
      ['Better through diet', 'No image risk.']],
  },
  {
    id: 'md_mouthguard', cat: 'medical', w: 2, repeat: 100,
    when: { player: { depts: ['DIF'] } },
    o: [
      { fx: { injuryProne: -6, morale: -2 } },
      { fx: {} },
    ],
    it: ['Il paradenti', 'Dopo un contrasto aereo {player} ha perso un dente. Il medico vuole che giochi con il paradenti.',
      ['Obbligatorio', '{player} brontola, ma è più protetto.'],
      ['Decide lui', 'Niente paradenti.']],
    en: ['The mouthguard', 'After an aerial challenge {player} lost a tooth. The doctor wants him to play with a mouthguard.',
      ['Mandatory', '{player} grumbles, but he’s better protected.'],
      ['His choice', 'No mouthguard.']],
  },
  {
    id: 'md_rehab_abroad', cat: 'medical', w: 3, repeat: 40,
    when: { player: { injured: true, rankMax: 10 } },
    o: [
      { fx: { injury: -1, bond: -5, budget: -0.2 } },
      { fx: { bond: 5 } },
    ],
    it: ['Riabilitazione lontano', '{player} vuole fare la riabilitazione nel centro specializzato del suo paese.',
      ['Autorizzo', 'Recupero leggermente più rapido, ma {player} si allontana dal gruppo.'],
      ['Resta qui con noi', '{player} resta vicino alla squadra.']],
    en: ['Rehab far away', '{player} wants to do his rehab at a specialist centre in his home country.',
      ['Authorise it', 'A slightly faster recovery, but {player} drifts from the group.'],
      ['He stays here with us', '{player} stays close to the team.']],
  },
];
