/* La stampa: conferenze, interviste, polemiche. Ogni parola detta ai
   microfoni arriva allo spogliatoio, in sede e in curva. */

export default [
  {
    id: 'pr_job_question', cat: 'press', w: 6, repeat: 12,
    when: { mdMin: 4, streakL: 2 },
    o: [
      { fx: { teamMorale: 3, trust: -2 } },
      { odds: { base: 0.5, rep: 0.006, good: { reputation: 3, teamMorale: 4 }, bad: { trust: -6, reputation: -2 } } },
      { fx: { fans: -3, trust: 2, reputation: -1 } },
    ],
    it: ['“Si sente in discussione?”', 'Due sconfitte di fila. In conferenza stampa la prima domanda è sempre la stessa: la tua panchina traballa?',
      ['“Sono qui per lavorare, non per parlare di me”', 'Risposta asciutta: la squadra apprezza. In sede qualcuno avrebbe voluto più autocritica.'],
      ['“Chi pensa che sia finita non conosce questo gruppo”', 'La frase diventa un titolo: la squadra si sente difesa.', 'Frase troppo sicura: suona come una sfida alla società.'],
      ['“Le responsabilità sono tutte mie”', 'L’umiltà piace alla società. I tifosi vorrebbero sentire più grinta.']],
    en: ['“Do you feel under pressure?”', 'Two defeats in a row. At the press conference the first question is always the same: is your job at risk?',
      ['“I’m here to work, not to talk about myself”', 'A dry answer: the team appreciates it. Some at the club wanted more self-criticism.'],
      ['“Anyone who thinks it’s over doesn’t know this group”', 'The line becomes a headline: the team feels defended.', 'Too sure of yourself: it sounds like a challenge to the board.'],
      ['“The responsibility is all mine”', 'The humility pleases the board. The fans wanted to hear more fight.']],
  },
  {
    id: 'pr_rival_coach_jab', cat: 'rival', w: 5, repeat: 15,
    when: { mdMin: 1 },
    o: [
      { odds: { base: 0.5, good: { teamMorale: 5, nextMatch: { attack: 1.05 } }, bad: { nextMatch: { discipline: 1.4 }, reputation: -2 } } },
      { fx: { reputation: 2, nextMatch: { control: 1.02 } } },
      { fx: { fans: 4, teamMorale: 2, nextMatch: { discipline: 1.2 } } },
    ],
    it: ['La frecciata del collega', 'L’allenatore del {opponent} dice ai giornali che la tua squadra “gioca un calcio vecchio”. Tutti aspettano la tua risposta.',
      ['Rispondo a tono', 'La squadra si carica per la sfida.', 'La polemica innervosisce tutti: si rischia di perdere la testa in campo.'],
      ['“Parlerà il campo”', 'Risposta elegante. Nessuna tensione in più.'],
      ['Lo prendo in giro con una battuta', 'I tifosi ridono e la squadra si diverte. In campo però c’è un po’ di nervosismo.']],
    en: ['A dig from the rival manager', 'The {opponent} manager tells the papers that your team “plays old-fashioned football”. Everyone awaits your reply.',
      ['Hit back', 'The team gets fired up for the game.', 'The row makes everyone edgy: heads could go on the pitch.'],
      ['“The pitch will do the talking”', 'An elegant answer. No extra tension.'],
      ['Mock him with a joke', 'The fans laugh and the team enjoys it. On the pitch, though, there’s some edge.']],
  },
  {
    id: 'pr_referee_after_loss', cat: 'press', w: 5, repeat: 10,
    when: { last: 'L', mdMin: 1 },
    o: [
      { fx: { fans: 4, suspendCoach: 1, reputation: -2, teamMorale: 2 } },
      { fx: { reputation: 2, fans: -2 } },
      { odds: { base: 0.6, good: { teamMorale: 3 }, bad: { teamMorale: -4 } } },
    ],
    it: ['L’arbitraggio', 'Un rigore negato nel finale. In sala stampa ti chiedono dell’arbitro.',
      ['“È uno scandalo, ci hanno derubato”', 'La curva ti adora. Il giudice sportivo un po’ meno: una giornata di squalifica.'],
      ['“Abbiamo perso per colpa nostra”', 'Nessuna polemica: guadagni rispetto nel mondo del calcio.'],
      ['“Guardate i video e giudicate voi”', 'Messaggio chiaro senza esporti: la squadra si sente difesa.', 'La frase sembra un alibi: nello spogliatoio c’è chi si rilassa troppo.']],
    en: ['The refereeing', 'A penalty denied late on. In the press room they ask about the referee.',
      ['“It’s a scandal, we were robbed”', 'The fans love you. The disciplinary judge less so: a one-match ban.'],
      ['“We lost because of our own mistakes”', 'No controversy: you earn respect in football.'],
      ['“Watch the replays and judge for yourselves”', 'A clear message without exposing yourself: the team feels defended.', 'It sounds like an excuse: some players get too relaxed.']],
  },
  {
    id: 'pr_star_praise', cat: 'press', w: 4, repeat: 15,
    when: { player: { rankMax: 3, avgMin: 6.8 } },
    o: [
      { fx: { morale: 8, bond: 5, teamMorale: -2 } },
      { fx: { teamMorale: 3, morale: -2 } },
    ],
    it: ['Le lodi a {player}', 'Un giornalista ti chiede se {player} sia il miglior giocatore del campionato.',
      ['“Per me sì, è il più forte”', '{player} si gonfia d’orgoglio. Qualche compagno si sente trascurato.'],
      ['“Il più forte è il gruppo”', 'Risposta da allenatore: lo spogliatoio apprezza, {player} un po’ meno.']],
    en: ['Praise for {player}', 'A journalist asks you whether {player} is the best player in the league.',
      ['“For me, yes, he’s the best”', '{player} swells with pride. Some teammates feel overlooked.'],
      ['“The best is the group”', 'A manager’s answer: the dressing room appreciates it, {player} a little less.']],
  },
  {
    id: 'pr_transfer_rumour_coach', cat: 'press', w: 4, repeat: 40,
    when: { mdMin: 10, gapMax: -1, repMin: 45 },
    o: [
      { fx: { trust: 6, reputation: -1 } },
      { fx: { reputation: 3, trust: -6, teamMorale: -2 } },
    ],
    it: ['“Un grande club la cerca”', 'I giornali scrivono che un grande club pensa a te per la prossima stagione.',
      ['“Io sto benissimo qui”', 'La società tira un sospiro di sollievo.'],
      ['“Fa piacere essere apprezzati”', 'La tua reputazione sale. In società e nello spogliatoio ci si chiede se resterai.']],
    en: ['“A big club wants you”', 'The papers report that a big club is considering you for next season.',
      ['“I’m very happy here”', 'The board breathes a sigh of relief.'],
      ['“It’s nice to be appreciated”', 'Your reputation rises. The board and the dressing room wonder if you’ll stay.']],
  },
  {
    id: 'pr_leak_lineup', cat: 'press', w: 4, repeat: 30,
    when: { mdMin: 2 },
    o: [
      { fx: { teamMorale: -4, trust: 2, nextMatch: { control: 1.02 } } },
      { fx: { nextMatch: { control: 0.96 } } },
      { odds: { base: 0.55, good: { nextMatch: { attack: 1.06 } }, bad: { teamMorale: -3 } } },
    ],
    it: ['La formazione sui giornali', 'Qualcuno dello spogliatoio passa ai giornalisti la formazione e la tattica della prossima partita.',
      ['Caccia alla talpa', 'Lo spogliatoio si sente sotto accusa, ma la fuga di notizie si ferma.'],
      ['Ignoro la cosa', 'L’avversario sa già tutto: si parte in svantaggio tattico.'],
      ['Cambio tutto all’ultimo momento', 'L’avversario si prepara a una squadra che non vedrà mai.', 'Troppi cambi in una notte: i giocatori sono confusi.']],
    en: ['The line-up in the papers', 'Someone in the dressing room leaks the line-up and tactics for the next match to journalists.',
      ['Hunt the mole', 'The dressing room feels accused, but the leaks stop.'],
      ['Ignore it', 'The opponent already knows everything: you start at a tactical disadvantage.'],
      ['Change everything at the last minute', 'The opponent prepares for a team it will never see.', 'Too many changes overnight: the players are confused.']],
  },
  {
    id: 'pr_tv_pundit', cat: 'press', w: 4, repeat: 20,
    when: { mdMin: 3, winless: 2 },
    o: [
      { fx: { reputation: -2, fans: 3 } },
      { fx: { teamMorale: 3 } },
      { fx: { reputation: 2, trust: 1 } },
    ],
    it: ['L’opinionista in TV', 'Un ex campione, oggi opinionista televisivo, dice in diretta che la tua squadra “non ha un’idea di gioco”.',
      ['Rispondo in diretta telefonica', 'Siparietto televisivo che diverte i tifosi, un po’ meno gli addetti ai lavori.'],
      ['Faccio vedere la clip alla squadra', 'La squadra usa la critica come benzina.'],
      ['Lo invito ad assistere a un allenamento', 'Mossa intelligente: l’opinionista cambia tono.']],
    en: ['The TV pundit', 'A former star turned TV pundit says live that your team “has no idea how to play”.',
      ['Phone in live to reply', 'A TV spat that amuses the fans, less so the insiders.'],
      ['Show the clip to the team', 'The team uses the criticism as fuel.'],
      ['Invite him to watch a training session', 'Smart move: the pundit changes his tune.']],
  },
  {
    id: 'pr_derby_words', cat: 'rival', w: 6, repeat: 8,
    when: { derbyNext: true },
    o: [
      { fx: { fans: 5, teamMorale: 3, nextMatch: { discipline: 1.3, attack: 1.03 } } },
      { fx: { nextMatch: { control: 1.03 } } },
      { odds: { base: 0.5, good: { fans: 6, nextMatch: { attack: 1.05 } }, bad: { fans: -4, teamMorale: -3 } } },
    ],
    it: ['La settimana del derby', 'Si avvicina il derby con il {opponent}. La città non parla d’altro e i giornalisti cercano la frase a effetto.',
      ['“Questa partita vale una stagione”', 'La tensione sale: squadra carica, ma a rischio cartellini.'],
      ['“È una partita come le altre”', 'Profilo basso: la squadra resta concentrata.'],
      ['“La città quest’anno è nostra”', 'La frase infiamma la curva e la squadra.', 'Frase che si ritorce contro: gli avversari la appendono nello spogliatoio.']],
    en: ['Derby week', 'The derby against {opponent} is coming. The city talks of nothing else and journalists want a punchline.',
      ['“This match is worth a season”', 'Tension rises: a fired-up team, but a risk of cards.'],
      ['“It’s a match like any other”', 'Low profile: the team stays focused.'],
      ['“This year the city is ours”', 'The line sets the fans and the team alight.', 'It backfires: the opponents pin it up in their dressing room.']],
  },
  {
    id: 'pr_tactics_question', cat: 'style', w: 4, repeat: 20,
    when: { mdMin: 3, winless: 3 },
    o: [
      { fx: { familiarity: -10, teamMorale: 2, trust: 2 } },
      { odds: { base: 0.5, good: { familiarity: 5, teamMorale: 4 }, bad: { trust: -5 } } },
    ],
    it: ['“Cambierà modulo?”', 'Tre partite senza vittorie. La stampa chiede se è il momento di abbandonare il tuo stile di gioco.',
      ['“Valuto tutto, anche un cambio”', 'La società apprezza l’apertura, ma la squadra perde certezze.'],
      ['“La strada è questa, non si cambia”', 'La squadra crede nel progetto e migliora.', 'La coerenza sembra testardaggine: la società si spazientisce.']],
    en: ['“Will you change system?”', 'Three games without a win. The press ask if it’s time to abandon your playing style.',
      ['“I’m considering everything, even a change”', 'The board likes the openness, but the team loses certainty.'],
      ['“This is the path, it won’t change”', 'The team believes in the project and improves.', 'Consistency looks like stubbornness: the board loses patience.']],
  },
  {
    id: 'pr_off_record', cat: 'press', w: 3, repeat: 40,
    when: { mdMin: 5 },
    o: [
      { fx: { reputation: -3, teamMorale: -5, trust: -2 } },
      { fx: { reputation: 1 } },
    ],
    it: ['Il fuori onda', 'Un microfono rimasto acceso ha registrato un tuo commento poco lusinghiero su un giocatore della rosa.',
      ['Minimizzo: “Era una battuta”', 'Nessuno ci crede: lo spogliatoio è freddo per giorni.'],
      ['Chiedo scusa pubblicamente e in privato', 'Le scuse sincere chiudono la questione.']],
    en: ['The hot mic', 'A microphone left on recorded an unflattering comment of yours about a squad player.',
      ['Play it down: “It was a joke”', 'Nobody believes it: the dressing room is cold for days.'],
      ['Apologise publicly and privately', 'A sincere apology closes the matter.']],
  },
  {
    id: 'pr_social_fake', cat: 'press', w: 3, repeat: 60,
    when: {},
    o: [
      { fx: { reputation: 1, budget: -0.1 } },
      { fx: { reputation: -2, fans: -2 } },
    ],
    it: ['La frase inventata', 'Sui social gira una tua frase falsa contro i tifosi. Migliaia di condivisioni.',
      ['Smentisco con un comunicato e un video', 'La smentita arriva in tempo: la bufala si sgonfia.'],
      ['Non rispondo alle bufale', 'Il silenzio viene preso per un’ammissione.']],
    en: ['The made-up quote', 'A fake quote of yours against the fans is spreading on social media. Thousands of shares.',
      ['Deny it with a statement and a video', 'The denial comes in time: the hoax fizzles out.'],
      ['I don’t respond to hoaxes', 'Silence is taken as an admission.']],
  },
  {
    id: 'pr_press_boycott', cat: 'press', w: 3, repeat: 40,
    when: { mdMin: 6, streakL: 3 },
    o: [
      { fx: { teamMorale: 4, reputation: -3, trust: -2 } },
      { fx: { reputation: 1, teamMorale: -1 } },
    ],
    it: ['Silenzio stampa?', 'Dopo tre sconfitte i senatori propongono il silenzio stampa per proteggere il gruppo dalle critiche.',
      ['Silenzio stampa totale', 'Il gruppo si chiude a riccio e si compatta. Giornali e società non gradiscono.'],
      ['No: ci metto la faccia', 'Ti prendi le critiche tu, il gruppo lavora tranquillo.']],
    en: ['Media blackout?', 'After three defeats the senior players propose a media blackout to shield the group from criticism.',
      ['Total media blackout', 'The group closes ranks and pulls together. The papers and the board don’t like it.'],
      ['No: I’ll face the press', 'You take the criticism, the group works in peace.']],
  },
  {
    id: 'pr_record_streak', cat: 'press', w: 5, repeat: 25,
    when: { streakW: 4 },
    o: [
      { fx: { teamMorale: 4, fans: 3, nextMatch: { block: 0.97 } } },
      { fx: { nextMatch: { control: 1.02 }, reputation: 1 } },
    ],
    it: ['“Siete da titolo?”', 'Quattro vittorie di fila: i giornalisti vogliono sapere se la squadra può puntare in alto.',
      ['“Non poniamo limiti”', 'Entusiasmo alle stelle. Il rischio è di sentirsi già arrivati.'],
      ['“Pensiamo alla prossima partita”', 'Frase fatta, ma tiene tutti con i piedi per terra.']],
    en: ['“Title contenders?”', 'Four wins in a row: journalists want to know if the team can aim high.',
      ['“We set no limits”', 'Enthusiasm through the roof. The risk is feeling you’ve already made it.'],
      ['“We think about the next match”', 'A cliché, but it keeps everyone grounded.']],
  },
  {
    id: 'pr_player_criticised', cat: 'press', w: 5, repeat: 12,
    when: { last: 'L', player: { starter: true, avgMax: 6.2, appsMin: 3 } },
    o: [
      { fx: { morale: 8, bond: 8 } },
      { odds: { base: 0.45, pers: { professionista: 0.2, leader: 0.1, fragile: -0.25, ribelle: -0.15 }, good: { form: 3 }, bad: { morale: -15, bond: -12 } } },
    ],
    it: ['I giornali contro {player}', 'I voti in pagella di {player} sono i peggiori della squadra. Un quotidiano titola: “È lui il problema”.',
      ['Lo difendo pubblicamente', '{player} ti ringrazia: sa di avere un allenatore dalla sua parte.'],
      ['“Deve dare di più, e lo sa”', 'La critica lo sprona.', 'Sentirsi attaccato anche dall’allenatore lo abbatte.']],
    en: ['The papers against {player}', '{player}’s ratings are the worst in the team. A newspaper headline says: “He’s the problem”.',
      ['Defend him publicly', '{player} thanks you: he knows his manager is on his side.'],
      ['“He has to give more, and he knows it”', 'The criticism spurs him on.', 'Being attacked by his own manager too crushes him.']],
  },
  {
    id: 'pr_foreign_press', cat: 'press', w: 3, repeat: 60,
    when: { repMin: 55 },
    o: [
      { fx: { reputation: 3, teamFitness: -2 } },
      { fx: {} },
    ],
    it: ['Intervista internazionale', 'Un grande giornale straniero vuole un’intervista lunga sul tuo metodo di lavoro.',
      ['Accetto', 'L’intervista gira in tutta Europa: il tuo nome cresce.'],
      ['Declino', 'Nessuna distrazione.']],
    en: ['International interview', 'A major foreign newspaper wants a long interview about your methods.',
      ['Accept', 'The interview goes around Europe: your name grows.'],
      ['Decline', 'No distractions.']],
  },
  {
    id: 'pr_racism_episode', cat: 'press', w: 3, repeat: 60,
    when: { mdMin: 2, player: { foreign: true, starter: true } },
    o: [
      { fx: { reputation: 4, bond: 15, morale: 6, teamMorale: 5 } },
      { fx: { bond: -10, morale: -10, reputation: -3 } },
    ],
    it: ['Insulti razzisti', 'Durante l’ultima partita {player} è stato bersaglio di cori razzisti dagli spalti. Tutti aspettano la tua presa di posizione.',
      ['Condanno con forza e chiedo sanzioni', 'La tua voce è netta: {player} e la squadra si sentono protetti.'],
      ['“Non ho sentito nulla”', 'Risposta evasiva: {player} si sente abbandonato e la stampa ti critica.']],
    en: ['Racist abuse', 'During the last match {player} was targeted by racist chants from the stands. Everyone awaits your stance.',
      ['Condemn it strongly and demand sanctions', 'Your voice is clear: {player} and the team feel protected.'],
      ['“I didn’t hear anything”', 'An evasive answer: {player} feels abandoned and the press criticises you.']],
  },
  {
    id: 'pr_old_club_question', cat: 'press', w: 3, repeat: 60,
    when: { seasonsMin: 1 },
    o: [
      { fx: { fans: 3, reputation: -1 } },
      { fx: { reputation: 2 } },
    ],
    it: ['La domanda sul passato', 'Un giornalista ti chiede un commento sulle tue esperienze precedenti e su chi non ha creduto in te.',
      ['“Qualcuno si è sbagliato”', 'I tifosi apprezzano la grinta. Nell’ambiente qualcuno la trova una caduta di stile.'],
      ['“Porto rispetto a tutti”', 'Risposta signorile.']],
    en: ['The question about the past', 'A journalist asks you to comment on your previous jobs and those who didn’t believe in you.',
      ['“Someone got it wrong”', 'The fans like the fight. Some in the game find it classless.'],
      ['“I respect everyone”', 'A classy answer.']],
  },
  {
    id: 'pr_young_hype', cat: 'press', w: 4, repeat: 25,
    when: { player: { ageMax: 20, avgMin: 6.8, appsMin: 2 } },
    o: [
      { odds: { base: 0.5, pers: { professionista: 0.2, ambizioso: -0.15, fragile: -0.15 }, good: { morale: 8, attrs: { composure: 2 } }, bad: { form: -4, consistency: -8 } } },
      { fx: { potential: 1, morale: -2 } },
    ],
    it: ['Il nuovo fenomeno', 'Dopo le ultime partite i giornali paragonano {player} ai più grandi di sempre. Le richieste di interviste sono decine.',
      ['Lo lascio parlare con i giornalisti', '{player} gestisce la pressione da veterano.', 'Il clamore gli dà alla testa e le prestazioni ne risentono.'],
      ['Lo proteggo: niente interviste', '{player} continua a lavorare lontano dal rumore.']],
    en: ['The new phenomenon', 'After his recent performances the papers compare {player} to the all-time greats. Dozens of interview requests.',
      ['Let him talk to the press', '{player} handles the pressure like a veteran.', 'The hype goes to his head and his performances suffer.'],
      ['Protect him: no interviews', '{player} keeps working away from the noise.']],
  },
  {
    id: 'pr_injury_blame', cat: 'medical', w: 3, repeat: 30,
    when: { injuredMin: 2 },
    o: [
      { fx: { staff: -5, reputation: 1 } },
      { fx: { staff: 3, reputation: -2 } },
    ],
    it: ['Di chi è la colpa?', 'La stampa chiede se gli infortuni siano colpa della preparazione atletica.',
      ['“Lo staff deve rivedere qualcosa”', 'Lo staff si sente scaricato. I giornalisti apprezzano la franchezza.'],
      ['“La responsabilità è solo mia”', 'Lo staff ti è grato; la stampa ti accusa di coprire gli errori.']],
    en: ['Whose fault is it?', 'The press ask whether the injuries are down to the fitness programme.',
      ['“The staff need to review a few things”', 'The staff feel thrown under the bus. Journalists appreciate the honesty.'],
      ['“The responsibility is mine alone”', 'The staff are grateful; the press accuse you of covering up mistakes.']],
  },
  {
    id: 'pr_press_prank', cat: 'press', w: 2, repeat: 80,
    when: {},
    o: [
      { fx: { fans: 3, teamMorale: 3, reputation: -1 } },
      { fx: { reputation: 1 } },
    ],
    it: ['Lo scherzo in conferenza', 'I giocatori organizzano uno scherzo in diretta durante la tua conferenza stampa: una torta in faccia.',
      ['Rido e sto al gioco', 'Il video fa il giro del mondo: squadra e tifosi ti adorano.'],
      ['Mi arrabbio: c’è un limite', 'Il messaggio arriva: la conferenza è una cosa seria.']],
    en: ['The press conference prank', 'The players pull a prank live during your press conference: a cake in the face.',
      ['Laugh and play along', 'The video goes around the world: team and fans adore you.'],
      ['Get angry: there are limits', 'The message gets through: press conferences are serious.']],
  },
  {
    id: 'pr_contract_leak', cat: 'press', w: 3, repeat: 50,
    when: { player: { rankMax: 5, contractLeft: 1 } },
    o: [
      { fx: { morale: -8, trust: 2 } },
      { fx: { morale: 6, bond: 4 } },
    ],
    it: ['Le cifre del rinnovo', 'Un giornale pubblica le cifre che {player} chiederebbe per rinnovare. Tutti ti chiedono se valga quei soldi.',
      ['“Nessuno vale più della squadra”', 'Frase che piace in società. {player} la legge come un segnale.'],
      ['“Vale ogni centesimo”', '{player} si sente apprezzato. La società ora dovrà trattare.']],
    en: ['The renewal numbers', 'A newspaper publishes the figures {player} is supposedly demanding to renew. Everyone asks if he’s worth it.',
      ['“Nobody is worth more than the team”', 'The board likes it. {player} reads it as a signal.'],
      ['“He’s worth every penny”', '{player} feels valued. Now the club will have to negotiate.']],
  },
  {
    id: 'pr_manager_award', cat: 'press', w: 3, repeat: 40,
    when: { streakW: 3, mdMin: 6 },
    o: [
      { fx: { reputation: 4, teamMorale: -1 } },
      { fx: { teamMorale: 4, reputation: 2 } },
    ],
    it: ['Allenatore del mese', 'Vinci il premio di allenatore del mese. Alla consegna devi dire due parole.',
      ['Mi godo il premio', 'Il tuo nome gira. Qualche giocatore pensa che il merito sia anche suo.'],
      ['Dedico il premio ai giocatori', 'Lo spogliatoio apprezza il gesto.']],
    en: ['Manager of the month', 'You win manager of the month. At the ceremony you have to say a few words.',
      ['Enjoy the award', 'Your name gets around. Some players think the credit is theirs too.'],
      ['Dedicate it to the players', 'The dressing room appreciates the gesture.']],
  },
  {
    id: 'pr_title_rival_mindgames', cat: 'rival', w: 4, repeat: 20,
    when: { posMax: 3, mdMin: 15 },
    o: [
      { odds: { base: 0.5, rep: 0.006, good: { teamMorale: 5, reputation: 2 }, bad: { teamMorale: -5 } } },
      { fx: { nextMatch: { control: 1.02 } } },
    ],
    it: ['Guerra psicologica', 'In corsa per il vertice, i rivali dicono che la tua squadra “crollerà sotto pressione”.',
      ['Rispondo: “La pressione ce l’hanno loro”', 'La squadra si sente forte e protetta.', 'La tensione sale e la squadra ne risente.'],
      ['Non rispondo', 'Nessuna distrazione dal lavoro.']],
    en: ['Mind games', 'In the race at the top, the rivals say your team “will crack under pressure”.',
      ['Reply: “They’re the ones under pressure”', 'The team feels strong and protected.', 'The tension rises and the team feels it.'],
      ['Don’t reply', 'No distraction from the work.']],
  },
  {
    id: 'pr_fans_banner_press', cat: 'fans', w: 3, repeat: 30,
    when: { fansMax: 40 },
    o: [
      { fx: { fans: 6, trust: -2 } },
      { fx: { fans: -3, trust: 2 } },
    ],
    it: ['Lo striscione contro la società', 'I tifosi espongono uno striscione contro la proprietà. I giornalisti ti chiedono se lo condividi.',
      ['“Capisco la loro rabbia”', 'I tifosi ti sentono vicino. La proprietà no.'],
      ['“Non commento”', 'La società apprezza. La curva ti considera dalla parte del presidente.']],
    en: ['The banner against the club', 'The fans display a banner against the owners. Journalists ask whether you agree with it.',
      ['“I understand their anger”', 'The fans feel you’re with them. The owners don’t.'],
      ['“No comment”', 'The board appreciates it. The ultras see you as the chairman’s man.']],
  },
  {
    id: 'pr_ex_player_attack', cat: 'press', w: 3, repeat: 40,
    when: { mdMin: 4 },
    o: [
      { fx: { teamMorale: 3, reputation: -1 } },
      { fx: { reputation: 2 } },
    ],
    it: ['L’ex giocatore', 'Un giocatore che hai allenato in passato racconta in un podcast che eri “un sergente”.',
      ['Rispondo con ironia', 'La squadra ride con te: clima disteso.'],
      ['Ignoro', 'Nessuna polemica.']],
    en: ['The former player', 'A player you once coached says on a podcast that you were “a drill sergeant”.',
      ['Answer with irony', 'The team laughs with you: a relaxed atmosphere.'],
      ['Ignore it', 'No controversy.']],
  },
  {
    id: 'pr_live_mic_tactics', cat: 'style', w: 3, repeat: 40,
    when: { mdMin: 2 },
    o: [
      { fx: { reputation: 2, nextMatch: { control: 0.97 } } },
      { fx: {} },
    ],
    it: ['La lavagna in TV', 'Una trasmissione ti invita a spiegare la tua tattica davanti a una lavagna, in diretta.',
      ['Accetto: il calcio va raccontato', 'Bella figura in TV. Il prossimo avversario però ha preso appunti.'],
      ['I segreti restano nello spogliatoio', 'Nessuna informazione regalata.']],
    en: ['The tactics board on TV', 'A TV show invites you to explain your tactics at a whiteboard, live.',
      ['Accept: football should be explained', 'You look good on TV. The next opponent took notes, though.'],
      ['Secrets stay in the dressing room', 'No information given away.']],
  },
  {
    id: 'pr_survival_talk', cat: 'press', w: 4, repeat: 20,
    when: { mdMin: 20, objective: ['survival', 'safe'], gapMin: 1 },
    o: [
      { fx: { teamMorale: 4, nextMatch: { attack: 1.03 } } },
      { odds: { base: 0.5, good: { teamMorale: 6, fans: 4 }, bad: { teamMorale: -6 } } },
    ],
    it: ['“Vi salverete?”', 'Siete sotto la linea dell’obiettivo. I giornalisti chiedono se la squadra ci crede ancora.',
      ['“Ci salveremo, ne sono certo”', 'La sicurezza contagia il gruppo.'],
      ['“Ogni partita è una finale”', 'La squadra entra in modalità battaglia.', 'La frase mette troppa pressione: gambe che tremano.']],
    en: ['“Will you stay up?”', 'You’re below the target line. Journalists ask whether the team still believes.',
      ['“We’ll stay up, I’m sure of it”', 'The confidence spreads through the group.'],
      ['“Every match is a final”', 'The team switches into battle mode.', 'Too much pressure: shaky legs.']],
  },
  {
    id: 'pr_gaffe_language', cat: 'press', w: 2, repeat: 80,
    when: {},
    o: [
      { fx: { fans: 4, reputation: 1 } },
      { fx: { reputation: -1 } },
    ],
    it: ['La gaffe linguistica', 'Durante un’intervista in una lingua straniera sbagli una parola e dici una cosa esilarante. Il video spopola.',
      ['Ci scherzo su', 'Diventi simpatico a tutti.'],
      ['Chiedo di rimuovere il video', 'Il video si diffonde ancora di più.']],
    en: ['The language gaffe', 'During an interview in a foreign language you get a word wrong and say something hilarious. The clip goes viral.',
      ['Joke about it', 'Everyone warms to you.'],
      ['Ask for the clip to be removed', 'It spreads even more.']],
  },
  {
    id: 'pr_captain_press', cat: 'press', w: 3, repeat: 30,
    when: { last: 'L', player: { captain: true } },
    o: [
      { fx: { bond: 6, teamMorale: 3 } },
      { fx: { reputation: 1, bond: -4 } },
    ],
    it: ['Il capitano in conferenza', '{player} chiede di andare lui in conferenza stampa dopo la sconfitta, per metterci la faccia.',
      ['Va bene, parla il capitano', '{player} parla da leader: la squadra si compatta.'],
      ['Ci vado io, è compito mio', 'Proteggi il capitano. Lui avrebbe voluto farlo.']],
    en: ['The captain faces the press', '{player} asks to do the press conference himself after the defeat, to take responsibility.',
      ['Fine, the captain speaks', '{player} speaks like a leader: the team pulls together.'],
      ['I’ll go, it’s my job', 'You protect your captain. He would have liked to do it.']],
  },
  {
    id: 'pr_betting_odds', cat: 'press', w: 3, repeat: 40,
    when: { mdMin: 6, trustMax: 45 },
    o: [
      { fx: { teamMorale: 3 } },
      { fx: { reputation: -1, trust: -1 } },
    ],
    it: ['Primo nella lista degli esoneri', 'Le agenzie di scommesse ti danno come primo allenatore a essere esonerato. I giornali ci ricamano sopra.',
      ['Lo appendo nello spogliatoio: “Smentiamoli”', 'La squadra la prende come una sfida personale.'],
      ['Faccio finta di niente', 'La notizia gira comunque, e mina un po’ la tua autorità.']],
    en: ['Favourite for the sack', 'The bookmakers make you favourite to be the first manager sacked. The papers run with it.',
      ['Pin it up in the dressing room: “Prove them wrong”', 'The team takes it as a personal challenge.'],
      ['Pretend nothing happened', 'The story spreads anyway and chips at your authority.']],
  },
  {
    id: 'pr_christmas_message', cat: 'press', w: 3, repeat: 40,
    when: { mdMin: 16, mdMax: 20 },
    o: [
      { fx: { fans: 4, teamMorale: 2 } },
      { fx: { teamFitness: 4 } },
    ],
    it: ['Gli auguri di Natale', 'L’ufficio stampa vuole un video di auguri con tutta la squadra, girato in una giornata di riposo.',
      ['Giriamo il video', 'Video simpatico: i tifosi apprezzano e il gruppo si diverte.'],
      ['Il riposo è sacro', 'Niente video, gambe più fresche.']],
    en: ['Christmas greetings', 'The press office wants a Christmas video with the whole squad, filmed on a rest day.',
      ['Film the video', 'A fun video: the fans love it and the group enjoys it.'],
      ['Rest days are sacred', 'No video, fresher legs.']],
  },
  {
    id: 'pr_leaked_argument', cat: 'dressing', w: 4, repeat: 30,
    when: { mdMin: 4, player: { rankMax: 8, personality: ['ribelle', 'ambizioso', 'leader'] } },
    o: [
      { fx: { bond: -8, trust: 3, teamMorale: -2 } },
      { odds: { base: 0.5, bond: 0.006, good: { bond: 12, teamMorale: 4 }, bad: { teamMorale: -5, bond: -6 } } },
    ],
    it: ['La lite finisce sui giornali', 'La tua discussione con {player} durante l’allenamento è finita sui giornali, con dettagli precisi.',
      ['Confermo: “Chi sbaglia paga”', 'La società apprezza. {player} si sente esposto pubblicamente.'],
      ['Appariamo insieme davanti ai giornalisti', 'Immagine di unità: la lite si trasforma in forza.', 'Il sorriso di circostanza non convince nessuno.']],
    en: ['The row reaches the papers', 'Your argument with {player} at training made the papers, with precise details.',
      ['Confirm it: “Mistakes have consequences”', 'The board likes it. {player} feels publicly exposed.'],
      ['Appear together in front of the press', 'A picture of unity: the row becomes strength.', 'The forced smiles convince no one.']],
  },
  {
    id: 'pr_injury_secret', cat: 'medical', w: 3, repeat: 30,
    when: { player: { injured: true, rankMax: 5 } },
    o: [
      { fx: { nextMatch: { control: 1.02 }, reputation: -1 } },
      { fx: { reputation: 1 } },
    ],
    it: ['Nascondere l’infortunio', 'L’avversario non sa che {player} è infortunato. Il tuo vice propone di far credere che giocherà.',
      ['Lasciamoli nel dubbio', 'L’avversario prepara la partita contro un giocatore che non ci sarà.'],
      ['Comunico l’infortunio', 'Trasparenza: nessun vantaggio, nessuna polemica.']],
    en: ['Hiding the injury', 'The opponents don’t know {player} is injured. Your assistant suggests making them think he’ll play.',
      ['Keep them guessing', 'The opponent prepares for a player who won’t be there.'],
      ['Announce the injury', 'Transparency: no advantage, no controversy.']],
  },
  {
    id: 'pr_away_ban_fans', cat: 'fans', w: 3, repeat: 40,
    when: { mdMin: 2 },
    o: [
      { fx: { fans: 5, trust: -1 } },
      { fx: { reputation: 1 } },
    ],
    it: ['Trasferta vietata ai tifosi', 'Le autorità vietano la trasferta ai tuoi tifosi per motivi di ordine pubblico. Ti chiedono un commento.',
      ['“Una decisione ingiusta”', 'I tifosi apprezzano la solidarietà.'],
      ['“Le regole si rispettano”', 'Risposta istituzionale.']],
    en: ['Away fans banned', 'The authorities ban your fans from the away match for public order reasons. You’re asked to comment.',
      ['“An unfair decision”', 'The fans appreciate the solidarity.'],
      ['“Rules must be respected”', 'An institutional answer.']],
  },
  {
    id: 'pr_record_defeat', cat: 'press', w: 5, repeat: 30,
    when: { last: 'L', mdMin: 1, trustMax: 70 },
    o: [
      { fx: { teamMorale: -3, trust: 3 } },
      { fx: { teamMorale: 4, trust: -2 } },
      { odds: { base: 0.5, good: { teamMorale: 5, teamForm: 1 }, bad: { teamMorale: -6 } } },
    ],
    it: ['La sconfitta brucia', 'In conferenza stampa l’aria è pesante. Come commenti la sconfitta?',
      ['“Una prestazione vergognosa”', 'La società apprezza la franchezza. I giocatori si sentono messi alla gogna.'],
      ['“Ho visto cose buone”', 'La squadra si sente protetta. I tifosi pensano che tu non veda i problemi.'],
      ['“Da domani doppi allenamenti”', 'Il messaggio arriva: la squadra reagisce.', 'I giocatori lo vivono come una punizione: il morale crolla.']],
    en: ['A painful defeat', 'The press room feels heavy. How do you sum up the defeat?',
      ['“A shameful performance”', 'The board appreciates the honesty. The players feel pilloried.'],
      ['“I saw good things”', 'The team feels protected. The fans think you can’t see the problems.'],
      ['“Double sessions from tomorrow”', 'The message lands: the team reacts.', 'The players see it as punishment: morale collapses.']],
  },
  {
    id: 'pr_youth_question', cat: 'youth', w: 3, repeat: 30,
    when: { mdMin: 5 },
    o: [
      { fx: { fans: 3, youngsters: { morale: 5 }, trust: 1 } },
      { fx: { reputation: 1 } },
    ],
    it: ['“E i giovani?”', 'I giornalisti ti chiedono perché i ragazzi del vivaio giochino così poco.',
      ['“Presto vedrete qualche esordio”', 'I tifosi e i ragazzi ci sperano. Ora però se lo aspettano.'],
      ['“Gioca chi è pronto”', 'Risposta onesta, nessuna promessa.']],
    en: ['“What about the youngsters?”', 'Journalists ask why the academy players get so few minutes.',
      ['“You’ll see some debuts soon”', 'The fans and the kids hope so. Now they expect it.'],
      ['“Whoever is ready plays”', 'An honest answer, no promises.']],
  },
  {
    id: 'pr_top_scorer_race', cat: 'press', w: 3, repeat: 20,
    when: { mdMin: 12, player: { roles: ['PUN', 'ALA'], goalsMin: 8 } },
    o: [
      { fx: { morale: 6, penalties: true, teamMorale: -2 } },
      { fx: { teamMorale: 2, morale: -2 } },
    ],
    it: ['La corsa al titolo di capocannoniere', '{player} è in corsa per il titolo di capocannoniere. I giornalisti ti chiedono se la squadra lo aiuterà.',
      ['“Batterà lui i rigori”', '{player} è felicissimo. Il vecchio rigorista meno.'],
      ['“Conta la squadra, non la classifica marcatori”', 'Nessuna gerarchia nuova.']],
    en: ['The race for top scorer', '{player} is in the race for the golden boot. Journalists ask if the team will help him.',
      ['“He’ll take the penalties”', '{player} is delighted. The old penalty taker less so.'],
      ['“The team matters, not the scoring chart”', 'No new pecking order.']],
  },
  {
    id: 'pr_coach_book', cat: 'private', w: 2, repeat: 150,
    when: { repMin: 50 },
    o: [
      { fx: { reputation: 3, budget: 0.2, teamFitness: -2 } },
      { fx: {} },
    ],
    it: ['Un libro sul tuo metodo', 'Un editore ti propone di scrivere un libro sul tuo modo di allenare.',
      ['Ci sto', 'Il libro vende bene: il tuo nome cresce. Qualche notte passata a scrivere.'],
      ['Non ora', 'Il libro può aspettare.']],
    en: ['A book about your method', 'A publisher offers you a deal for a book about how you coach.',
      ['I’m in', 'The book sells well: your name grows. A few nights spent writing.'],
      ['Not now', 'The book can wait.']],
  },
  {
    id: 'pr_final_day_nerves', cat: 'press', w: 5, repeat: 30,
    when: { mdFromEndMax: 2, gapMin: -1, gapMax: 2 },
    o: [
      { fx: { teamMorale: 5, nextMatch: { discipline: 1.15 } } },
      { fx: { nextMatch: { control: 1.03 } } },
    ],
    it: ['Tutto in una partita', 'Mancano pochissime giornate e l’obiettivo si decide ora. La conferenza stampa è gremita.',
      ['“Ci giochiamo la vita”', 'La squadra entra in campo con il fuoco dentro, forse troppo.'],
      ['“Serenità: siamo pronti”', 'Il gruppo resta lucido.']],
    en: ['Everything on one match', 'Only a few matchdays left and the target is decided now. The press room is packed.',
      ['“Our lives are on the line”', 'The team takes the field with fire inside, maybe too much.'],
      ['“Calm: we’re ready”', 'The group stays clear-headed.']],
  },
  {
    id: 'pr_praise_opponent', cat: 'press', w: 3, repeat: 30,
    when: { mdMin: 1 },
    o: [
      { fx: { reputation: 2, nextMatch: { attack: 0.98 } } },
      { fx: { teamMorale: 2, nextMatch: { control: 1.01 } } },
    ],
    it: ['Elogi all’avversario', 'Prima della sfida con il {opponent} ti chiedono cosa pensi dei prossimi avversari.',
      ['“Una squadra fortissima, da rispettare”', 'Parole da signore. La squadra forse li teme un po’ di più.'],
      ['“Li rispettiamo, ma giochiamo per vincere”', 'La squadra percepisce fiducia.']],
    en: ['Praising the opponent', 'Before the game against {opponent} you’re asked what you think of them.',
      ['“A very strong team, to be respected”', 'Gracious words. The team may fear them a little more.'],
      ['“We respect them, but we play to win”', 'The team senses confidence.']],
  },
];
