/* Scelte sui singoli giocatori: il voto, il potenziale, il morale e il
   legame con l'allenatore si muovono in base alla risposta. */

export default [
  {
    id: 'pl_extra_training', cat: 'player', w: 7, repeat: 14,
    when: { player: { ageMax: 27, potentialGap: 3, injured: false } },
    o: [
      { odds: { base: 0.62, pers: { professionista: 0.22, ambizioso: 0.12, pigro: -0.3, ribelle: -0.12 }, bond: 0.003, good: { attrs: { role: 2 }, potential: 1, bond: 6, fitness: -8 }, bad: { attrs: { role: -1 }, morale: -12, bond: -8, injury: 1 } } },
      { fx: { morale: 3 } },
    ],
    it: ['Doppia seduta per {player}?', 'Lo staff tecnico propone un programma di allenamenti extra per {player}: pomeriggi in palestra e video delle sue partite. Può fare il salto, o spremerlo troppo.',
      ['Doppia seduta per un mese', '{player} risponde alla grande: più sicuro, più preciso, più veloce di pensiero.', '{player} non la regge: si trascina, si lamenta e alla fine si ferma con un risentimento.'],
      ['Nessun extra, gestiamo le energie', '{player} apprezza la fiducia e si allena sereno.']],
    en: ['Double sessions for {player}?', 'The coaching staff propose an extra training plan for {player}: afternoons in the gym and video of his matches. It could be the leap forward, or it could burn him out.',
      ['Double sessions for a month', '{player} responds superbly: more confident, sharper, quicker in thought.', '{player} can’t take it: he drags himself around, complains and ends up with a strain.'],
      ['No extras, manage his energy', '{player} appreciates the trust and trains calmly.']],
  },
  {
    id: 'pl_bench_star', cat: 'player', w: 6, repeat: 16,
    when: { mdMin: 4, player: { rankMax: 4, avgMax: 6.3, appsMin: 3, injured: false } },
    o: [
      { odds: { base: 0.5, pers: { professionista: 0.25, leader: 0.1, ambizioso: 0.05, ribelle: -0.3, fragile: -0.2 }, good: { form: 4, attrs: { role: 1 }, morale: 4 }, bad: { morale: -22, bond: -20, form: -2 } }, fx: { nextMatch: {} } },
      { fx: { morale: 4, bond: 4 } },
      { fx: { form: 2, bond: 8, teamMorale: -2 } },
    ],
    it: ['{player} in crisi', '{player} è uno dei migliori della rosa, ma nelle ultime partite ha la media più bassa della squadra. I giornali chiedono la panchina.',
      ['Una partita in panchina per scuoterlo', 'La panchina lo punge: in allenamento è un altro e torna in campo affamato.', '{player} la vive come un’umiliazione e smette di parlarti.'],
      ['Titolare, la fiducia non si discute', '{player} ringrazia e promette di ripagarti.'],
      ['Lo difendo in conferenza stampa', 'Il gesto lo carica, ma qualcuno nello spogliatoio pensa che per lui valgano regole diverse.']],
    en: ['{player} in a slump', '{player} is one of the best in the squad, but lately he has the lowest average rating in the team. The papers want him dropped.',
      ['Drop him for a match to shake him up', 'Being dropped stings: he’s a different man in training and returns hungry.', '{player} takes it as a humiliation and stops talking to you.'],
      ['He starts, trust is not up for debate', '{player} thanks you and promises to repay you.'],
      ['Defend him at the press conference', 'The gesture fires him up, but some in the dressing room think different rules apply to him.']],
  },
  {
    id: 'pl_position_change_fb', cat: 'player', w: 4, repeat: 60,
    when: { player: { roles: ['ALA'], ageMax: 30, rankMin: 3 } },
    o: [
      { odds: { base: 0.52, pers: { professionista: 0.2, ambizioso: -0.1, ribelle: -0.2 }, age: -0.02, good: { newRole: 'TZ', attrs: { tackling: 6, marking: 6, stamina: 3 }, morale: 5 }, bad: { newRole: 'TZ', attrs: { tackling: 3, marking: 3 }, morale: -18, form: -3 } } },
      { fx: { morale: 2 } },
    ],
    it: ['{player} terzino?', 'Lo staff vede in {player} un terzino moderno: corsa, cross, uno contro uno. Ma lui si è sempre sentito un attaccante.',
      ['Lo provo terzino da subito', 'Esperimento riuscito: {player} scopre un ruolo nuovo e ci si trova benissimo.', '{player} gioca da terzino controvoglia: impara a difendere, ma perde il sorriso.'],
      ['Resta dov’è', '{player} continua nel suo ruolo.']],
    en: ['{player} at full-back?', 'The staff see a modern full-back in {player}: running, crossing, one against one. But he has always seen himself as an attacker.',
      ['Try him at full-back right away', 'Experiment works: {player} finds a new role and thrives in it.', '{player} plays full-back reluctantly: he learns to defend, but loses his smile.'],
      ['He stays where he is', '{player} carries on in his role.']],
  },
  {
    id: 'pl_position_change_mid', cat: 'player', w: 4, repeat: 60,
    when: { player: { roles: ['DC'], ageMax: 29, rankMin: 4 } },
    o: [
      { odds: { base: 0.48, pers: { professionista: 0.2, leader: 0.1, ribelle: -0.2 }, good: { newRole: 'MED', attrs: { passing: 6, vision: 4, positioning: 2 }, morale: 5 }, bad: { newRole: 'MED', attrs: { passing: 2 }, morale: -12, form: -3 } } },
      { fx: {} },
    ],
    it: ['{player} davanti alla difesa', 'In allenamento {player} imposta meglio di tanti centrocampisti. E se diventasse il tuo mediano?',
      ['Sì, lo sposto a mediano', '{player} detta i tempi come se l’avesse sempre fatto.', 'A centrocampo {player} va in affanno: il ritmo è un altro.'],
      ['Meglio difensore', 'Tutto resta com’è.']],
    en: ['{player} in front of the defence', 'In training {player} builds play better than many midfielders. What if he became your holding midfielder?',
      ['Yes, move him to holding midfield', '{player} dictates the tempo as if he had always done it.', 'In midfield {player} struggles: the pace is different.'],
      ['Better as a defender', 'Everything stays as it is.']],
  },
  {
    id: 'pl_striker_to_wing', cat: 'player', w: 3, repeat: 60,
    when: { player: { roles: ['PUN'], ageMax: 27, rankMin: 3 } },
    o: [
      { odds: { base: 0.5, pers: { professionista: 0.15, ambizioso: 0.1, pigro: -0.15 }, good: { newRole: 'ALA', attrs: { dribbling: 5, crossing: 5, pace: 2 }, morale: 4 }, bad: { newRole: 'ALA', attrs: { crossing: 2 }, morale: -12 } } },
      { fx: { morale: 2 } },
    ],
    it: ['{player} largo a destra', 'Con tante punte in rosa, lo staff propone di spostare {player} sulla fascia, dove può partire in velocità.',
      ['Lo provo ala', '{player} si diverte: dribbling, cross, gol partendo largo.', '{player} si perde sulla fascia: non riceve mai dove vorrebbe.'],
      ['Resta punta', '{player} resta al centro dell’attacco.']],
    en: ['{player} out wide', 'With plenty of strikers in the squad, the staff suggest moving {player} out wide, where he can run at people.',
      ['Try him on the wing', '{player} loves it: dribbles, crosses, goals from wide.', '{player} gets lost on the flank: he never receives the ball where he wants it.'],
      ['He stays up front', '{player} stays at the centre of the attack.']],
  },
  {
    id: 'pl_captaincy', cat: 'player', w: 4, repeat: 80,
    when: { mdMax: 6, player: { rankMax: 8, ageMin: 24, noFlag: 'captainOffered', personality: ['leader', 'professionista', 'ambizioso', 'ribelle'] } },
    o: [
      { odds: { base: 0.6, pers: { leader: 0.3, professionista: 0.15, ribelle: -0.25, ambizioso: -0.05 }, good: { captain: true, morale: 12, bond: 15, attrs: { composure: 3 }, teamMorale: 3 }, bad: { captain: true, morale: 5, teamMorale: -6 } } },
      { fx: { flag: 'captainOffered', morale: -3 } },
    ],
    it: ['La fascia a {player}?', 'Lo spogliatoio si chiede chi debba portare la fascia. {player} non lo dice, ma ci spera.',
      ['Gli do la fascia', '{player} diventa il capitano che serviva: parla, trascina, protegge i giovani.', '{player} prende la fascia, ma i senatori non lo riconoscono come guida.'],
      ['Non cambio capitano', '{player} ci resta male, ma capisce.']],
    en: ['The armband for {player}?', 'The dressing room wonders who should wear the armband. {player} doesn’t say it, but he hopes.',
      ['Give him the armband', '{player} becomes the captain the team needed: he talks, drives, protects the youngsters.', '{player} takes the armband, but the senior players don’t accept him as their leader.'],
      ['No change of captain', '{player} is disappointed, but understands.']],
  },
  {
    id: 'pl_promise_minutes', cat: 'player', w: 7, repeat: 14,
    when: { mdMin: 3, player: { starter: false, rankMax: 18, ageMin: 20, moraleMax: 62, injured: false, personality: ['ambizioso', 'ribelle', 'leader', 'professionista'] } },
    o: [
      { fx: { morale: 14, bond: 6 }, promise: { type: 'starts', need: 3, within: 6 } },
      { odds: { base: 0.45, pers: { professionista: 0.3, leader: 0.1, ambizioso: -0.15, ribelle: -0.3 }, good: { morale: 6, attrs: { role: 1 } }, bad: { morale: -15, bond: -15 } } },
      { fx: { morale: -8, bond: -10, trust: 1 } },
    ],
    it: ['{player} bussa alla porta', '{player} entra nel tuo ufficio: gioca poco e vuole sapere che futuro ha in questa squadra.',
      ['Gli prometto tre partite da titolare nelle prossime sei', '{player} esce dall’ufficio con un altro passo. Ora però la promessa va mantenuta.'],
      ['Gli dico di guadagnarsi il posto in allenamento', '{player} raccoglie la sfida e in allenamento spinge come un matto.', '{player} sente solo un rifiuto e il suo umore precipita.'],
      ['Gli ricordo che decido io', 'La porta si chiude in fretta. La società apprezza la fermezza, lui molto meno.']],
    en: ['{player} knocks on the door', '{player} walks into your office: he’s barely playing and wants to know what future he has at this club.',
      ['Promise him three starts in the next six matches', '{player} leaves the office walking taller. Now the promise has to be kept.'],
      ['Tell him to earn his place in training', '{player} takes up the challenge and goes all out in training.', '{player} hears only a no, and his mood collapses.'],
      ['Remind him that I make the decisions', 'The door closes quickly. The board likes the firmness, he likes it far less.']],
  },
  {
    id: 'promise_kept', cat: 'player', w: 1, chainOnly: true,
    when: { player: {} },
    o: [{ fx: { morale: 15, bond: 18, attrs: { role: 1 }, form: 2 } }],
    it: ['Promessa mantenuta', 'Hai dato a {player} le partite promesse: {count} da titolare su {need}. Lui non lo dimentica.',
      ['Avanti così', '{player} ora si farebbe in quattro per te.']],
    en: ['Promise kept', 'You gave {player} the matches you promised: {count} starts out of {need}. He won’t forget it.',
      ['Carry on', '{player} would now run through walls for you.']],
  },
  {
    id: 'promise_broken', cat: 'player', w: 1, chainOnly: true,
    when: { player: {} },
    o: [
      { fx: { morale: -12, bond: -20, trust: -1 }, chain: { id: 'pl_transfer_request', in: 3 } },
      { odds: { base: 0.4, pers: { professionista: 0.25, leader: 0.1, ribelle: -0.25, ambizioso: -0.15 }, good: { morale: -4, bond: -5 }, bad: { morale: -20, bond: -30, teamMorale: -3 } } },
    ],
    it: ['Promessa tradita', 'Avevi promesso a {player} {need} partite da titolare. Ne ha giocate {count}. Lo spogliatoio ha visto tutto.',
      ['Non ho niente da dire', '{player} fa sapere al suo agente che vuole andare via.'],
      ['Gli chiedo scusa davanti a tutti', 'Le scuse pubbliche ricuciono in parte: {player} ti dà un’altra possibilità.', 'Le scuse arrivano tardi: {player} le prende come una presa in giro e lo spogliatoio si divide.']],
    en: ['A broken promise', 'You promised {player} {need} starts. He got {count}. The dressing room saw everything.',
      ['I have nothing to say', '{player} tells his agent he wants out.'],
      ['Apologise to him in front of everyone', 'The public apology mends things a little: {player} gives you another chance.', 'The apology comes too late: {player} takes it as mockery and the dressing room splits.']],
  },
  {
    id: 'pl_transfer_request', cat: 'market', w: 1, chainOnly: true,
    when: { player: {} },
    o: [
      { fx: { sell: 0.85, teamMorale: 1 } },
      { odds: { base: 0.35, pers: { professionista: 0.25, leader: 0.1, ribelle: -0.2 }, bond: 0.004, good: { morale: 10, bond: 10 }, bad: { morale: -15, form: -4, teamMorale: -4 } } },
      { fx: { loanOut: true, morale: 5 } },
    ],
    it: ['{player} chiede la cessione', 'Il procuratore di {player} ha presentato una richiesta formale di cessione. Valore stimato: {value} milioni.',
      ['Lo vendo al miglior offerente', '{player} parte. I soldi entrano in cassa, un problema esce dallo spogliatoio.'],
      ['Lo trattengo e provo a ricucire', 'Una cena, un chiarimento vero: {player} resta e torna dalla tua parte.', '{player} resta controvoglia e si vede: allenamenti svogliati, facce lunghe.'],
      ['Lo mando in prestito fino a fine stagione', '{player} va a giocare altrove. Tornerà, forse cresciuto.']],
    en: ['{player} asks to leave', '{player}’s agent has submitted a formal transfer request. Estimated value: {value} million.',
      ['Sell him to the highest bidder', '{player} leaves. Money comes in, a problem walks out of the dressing room.'],
      ['Keep him and try to patch things up', 'A dinner, a real heart-to-heart: {player} stays and is back on your side.', '{player} stays against his will and it shows: lazy sessions, long faces.'],
      ['Loan him out until the end of the season', '{player} goes to play elsewhere. He’ll be back, maybe better.']],
  },
  {
    id: 'pl_night_out', cat: 'private', w: 6, repeat: 12,
    when: { player: { ageMax: 30, personality: ['ribelle', 'pigro', 'ambizioso', 'fragile', 'leader'] } },
    o: [
      { fx: { morale: -10, bond: -6, suspended: 1, trust: 2, fans: 1 } },
      { fx: { morale: -4, fitness: -10, teamMorale: -1 } },
      { odds: { base: 0.5, pers: { leader: 0.2, ribelle: -0.2, pigro: -0.1 }, bond: 0.004, good: { bond: 14, morale: 6 }, bad: { form: -5, fitness: -15, trust: -4, fans: -3 } } },
    ],
    it: ['{player} in discoteca', 'Foto di {player} alle tre di notte in un locale, due giorni prima della partita. Sono già sui social.',
      ['Multa e fuori per una giornata', 'Il messaggio arriva a tutti: le regole valgono per chiunque.'],
      ['Multa, ma gioca', '{player} paga la multa. In campo però le gambe sono pesanti.'],
      ['Chiudo un occhio, ci parlo a quattr’occhi', 'Il gesto di fiducia lo conquista: da quel giorno non sgarra più.', '{player} ci ricasca la settimana dopo e stavolta lo scoprono tutti.']],
    en: ['{player} out clubbing', 'Photos of {player} at three in the morning in a club, two days before the match. They’re already all over social media.',
      ['Fine him and drop him for a match', 'The message reaches everyone: rules apply to all.'],
      ['Fine him, but he plays', '{player} pays the fine. On the pitch, though, his legs are heavy.'],
      ['Turn a blind eye, talk to him privately', 'The show of trust wins him over: he never steps out of line again.', '{player} does it again the next week, and this time everyone finds out.']],
  },
  {
    id: 'pl_play_hurt', cat: 'medical', w: 6, repeat: 12,
    when: { mdMin: 2, player: { rankMax: 6, injured: true } },
    o: [
      { odds: { base: 0.45, pers: { professionista: 0.1, fragile: -0.25 }, good: { injury: -9, form: 2, bond: 6 }, bad: { injury: 6, injuryProne: 12, attrs: { pace: -3, stamina: -2 }, morale: -8 } } },
      { fx: { bond: 3 } },
    ],
    it: ['Infiltrazione per {player}?', '{player} è infortunato ma chiede di giocare con un’infiltrazione. Il medico non è convinto.',
      ['Lo faccio giocare', '{player} stringe i denti e regge: una partita da guerriero.', 'Il dolore peggiora in campo: ora lo stop sarà molto più lungo.'],
      ['Aspettiamo che guarisca', 'Il medico approva. {player} scalpita, ma recupera senza rischi.']],
    en: ['An injection for {player}?', '{player} is injured but wants to play with a painkilling injection. The doctor isn’t convinced.',
      ['Let him play', '{player} grits his teeth and holds up: a warrior’s performance.', 'The pain worsens on the pitch: now he’ll be out much longer.'],
      ['Wait until he’s healed', 'The doctor approves. {player} is restless, but recovers without risk.']],
  },
  {
    id: 'pl_young_debut', cat: 'youth', w: 6, repeat: 10,
    when: { player: { ageMax: 19, appsMax: 1, injured: false } },
    o: [
      { odds: { base: 0.55, pers: { professionista: 0.15, ambizioso: 0.15, fragile: -0.25 }, good: { potential: 4, attrs: { role: 2 }, morale: 15, bond: 12, promiseStarts: { need: 1, within: 3 } }, bad: { morale: -14, potential: -2, form: -4 } } },
      { fx: { potential: 1, morale: -3 } },
    ],
    it: ['L’esordio di {player}', '{player} ha diciotto anni e in allenamento incanta. Lo staff dice che è pronto per l’esordio.',
      ['Lo lancio titolare', '{player} gioca con la faccia tosta dei grandi. Nasce una stella?', 'La pressione lo schiaccia: sbaglia tutto e esce in lacrime.'],
      ['Aspetto, deve crescere con calma', '{player} continua a lavorare lontano dai riflettori.']],
    en: ['{player}’s debut', '{player} is eighteen and dazzling in training. The staff say he’s ready for his debut.',
      ['Throw him in from the start', '{player} plays with the nerve of a veteran. Is a star being born?', 'The pressure crushes him: he gets everything wrong and leaves in tears.'],
      ['Wait, he needs to grow calmly', '{player} keeps working away from the spotlight.']],
  },
  {
    id: 'pl_renewal_star', cat: 'market', w: 7, repeat: 30,
    when: { player: { rankMax: 7, contractLeft: 1, ageMax: 31, noFlag: 'renewed' } },
    o: [
      { fx: { renew: 4, raise: 0.35, morale: 12, bond: 8, budgetPct: -0.05 } },
      { odds: { base: 0.45, pers: { professionista: 0.15, leader: 0.15, ambizioso: -0.25 }, bond: 0.005, good: { renew: 3, raise: 0.1, morale: 6 }, bad: { morale: -15, noRenew: true, form: -2 } } },
      { fx: { noRenew: true, morale: -10, trust: 2 } },
    ],
    it: ['Il rinnovo di {player}', 'Il contratto di {player} scade a fine stagione. Il suo agente chiede un aumento importante.',
      ['Accontento tutte le richieste', 'Firma fino a quattro anni: {player} è il volto del progetto.'],
      ['Offro un rinnovo al ribasso', '{player} accetta: vuole restare più dei soldi.', '{player} si sente sottovalutato: andrà via a parametro zero.'],
      ['Lo lascio andare a scadenza', 'La società risparmia, ma a giugno {player} saluterà.']],
    en: ['{player}’s new contract', '{player}’s contract expires at the end of the season. His agent wants a big raise.',
      ['Meet all his demands', 'He signs for four years: {player} is the face of the project.'],
      ['Offer a cheaper deal', '{player} accepts: he wants to stay more than he wants the money.', '{player} feels undervalued: he’ll leave on a free.'],
      ['Let his contract run down', 'The club saves money, but in June {player} will say goodbye.']],
  },
  {
    id: 'pl_renewal_veteran', cat: 'market', w: 5, repeat: 30,
    when: { player: { ageMin: 31, contractLeft: 1, noFlag: 'renewed' } },
    o: [
      { fx: { renew: 1, raise: 0, morale: 10, bond: 10, teamMorale: 2 } },
      { fx: { renew: 2, raise: 0.1, morale: 8 } },
      { fx: { noRenew: true, morale: -6, trust: 1 } },
    ],
    it: ['Un altro anno per {player}?', '{player} è uno dei veterani. Vorrebbe chiudere la carriera qui, con un contratto di un anno.',
      ['Un anno, alle stesse cifre', '{player} ringrazia commosso: lo spogliatoio apprezza il rispetto per i senatori.'],
      ['Due anni e un piccolo aumento', '{player} firma felice. La società storce un po’ il naso.'],
      ['È ora di separarsi', 'A fine stagione {player} lascerà il club.']],
    en: ['Another year for {player}?', '{player} is one of the veterans. He’d like to finish his career here, with a one-year deal.',
      ['One year, same terms', '{player} thanks you, moved: the dressing room appreciates the respect shown to veterans.'],
      ['Two years and a small raise', '{player} signs happily. The board frowns a little.'],
      ['Time to part ways', 'At the end of the season {player} will leave the club.']],
  },
  {
    id: 'pl_diet_program', cat: 'staff', w: 5, repeat: 20,
    when: { player: { ageMin: 26, personality: ['pigro', 'ribelle', 'professionista', 'ambizioso'] } },
    o: [
      { odds: { base: 0.55, pers: { professionista: 0.25, pigro: -0.3, ribelle: -0.15 }, good: { attrs: { stamina: 4, pace: 2, strength: 2 }, injuryProne: -10, bond: 4 }, bad: { morale: -10, bond: -6 } } },
      { fx: {} },
    ],
    it: ['Nutrizionista per {player}', 'Il nutrizionista dice che {player} ha qualche chilo di troppo e propone una dieta rigida con lavoro atletico.',
      ['Dieta e lavoro atletico', 'Due mesi dopo {player} vola: più resistenza, meno acciacchi.', '{player} odia la dieta e smette di seguirla. E ce l’ha con te.'],
      ['Lasciamolo tranquillo', 'Nessun cambio nella routine di {player}.']],
    en: ['A nutritionist for {player}', 'The nutritionist says {player} is carrying a few extra kilos and proposes a strict diet with conditioning work.',
      ['Diet and conditioning', 'Two months later {player} is flying: more stamina, fewer knocks.', '{player} hates the diet and stops following it. And he blames you.'],
      ['Leave him be', 'No change to {player}’s routine.']],
  },
  {
    id: 'pl_psychologist', cat: 'staff', w: 5, repeat: 20,
    when: { player: { moraleMax: 45 } },
    o: [
      { odds: { base: 0.6, pers: { fragile: 0.1, ribelle: -0.25, leader: -0.05 }, good: { morale: 25, attrs: { composure: 4 }, consistency: 10 }, bad: { morale: -5, bond: -5 } } },
      { fx: { morale: 8, bond: 8 } },
      { fx: { form: -2, trust: 1 } },
    ],
    it: ['{player} non è sereno', '{player} è giù di morale da settimane. In allenamento sbaglia cose semplici e si isola.',
      ['Lo affido al mental coach', 'Qualche seduta e {player} ritrova la testa: più freddo nei momenti che contano.', '{player} vive il mental coach come una bocciatura.'],
      ['Ci parlo io, da uomo a uomo', 'Un’ora di chiacchierata: {player} esce sollevato.'],
      ['Deve reagire da solo', 'La società approva la linea dura. {player} continua a faticare.']],
    en: ['{player} is not in a good place', '{player} has been down for weeks. In training he gets simple things wrong and keeps to himself.',
      ['Send him to the mental coach', 'A few sessions and {player} gets his head back: calmer in the moments that matter.', '{player} sees the mental coach as a vote of no confidence.'],
      ['I’ll talk to him, man to man', 'An hour-long chat: {player} walks out relieved.'],
      ['He has to react on his own', 'The board likes the tough line. {player} keeps struggling.']],
  },
  {
    id: 'pl_free_kick_specialist', cat: 'player', w: 4, repeat: 40,
    when: { player: { depts: ['CEN', 'ATT', 'DIF'], ageMax: 29 } },
    o: [
      { odds: { base: 0.58, pers: { professionista: 0.2, pigro: -0.25 }, good: { attrs: { technique: 4, longshots: 5 } }, bad: { attrs: { technique: 1 }, fitness: -12, injury: 1 } } },
      { fx: {} },
    ],
    it: ['Cento punizioni al giorno', '{player} resta dopo l’allenamento a calciare punizioni. Chiede di avere un preparatore dedicato.',
      ['Gli metto a disposizione uno specialista', '{player} affina il piede: ora la punizione dal limite è un’arma.', 'Troppi tiri, troppa fatica: {player} si ferma per un affaticamento all’adduttore.'],
      ['No, prima la squadra', '{player} torna al lavoro di gruppo.']],
    en: ['A hundred free kicks a day', '{player} stays after training to practise free kicks. He asks for a dedicated coach.',
      ['Give him a specialist', '{player} sharpens his technique: a free kick on the edge is now a weapon.', 'Too many kicks, too much strain: {player} is out with an adductor problem.'],
      ['No, the team comes first', '{player} goes back to group training.']],
  },
  {
    id: 'pl_agent_rumours', cat: 'market', w: 6, repeat: 15,
    when: { player: { rankMax: 5, ageMax: 30 } },
    o: [
      { odds: { base: 0.55, bond: 0.006, pers: { leader: 0.15, professionista: 0.1, ambizioso: -0.25 }, good: { morale: 8, bond: 10 }, bad: { morale: -10, form: -3 } }, chain: { id: 'pl_transfer_request', in: 4 }, chainOn: 'bad' },
      { fx: { trust: 3, morale: -6, bond: -6 } },
      { fx: { morale: 4, fans: 3 } },
    ],
    it: ['Le sirene per {player}', 'Il procuratore di {player} fa circolare voci di un grande club interessato. Valore stimato: {value} milioni.',
      ['Lo chiamo e gli chiedo di restare concentrato', '{player} ti assicura che vuole restare: la voce svanisce.', '{player} tentenna: la testa è già altrove.'],
      ['Lascio la questione alla società', 'La società fa muro. {player} non la prende benissimo.'],
      ['Dichiaro che è incedibile', 'I tifosi esultano e {player} apprezza la presa di posizione.']],
    en: ['Big clubs circling {player}', '{player}’s agent is spreading rumours about a big club’s interest. Estimated value: {value} million.',
      ['Call him and ask him to stay focused', '{player} assures you he wants to stay: the rumour fades.', '{player} wavers: his head is already elsewhere.'],
      ['Leave it to the board', 'The board digs in. {player} doesn’t take it too well.'],
      ['Declare him untouchable', 'The fans cheer and {player} appreciates the stance.']],
  },
  {
    id: 'pl_big_offer', cat: 'market', w: 5, repeat: 25,
    when: { window: true, player: { rankMax: 3, ageMax: 30 } },
    o: [
      { fx: { sell: 1.3, fans: -8, teamMorale: -3, trust: 4 } },
      { fx: { morale: -8, bond: 4, fans: 4, trust: -2 } },
      { odds: { base: 0.5, pers: { leader: 0.15, professionista: 0.1, ambizioso: -0.2 }, good: { renew: 4, raise: 0.25, morale: 10 }, bad: { morale: -18, form: -4 } } },
    ],
    it: ['Offerta monstre per {player}', 'Un top club offre il 30% in più del valore di {player} ({value} milioni). La società lascia a te l’ultima parola.',
      ['Vendo: sono troppi soldi', '{player} parte, la cassa si riempie. I tifosi però non la prendono bene.'],
      ['Rifiuto: non si vende', '{player} avrebbe voluto parlarne. La piazza invece ti ama.'],
      ['Rifiuto e offro il rinnovo', '{player} firma a vita e diventa bandiera.', '{player} voleva andare e il rinnovo non basta: è furioso.']],
    en: ['A huge offer for {player}', 'A top club offers 30% above {player}’s value ({value} million). The board leaves the final word to you.',
      ['Sell: it’s too much money', '{player} leaves, the coffers fill up. The fans don’t take it well.'],
      ['Refuse: he’s not for sale', '{player} would have liked to discuss it. The fans, though, love you.'],
      ['Refuse and offer a new contract', '{player} signs long term and becomes a club icon.', '{player} wanted to go and the new deal isn’t enough: he’s furious.']],
  },
  {
    id: 'pl_loan_youngster', cat: 'youth', w: 6, repeat: 20,
    when: { player: { ageMax: 21, appsMax: 3, potentialGap: 6, starter: false } },
    o: [
      { odds: { base: 0.6, pers: { professionista: 0.15, ambizioso: 0.15, pigro: -0.2 }, good: { loanOut: true, potential: 5 }, bad: { loanOut: true, potential: -3, morale: -10 } } },
      { fx: { potential: 1, morale: -4 } },
      { fx: { promiseStarts: { need: 2, within: 6 }, morale: 12 } },
    ],
    it: ['{player} in prestito?', 'Un club di categoria inferiore chiede {player} in prestito: gli garantiscono il posto da titolare.',
      ['Lo mando a giocare', 'Ottima scelta: {player} gioca ogni domenica e cresce a vista d’occhio.', 'Il prestito si rivela un disastro: panchina e un allenatore che non lo vede.'],
      ['Resta qui ad allenarsi con i grandi', '{player} resta, ma di minuti ne vedrà pochi.'],
      ['Resta e gli prometto spazio', '{player} è entusiasta. Ora gli servono davvero due partite da titolare.']],
    en: ['{player} out on loan?', 'A lower-division club wants {player} on loan and guarantees him a starting place.',
      ['Send him out to play', 'Great call: {player} plays every weekend and grows before your eyes.', 'The loan is a disaster: the bench and a coach who doesn’t rate him.'],
      ['He stays and trains with the first team', '{player} stays, but he won’t see many minutes.'],
      ['He stays and I promise him chances', '{player} is thrilled. Now he really needs two starts.']],
  },
  {
    id: 'pl_hothead', cat: 'dressing', w: 5, repeat: 15,
    when: { player: { personality: ['ribelle'], ageMax: 32 } },
    o: [
      { fx: { suspended: 2, morale: -14, bond: -10, teamMorale: 3, trust: 2 } },
      { odds: { base: 0.45, bond: 0.005, good: { bond: 12, morale: 8, consistency: 8 }, bad: { teamMorale: -6, bond: -4 } } },
      { fx: { sell: 0.75, teamMorale: 2 } },
    ],
    it: ['Rissa in allenamento', '{player} è venuto alle mani con un compagno durante la partitella. Lo spogliatoio aspetta la tua reazione.',
      ['Fuori rosa per due partite', 'Pugno duro: il gruppo apprezza, {player} molto meno.'],
      ['Li chiudo in una stanza finché non chiariscono', 'Escono abbracciati: la lite diventa un’amicizia.', 'Escono ancora più arrabbiati e lo spogliatoio si divide in due.'],
      ['Lo metto sul mercato', '{player} viene ceduto: via il problema, e un po’ di qualità.']],
    en: ['Fight in training', '{player} came to blows with a teammate during a practice match. The dressing room waits for your reaction.',
      ['Banished from the squad for two matches', 'An iron fist: the group approves, {player} much less.'],
      ['Lock them in a room until they sort it out', 'They come out hugging: the fight becomes a friendship.', 'They come out even angrier and the dressing room splits in two.'],
      ['Put him on the market', '{player} is sold: the problem is gone, and some quality with it.']],
  },
  {
    id: 'pl_hat_trick_hero', cat: 'press', w: 5, repeat: 10,
    when: { mdMin: 2, last: 'W', player: { goalsMin: 2, avgMin: 7 } },
    o: [
      { odds: { base: 0.55, pers: { professionista: 0.2, fragile: -0.1, ambizioso: -0.1, pigro: -0.15 }, good: { morale: 10, form: 3 }, bad: { form: -3, consistency: -6 } } },
      { fx: { morale: 4, bond: 6, form: 1 } },
    ],
    it: ['Tutti pazzi per {player}', '{player} è l’uomo del momento: prime pagine, interviste, pubblicità. Lo lasci sotto i riflettori?',
      ['Sì, se lo merita', '{player} si gode il momento e continua a segnare.', 'Troppa esposizione: {player} si distrae e si spegne.'],
      ['Silenzio stampa per lui', '{player} capisce: testa bassa e lavorare.']],
    en: ['Everyone’s crazy about {player}', '{player} is the man of the moment: front pages, interviews, ads. Do you leave him in the spotlight?',
      ['Yes, he’s earned it', '{player} enjoys the moment and keeps scoring.', 'Too much exposure: {player} loses focus and fades.'],
      ['Media blackout for him', '{player} understands: head down and work.']],
  },
  {
    id: 'pl_veteran_mentor', cat: 'dressing', w: 5, repeat: 25,
    when: { player: { ageMin: 30, personality: ['leader', 'professionista'] } },
    o: [
      { fx: { youngsters: { potential: 2, morale: 4 }, bond: 8, fitness: -5 } },
      { fx: { attrs: { role: 1 }, morale: 4 } },
    ],
    it: ['{player} fa da chioccia', '{player} si offre di seguire i ragazzi più giovani dopo gli allenamenti. Lo staff è d’accordo.',
      ['Sì, affido a lui i giovani', 'I ragazzi pendono dalle labbra di {player}: crescono più in fretta.'],
      ['Preferisco che pensi a sé', '{player} si concentra sul proprio lavoro e ne guadagna.']],
    en: ['{player} takes the youngsters under his wing', '{player} offers to mentor the youngest players after training. The staff agree.',
      ['Yes, he looks after the kids', 'The youngsters hang on {player}’s every word: they develop faster.'],
      ['I’d rather he focuses on himself', '{player} concentrates on his own work and benefits from it.']],
  },
  {
    id: 'pl_homesick', cat: 'private', w: 5, repeat: 25,
    when: { player: { foreign: true, ageMax: 25, moraleMax: 60 } },
    o: [
      { fx: { morale: 14, bond: 8, fitness: -6 } },
      { odds: { base: 0.5, pers: { professionista: 0.2, fragile: -0.25 }, good: { morale: 8 }, bad: { morale: -12, form: -4 } } },
      { fx: { morale: 10, teamMorale: 1, budget: -0.2 } },
    ],
    it: ['Nostalgia di casa', '{player} fatica ad ambientarsi: lontano dalla famiglia, lingua nuova, pochi amici.',
      ['Tre giorni a casa', '{player} torna rigenerato, anche se ha perso qualche allenamento.'],
      ['Deve abituarsi, fa parte del mestiere', '{player} si rimbocca le maniche e ce la fa.', '{player} si chiude ancora di più e in campo si vede.'],
      ['Il club gli paga un insegnante e un tutor', 'Piccoli gesti che fanno la differenza: {player} si sente a casa.']],
    en: ['Homesick', '{player} is struggling to settle: far from family, a new language, few friends.',
      ['Three days back home', '{player} returns refreshed, even if he missed a few sessions.'],
      ['He has to get used to it, it’s part of the job', '{player} rolls up his sleeves and makes it.', '{player} withdraws even more and it shows on the pitch.'],
      ['The club pays for a teacher and a tutor', 'Small gestures that make a difference: {player} feels at home.']],
  },
  {
    id: 'pl_contract_clause', cat: 'market', w: 4, repeat: 30,
    when: { player: { rankMax: 4, ageMax: 26, potentialGap: 3 } },
    o: [
      { fx: { renew: 5, raise: 0.3, morale: 10, budgetPct: -0.06 } },
      { fx: { morale: -6 } },
    ],
    it: ['Blindare {player}', 'Diversi club osservano {player}. La società propone di blindarlo con un contratto lungo e una clausola alta.',
      ['Contratto di cinque anni', '{player} firma e ringrazia. È il futuro del club.'],
      ['Non ora, vediamo come cresce', '{player} si aspettava più considerazione.']],
    en: ['Tying down {player}', 'Several clubs are watching {player}. The board suggests tying him down with a long contract and a high release clause.',
      ['Five-year contract', '{player} signs and thanks you. He’s the club’s future.'],
      ['Not now, let’s see how he develops', '{player} expected more consideration.']],
  },
  {
    id: 'pl_style_misfit', cat: 'style', w: 5, repeat: 20,
    when: { mdMin: 3, player: { rankMax: 6 } },
    o: [
      { odds: { base: 0.5, pers: { professionista: 0.25, ribelle: -0.25, pigro: -0.15 }, good: { attrs: { role: 1, stamina: 2 }, morale: 5 }, bad: { morale: -12, form: -3 } } },
      { fx: { morale: 6, familiarity: -3 } },
      { fx: { morale: -4, bond: -4, teamMorale: 1 } },
    ],
    it: ['{player} e il tuo calcio', '{player} fatica dentro il tuo stile di gioco e te lo dice chiaramente: così non rende.',
      ['Lo convinco a lavorare per adattarsi', '{player} ci mette tutto: ora sembra nato per questo calcio.', '{player} non si ritrova e la frustrazione cresce.'],
      ['Cambio qualcosa per lui', '{player} rinasce, ma la squadra perde un po’ di automatismi.'],
      ['È lui che si adegua, non il gioco', 'Il gruppo apprezza la coerenza. {player} no.']],
    en: ['{player} and your football', '{player} is struggling in your playing style and tells you plainly: he can’t perform like this.',
      ['Convince him to work on adapting', '{player} gives it everything: now he looks made for this football.', '{player} can’t find his feet and frustration grows.'],
      ['Change something for him', '{player} comes alive, but the team loses some of its automatisms.'],
      ['He adapts, not the system', 'The group respects the consistency. {player} doesn’t.']],
  },
  {
    id: 'pl_penalty_argument', cat: 'dressing', w: 4, repeat: 20,
    when: { mdMin: 3, player: { depts: ['ATT', 'CEN'], rankMax: 6 } },
    o: [
      { odds: { base: 0.55, pers: { leader: 0.2, fragile: -0.2 }, good: { penalties: true, morale: 10, attrs: { composure: 2 } }, bad: { penalties: true, morale: -6, teamMorale: -3 } } },
      { fx: { morale: -8, teamMorale: 2 } },
    ],
    it: ['Chi tira i rigori?', '{player} vuole diventare il rigorista e lo fa sapere a tutti, anche a chi li tira oggi.',
      ['Gli do i rigori', '{player} si prende la responsabilità e non trema.', 'La scelta crea malumori con l’ex rigorista.'],
      ['Le gerarchie non cambiano', '{player} abbozza. Il gruppo apprezza che le regole restino quelle.']],
    en: ['Who takes the penalties?', '{player} wants to be the penalty taker and makes sure everyone knows it, including the current taker.',
      ['He takes the penalties', '{player} takes responsibility and doesn’t flinch.', 'The decision causes friction with the former taker.'],
      ['The pecking order stays', '{player} goes along with it. The group likes that the rules stay the same.']],
  },
  {
    id: 'pl_charity', cat: 'private', w: 4, repeat: 40,
    when: { player: { ageMin: 23 } },
    o: [
      { fx: { fans: 5, morale: 8, fitness: -4, reputation: 1 } },
      { fx: { morale: -3 } },
    ],
    it: ['{player} e la beneficenza', '{player} vuole partecipare a un evento benefico nell’ospedale pediatrico della città, il giorno prima di un allenamento importante.',
      ['Vai, è più importante', 'Le foto fanno il giro della città: tifosi commossi e {player} felice.'],
      ['Meglio dopo la partita', '{player} rimanda, un po’ deluso.']],
    en: ['{player} and charity', '{player} wants to attend a charity event at the city’s children’s hospital, the day before an important training session.',
      ['Go, this matters more', 'The photos go around the city: fans are moved and {player} is happy.'],
      ['Better after the match', '{player} postpones, a little disappointed.']],
  },
  {
    id: 'pl_social_post', cat: 'press', w: 5, repeat: 15,
    when: { last: 'L', player: { ageMax: 28, starter: false } },
    o: [
      { fx: { suspended: 1, morale: -10, teamMorale: 2, trust: 2 } },
      { odds: { base: 0.5, bond: 0.004, pers: { ribelle: -0.2, professionista: 0.15 }, good: { morale: 6, bond: 8 }, bad: { teamMorale: -4, fans: -3 } } },
      { fx: { morale: -2, fans: -2 } },
    ],
    it: ['Il post di {player}', 'Dopo la sconfitta {player} pubblica una storia polemica: «Chi gioca non merita, chi merita non gioca».',
      ['Squalifica interna di una giornata', 'Lo spogliatoio capisce che certe cose non si fanno.'],
      ['Ne parliamo in privato', '{player} cancella il post e si scusa con i compagni.', 'Il chiarimento non basta: il post diventa un caso nazionale.'],
      ['Faccio finta di niente', 'La polemica si sgonfia, ma i tifosi mugugnano.']],
    en: ['{player}’s post', 'After the defeat {player} posts a pointed story: “Those who play don’t deserve it, those who deserve it don’t play”.',
      ['Internal one-match ban', 'The dressing room understands some things are not done.'],
      ['We talk in private', '{player} deletes the post and apologises to his teammates.', 'The talk isn’t enough: the post becomes a national story.'],
      ['Pretend nothing happened', 'The row blows over, but the fans grumble.']],
  },
  {
    id: 'pl_injury_prone_plan', cat: 'medical', w: 5, repeat: 30,
    when: { injuredMin: 1, player: { rankMax: 10 } },
    o: [
      { fx: { injuryProne: -18, fitness: -10, budget: -0.4 } },
      { fx: { injuryProne: 5 } },
    ],
    it: ['Prevenzione per {player}', 'Lo staff medico teme che il fisico di {player} sia a rischio e propone un piano di prevenzione con carichi ridotti.',
      ['Piano di prevenzione', 'Qualche settimana a ritmo ridotto, ma {player} ora rischia molto meno.'],
      ['Nessun piano, serve in campo', '{player} continua a pieno ritmo. Speriamo regga.']],
    en: ['Prevention plan for {player}', 'The medical staff fear {player}’s body is at risk and propose a prevention plan with reduced workloads.',
      ['Prevention plan', 'A few weeks at reduced pace, but {player} is now at much lower risk.'],
      ['No plan, we need him on the pitch', '{player} carries on at full tilt. Let’s hope he holds up.']],
  },
  {
    id: 'pl_comeback_slow', cat: 'medical', w: 4, repeat: 20,
    when: { player: { injured: true, rankMax: 12 } },
    o: [
      { odds: { base: 0.5, pers: { professionista: 0.15, fragile: -0.2 }, good: { injury: -6, attrs: { role: 1 } }, bad: { injury: 4, attrs: { pace: -2 } } } },
      { fx: { injuryProne: -6, morale: -3 } },
    ],
    it: ['Il rientro di {player}', 'Uno specialista all’estero propone una terapia sperimentale per accelerare il recupero di {player}.',
      ['Proviamo la terapia', 'Funziona: {player} rientra prima del previsto e più forte.', 'La terapia non va: il recupero si allunga.'],
      ['Tempi normali, nessun rischio', '{player} recupera con calma e torna senza strascichi.']],
    en: ['{player}’s return', 'A specialist abroad proposes an experimental therapy to speed up {player}’s recovery.',
      ['Try the therapy', 'It works: {player} returns ahead of schedule and stronger.', 'The therapy fails: recovery takes longer.'],
      ['Normal timings, no risks', '{player} recovers calmly and returns without after-effects.']],
  },
  {
    id: 'pl_role_model_kid', cat: 'youth', w: 4, repeat: 30,
    when: { player: { ageMax: 20, potentialGap: 8 } },
    o: [
      { fx: { potential: 3, morale: 10, bond: 10, teamMorale: -1 } },
      { fx: { morale: 2 } },
    ],
    it: ['Un talento da proteggere', 'Gli osservatori dicono che {player} ha il potenziale per diventare un campione. Vuoi dargli un programma personale?',
      ['Programma personale e allenamenti con la prima squadra', '{player} cresce protetto e motivato. Qualche senatore storce il naso.'],
      ['Nessun trattamento speciale', '{player} segue il percorso di tutti.']],
    en: ['A talent to protect', 'The scouts say {player} has the potential to become a star. Do you give him a personal programme?',
      ['Personal programme and first-team training', '{player} grows protected and motivated. A few senior players frown.'],
      ['No special treatment', '{player} follows the same path as everyone else.']],
  },
  {
    id: 'pl_drop_in_form', cat: 'player', w: 6, repeat: 12,
    when: { mdMin: 5, player: { formMax: -4, starter: true } },
    o: [
      { fx: { form: 3, fitness: 15, morale: -3 } },
      { odds: { base: 0.5, pers: { leader: 0.15, professionista: 0.15, fragile: -0.2 }, good: { form: 5, morale: 6 }, bad: { form: -3, morale: -8 } } },
    ],
    it: ['{player} non gira', '{player} è in un periodo nero: gambe pesanti, scelte sbagliate. Lo staff atletico consiglia riposo.',
      ['Una settimana di riposo', '{player} ricarica le batterie, anche se non la prende benissimo.'],
      ['Continua a giocare, si esce giocando', '{player} si sblocca con una grande prestazione.', '{player} affonda ancora di più.']],
    en: ['{player} isn’t clicking', '{player} is in a bad spell: heavy legs, wrong choices. The fitness staff recommend rest.',
      ['A week of rest', '{player} recharges his batteries, even if he doesn’t take it too well.'],
      ['Keep playing him, you play your way out of it', '{player} breaks out of it with a great performance.', '{player} sinks even deeper.']],
  },
  {
    id: 'pl_on_fire_rest', cat: 'player', w: 5, repeat: 12,
    when: { mdMin: 6, player: { formMin: 5, fitnessMax: 75 } },
    o: [
      { fx: { fitness: 18, form: -2 } },
      { odds: { base: 0.55, pers: { professionista: 0.1, fragile: -0.2 }, age: -0.015, good: { form: 2, morale: 4 }, bad: { injury: 3, injuryProne: 6 } } },
    ],
    it: ['{player} è on fire, ma è stanco', '{player} sta giocando il miglior calcio della sua carriera, ma i dati atletici dicono che è in riserva.',
      ['Riposa una partita', '{player} rifiata. Speriamo di non aver spezzato il momento magico.'],
      ['Chi vince non si cambia', '{player} continua a trascinare la squadra.', 'Il fisico presenta il conto: stiramento.']],
    en: ['{player} is on fire, but tired', '{player} is playing the best football of his career, but the fitness data say he’s running on fumes.',
      ['Rest him for a match', '{player} catches his breath. Let’s hope the magic spell isn’t broken.'],
      ['Never change a winning team', '{player} keeps carrying the team.', 'His body sends the bill: a strain.']],
  },
  {
    id: 'pl_national_callup', cat: 'national', w: 5, repeat: 20,
    when: { player: { rankMax: 6, ageMin: 21, ageMax: 31 } },
    o: [
      { odds: { base: 0.6, good: { morale: 12, attrs: { composure: 2 }, fitness: -10 }, bad: { injury: 3, morale: 5 } } },
      { fx: { morale: -12, bond: -8, fitness: 10 } },
    ],
    it: ['Convocato in nazionale', '{player} riceve la chiamata della nazionale per le amichevoli. Ma arriva da un periodo stancante.',
      ['Vai, è un onore', '{player} torna dalla nazionale carico e più maturo.', 'In nazionale si fa male: tornerà tra qualche settimana.'],
      ['Chiedo di lasciarlo a riposo', '{player} resta a casa, ma è furioso per l’occasione persa.']],
    en: ['National team call-up', '{player} is called up for international friendlies. But he’s coming off a tiring spell.',
      ['Go, it’s an honour', '{player} returns from international duty fired up and more mature.', 'He gets injured on international duty: he’ll be back in a few weeks.'],
      ['Ask for him to be rested', '{player} stays home, but is furious about the missed chance.']],
  },
  {
    id: 'pl_wants_new_role', cat: 'player', w: 4, repeat: 40,
    when: { player: { roles: ['CC'], ageMax: 28, rankMax: 10 } },
    o: [
      { odds: { base: 0.5, pers: { ambizioso: 0.15, professionista: 0.1, pigro: -0.2 }, good: { newRole: 'TRQ', attrs: { vision: 4, dribbling: 3, finishing: 2 }, morale: 8 }, bad: { newRole: 'TRQ', morale: -6, form: -3 } } },
      { odds: { base: 0.5, pers: { professionista: 0.2, ribelle: -0.2 }, good: { newRole: 'MED', attrs: { tackling: 4, positioning: 3 }, morale: 4 }, bad: { newRole: 'MED', morale: -10 } } },
      { fx: { morale: -4 } },
    ],
    it: ['{player} vuole cambiare', '{player} si sente sprecato da centrocampista puro e chiede un ruolo diverso.',
      ['Trequartista, dietro le punte', '{player} si scatena fra le linee: assist e gol.', 'Fra le linee {player} non trova spazi e si innervosisce.'],
      ['Mediano, a proteggere la difesa', '{player} scopre di saper recuperare palloni come pochi.', '{player} odia il lavoro sporco davanti alla difesa.'],
      ['Resta dov’è', '{player} continua da centrocampista, un po’ deluso.']],
    en: ['{player} wants a change', '{player} feels wasted as a pure central midfielder and asks for a different role.',
      ['Attacking midfielder, behind the strikers', '{player} runs riot between the lines: assists and goals.', 'Between the lines {player} can’t find space and gets frustrated.'],
      ['Holding midfielder, shielding the defence', '{player} finds he can win the ball back like few others.', '{player} hates the dirty work in front of the defence.'],
      ['He stays where he is', '{player} carries on in central midfield, a bit disappointed.']],
  },
  {
    id: 'pl_keeper_confidence', cat: 'player', w: 5, repeat: 15,
    when: { mdMin: 3, player: { roles: ['POR'], starter: true, avgMax: 6.3 } },
    o: [
      { odds: { base: 0.5, pers: { fragile: -0.25, professionista: 0.15 }, good: { form: 3, attrs: { reflexes: 2 } }, bad: { morale: -15, form: -4 } } },
      { odds: { base: 0.5, pers: { leader: 0.1, fragile: 0.1 }, good: { morale: 10, attrs: { composure: 3 } }, bad: { form: -2 } } },
    ],
    it: ['Il portiere trema', '{player} ha commesso qualche errore di troppo. La porta è il ruolo dove la fiducia pesa di più.',
      ['Panchina: tocca al secondo', 'La scossa funziona: quando torna, {player} è concentratissimo.', '{player} perde completamente la sicurezza.'],
      ['Lo confermo pubblicamente', '{player} si sente protetto e torna a parare tutto.', 'La fiducia non basta: arrivano altri errori.']],
    en: ['The keeper is shaking', '{player} has made one error too many. In goal, confidence matters more than anywhere.',
      ['Bench: the number two plays', 'The jolt works: when he returns, {player} is fully focused.', '{player} loses all his confidence.'],
      ['Back him publicly', '{player} feels protected and starts saving everything again.', 'Trust isn’t enough: more errors follow.']],
  },
  {
    id: 'pl_winger_defend', cat: 'style', w: 4, repeat: 25,
    when: { player: { roles: ['ALA', 'PUN', 'TRQ'], rankMax: 6, personality: ['pigro', 'ribelle', 'ambizioso'] } },
    o: [
      { odds: { base: 0.45, pers: { pigro: -0.2, ambizioso: 0.1 }, good: { attrs: { stamina: 3, tackling: 3 }, morale: 4 }, bad: { morale: -12, bond: -8 } } },
      { fx: { morale: 8, teamMorale: -3 } },
    ],
    it: ['{player} non torna in difesa', 'I compagni si lamentano: {player} non rientra mai a difendere e loro corrono per due.',
      ['Gli impongo i ripiegamenti', '{player} capisce e diventa un attaccante completo.', '{player} lo vive come un tradimento del suo talento.'],
      ['Lo lascio libero di attaccare', '{player} è felice. Gli altri molto meno.']],
    en: ['{player} doesn’t track back', 'His teammates complain: {player} never comes back to defend and they have to run for two.',
      ['Force him to track back', '{player} understands and becomes a complete forward.', '{player} sees it as a betrayal of his talent.'],
      ['Let him roam free', '{player} is happy. The others much less so.']],
  },
  {
    id: 'pl_tattoo_ad', cat: 'private', w: 3, repeat: 40,
    when: { player: { rankMax: 6 } },
    o: [
      { fx: { morale: 6, budget: 0.5, fitness: -6 } },
      { fx: { morale: -5, trust: 1 } },
    ],
    it: ['Lo spot di {player}', 'Un marchio sportivo vuole {player} per uno spot: due giorni di riprese durante la settimana di campionato. Al club va una percentuale.',
      ['Autorizzo', '{player} gira lo spot e il club incassa. Qualche allenamento saltato.'],
      ['Non durante la stagione', '{player} rinuncia a malincuore.']],
    en: ['{player}’s commercial', 'A sportswear brand wants {player} for a commercial: two days of filming during a league week. The club gets a cut.',
      ['Allow it', '{player} shoots the ad and the club cashes in. A couple of sessions missed.'],
      ['Not during the season', '{player} gives it up reluctantly.']],
  },
  {
    id: 'pl_lazy_training', cat: 'player', w: 5, repeat: 15,
    when: { player: { personality: ['pigro'], rankMax: 12 } },
    o: [
      { odds: { base: 0.45, bond: 0.004, good: { attrs: { role: 1, stamina: 2 }, consistency: 8 }, bad: { morale: -10, bond: -8 } } },
      { fx: { suspended: 1, morale: -8, teamMorale: 2 } },
      { fx: { attrs: { stamina: -2 }, teamMorale: -2 } },
    ],
    it: ['{player} si allena al minimo', 'Il preparatore è stufo: {player} fa il minimo sindacale e arriva sempre per ultimo.',
      ['Lo prendo di petto', 'La sfida lo sveglia: {player} cambia atteggiamento.', '{player} si offende e diventa ancora più svogliato.'],
      ['Fuori dai convocati per una partita', 'Lo spogliatoio nota che nessuno è intoccabile.'],
      ['Lascio perdere, in partita rende', 'In partita qualcosa si perde, e il gruppo se ne accorge.']],
    en: ['{player} coasts in training', 'The fitness coach is fed up: {player} does the bare minimum and always arrives last.',
      ['Confront him head on', 'The challenge wakes him up: {player} changes his attitude.', '{player} takes offence and becomes even lazier.'],
      ['Left out of the squad for a match', 'The dressing room notes that nobody is untouchable.'],
      ['Let it go, he delivers on match day', 'Something is lost on match day, and the group notices.']],
  },
  {
    id: 'pl_ambitious_demand', cat: 'player', w: 5, repeat: 25,
    when: { player: { personality: ['ambizioso'], rankMax: 8, ageMax: 27 } },
    o: [
      { fx: { morale: 10, promiseStarts: { need: 4, within: 5 } } },
      { odds: { base: 0.45, pers: {}, bond: 0.005, good: { morale: 4, attrs: { role: 1 } }, bad: { morale: -14 } }, chain: { id: 'pl_transfer_request', in: 5 }, chainOn: 'bad' },
    ],
    it: ['{player} vuole di più', '{player} è convinto di meritare un ruolo centrale nel progetto e vuole garanzie.',
      ['Gli garantisco il posto: quattro partite su cinque', '{player} ha ottenuto quello che voleva. Ora devi mantenere.'],
      ['Nessuna garanzia per nessuno', '{player} accetta la sfida e migliora.', '{player} comincia a guardarsi intorno.']],
    en: ['{player} wants more', '{player} is convinced he deserves a central role in the project and wants guarantees.',
      ['Guarantee him a place: four of the next five', '{player} got what he wanted. Now you have to deliver.'],
      ['No guarantees for anyone', '{player} takes up the challenge and improves.', '{player} starts looking around.']],
  },
  {
    id: 'pl_fragile_confidence', cat: 'player', w: 5, repeat: 20,
    when: { last: 'L', player: { personality: ['fragile'], starter: true } },
    o: [
      { fx: { morale: 12, bond: 8 } },
      { odds: { base: 0.3, good: { form: 3, attrs: { composure: 2 } }, bad: { morale: -18, form: -4 } } },
    ],
    it: ['{player} si sente in colpa', 'Dopo la sconfitta {player} è convinto che sia tutta colpa sua. Non dorme da due notti.',
      ['Lo tranquillizzo: si vince e si perde insieme', '{player} ritrova serenità.'],
      ['Gli chiedo di reagire, senza coccole', 'Lo scossone gli fa bene: {player} risponde in campo.', '{player} crolla. Ci vorrà tempo.']],
    en: ['{player} blames himself', 'After the defeat {player} is convinced it’s all his fault. He hasn’t slept for two nights.',
      ['Reassure him: we win and lose together', '{player} finds his calm again.'],
      ['Ask him to react, no coddling', 'The jolt does him good: {player} answers on the pitch.', '{player} falls apart. It will take time.']],
  },
  {
    id: 'pl_leader_speech', cat: 'dressing', w: 4, repeat: 20,
    when: { streakL: 2, player: { personality: ['leader'], ageMin: 25 } },
    o: [
      { odds: { base: 0.65, bond: 0.003, good: { teamMorale: 8, teamForm: 1, bond: 8 }, bad: { teamMorale: -3, bond: -5 } } },
      { fx: { bond: -4, morale: -3 } },
    ],
    it: ['{player} vuole parlare alla squadra', 'Dopo due sconfitte {player} ti chiede di poter parlare allo spogliatoio senza di te.',
      ['Lascio la parola a lui', 'Il discorso di {player} scuote tutti: la squadra si ricompatta.', 'Il discorso diventa uno sfogo contro lo staff. Clima pesante.'],
      ['Parlo io, sono l’allenatore', '{player} fa un passo indietro, un po’ ferito.']],
    en: ['{player} wants to address the team', 'After two defeats {player} asks to speak to the dressing room without you.',
      ['Let him speak', '{player}’s speech shakes everyone up: the team closes ranks.', 'The speech turns into a rant against the staff. Heavy atmosphere.'],
      ['I’ll speak, I’m the manager', '{player} steps back, a little hurt.']],
  },
  {
    id: 'pl_old_star_bench', cat: 'dressing', w: 5, repeat: 20,
    when: { mdMin: 5, player: { ageMin: 31, starter: false, rankMax: 10 } },
    o: [
      { fx: { morale: 10, bond: 6, promiseStarts: { need: 2, within: 5 } } },
      { odds: { base: 0.55, pers: { leader: 0.15, professionista: 0.2, ribelle: -0.25 }, good: { teamMorale: 3, bond: 8 }, bad: { teamMorale: -5, morale: -15 } } },
    ],
    it: ['{player} non accetta la panchina', '{player} ha vinto tanto in carriera e non ha mai fatto la riserva. Ora la fa, e si vede.',
      ['Gli prometto spazio nelle prossime partite', '{player} torna a sorridere. Due partite da titolare, però, vanno date.'],
      ['Gli chiedo di fare il leader dalla panchina', '{player} accetta il nuovo ruolo: il suo esempio vale doppio.', '{player} rifiuta e rumoreggia con i giornalisti.']],
    en: ['{player} won’t accept the bench', '{player} has won a lot in his career and never been a substitute. Now he is, and it shows.',
      ['Promise him chances in the coming matches', '{player} smiles again. But two starts have to come.'],
      ['Ask him to lead from the bench', '{player} accepts the new role: his example counts double.', '{player} refuses and grumbles to the press.']],
  },
  {
    id: 'pl_style_learning', cat: 'style', w: 4, repeat: 20,
    when: { mdMin: 2, player: { ageMax: 24 } },
    o: [
      { fx: { attrs: { positioning: 3, vision: 2 }, fitness: -8, familiarity: 3 } },
      { fx: { fitness: 6 } },
    ],
    it: ['Video sessioni con {player}', 'Il tuo vice propone sessioni video individuali con {player} per spiegargli i movimenti del tuo stile.',
      ['Sì, tutti i pomeriggi', '{player} capisce il gioco molto più velocemente. E la squadra con lui.'],
      ['Meglio il campo', '{player} impara allenandosi.']],
    en: ['Video sessions with {player}', 'Your assistant suggests individual video sessions with {player} to explain your style’s movements.',
      ['Yes, every afternoon', '{player} understands the game much faster. And so does the team.'],
      ['The pitch is better', '{player} learns by training.']],
  },
  {
    id: 'pl_striker_drought', cat: 'player', w: 6, repeat: 12,
    when: { mdMin: 6, player: { roles: ['PUN'], starter: true, avgMax: 6.2 } },
    o: [
      { odds: { base: 0.5, pers: { professionista: 0.15, fragile: -0.2 }, good: { attrs: { finishing: 3 }, form: 4 }, bad: { form: -3, morale: -8 } } },
      { fx: { form: 2, morale: 6, attrs: { composure: 1 } } },
      { fx: { morale: -12, bond: -6, teamMorale: 1 } },
    ],
    it: ['{player} non segna più', '{player} non trova la porta da settimane. In allenamento calcia male anche a porta vuota.',
      ['Allenamento specifico sulla finalizzazione', 'Ore davanti alla porta: {player} ritrova il killer instinct.', '{player} si intestardisce e peggiora.'],
      ['Gli dico di non pensarci: i gol torneranno', '{player} gioca più libero di testa.'],
      ['Lo metto in discussione davanti a tutti', 'La squadra capisce che si gioca per il posto. {player} la prende malissimo.']],
    en: ['{player} can’t score', '{player} hasn’t found the net for weeks. In training he misses even an open goal.',
      ['Specific finishing training', 'Hours in front of goal: {player} rediscovers his killer instinct.', '{player} gets stubborn and gets worse.'],
      ['Tell him not to think about it: the goals will come', '{player} plays with a clearer head.'],
      ['Question him in front of everyone', 'The team understands everyone is playing for their place. {player} takes it very badly.']],
  },
  {
    id: 'pl_defender_error', cat: 'player', w: 5, repeat: 12,
    when: { last: 'L', player: { depts: ['DIF'], starter: true } },
    o: [
      { fx: { morale: 8, bond: 5 } },
      { odds: { base: 0.5, pers: { professionista: 0.15, fragile: -0.2 }, good: { attrs: { positioning: 2, composure: 2 } }, bad: { morale: -10, form: -3 } } },
    ],
    it: ['L’errore di {player}', 'Il gol decisivo è nato da un errore di {player}. I tifosi lo hanno fischiato a fine partita.',
      ['Lo proteggo davanti alla stampa', '{player} ti ringrazia: la settimana dopo è un muro.'],
      ['Rivediamo l’errore insieme al video', '{player} capisce dove ha sbagliato e cresce.', 'Rivedere l’errore dieci volte lo manda in paranoia.']],
    en: ['{player}’s mistake', 'The decisive goal came from a mistake by {player}. The fans whistled him at full time.',
      ['Protect him in front of the press', '{player} thanks you: the next week he’s a wall.'],
      ['Review the mistake together on video', '{player} understands where he went wrong and improves.', 'Watching the mistake ten times sends him into a spiral.']],
  },
  {
    id: 'pl_birthday_party', cat: 'dressing', w: 4, repeat: 20,
    when: { player: { rankMax: 14 } },
    o: [
      { fx: { teamMorale: 4, teamFitness: -4 } },
      { fx: { teamMorale: -2 } },
      { fx: { teamMorale: 2, budget: -0.1 } },
    ],
    it: ['La festa di {player}', '{player} compie gli anni e invita tutta la squadra a una festa sabato sera, a tre giorni dalla partita.',
      ['Tutti alla festa', 'Serata indimenticabile: il gruppo è unito, un po’ meno riposato.'],
      ['Festa vietata', 'Qualcuno mugugna, ma la preparazione è salva.'],
      ['Pranzo di squadra al centro sportivo', 'Compromesso perfetto: torta, sorrisi e tutti a letto presto.']],
    en: ['{player}’s party', 'It’s {player}’s birthday and he invites the whole team to a party on Saturday night, three days before the match.',
      ['Everyone to the party', 'An unforgettable night: the group is united, if a little less rested.'],
      ['Party banned', 'Some grumbling, but preparation is safe.'],
      ['Team lunch at the training ground', 'Perfect compromise: cake, smiles and everyone to bed early.']],
  },
  {
    id: 'pl_gk_distribution', cat: 'style', w: 3, repeat: 40,
    when: { styles: ['tikitaka', 'totale', 'falsonove', 'gegenpressing'], player: { roles: ['POR'], starter: true } },
    o: [
      { odds: { base: 0.55, pers: { professionista: 0.15, fragile: -0.15 }, good: { attrs: { distribution: 6, composure: 2 } }, bad: { form: -4, morale: -8 } } },
      { fx: { familiarity: -2 } },
    ],
    it: ['Il portiere deve giocare coi piedi', 'Il tuo calcio chiede al portiere di impostare. {player} però è a disagio con la palla tra i piedi.',
      ['Allenamento specifico con i piedi', '{player} diventa il primo regista della squadra.', 'Due errori in costruzione e {player} va nel pallone.'],
      ['Via libera ai lanci lunghi', 'Il tuo gioco perde qualcosa, ma {player} è sereno.']],
    en: ['The keeper has to play with his feet', 'Your football asks the goalkeeper to build play. But {player} is uncomfortable with the ball at his feet.',
      ['Specific footwork training', '{player} becomes the team’s first playmaker.', 'Two errors in build-up and {player} loses his head.'],
      ['Long balls allowed', 'Your game loses something, but {player} is at ease.']],
  },
  {
    id: 'pl_super_sub', cat: 'player', w: 4, repeat: 20,
    when: { mdMin: 6, player: { starter: false, goalsMin: 2 } },
    o: [
      { fx: { morale: 12, promiseStarts: { need: 2, within: 4 } } },
      { odds: { base: 0.5, pers: { professionista: 0.2, ambizioso: -0.25 }, good: { morale: 4, attrs: { composure: 2 } }, bad: { morale: -10 } } },
    ],
    it: ['{player}, l’arma dalla panchina', '{player} segna appena entra. Ora chiede una maglia da titolare.',
      ['Se la merita: due partite da titolare', '{player} è al settimo cielo. Tocca a te mantenere la parola.'],
      ['Mi serve così: è il mio dodicesimo uomo', '{player} accetta il ruolo di jolly.', '{player} non vuole restare la riserva di lusso.']],
    en: ['{player}, the super sub', '{player} scores as soon as he comes on. Now he wants a starting shirt.',
      ['He’s earned it: two starts', '{player} is over the moon. It’s up to you to keep your word.'],
      ['I need him like this: he’s my twelfth man', '{player} accepts the joker role.', '{player} doesn’t want to stay a luxury substitute.']],
  },
  {
    id: 'pl_contract_leverage', cat: 'market', w: 4, repeat: 30,
    when: { player: { contractLeft: 1, rankMax: 14, ageMax: 29, noFlag: 'renewed' } },
    o: [
      { fx: { renew: 3, raise: 0.2, morale: 8 } },
      { fx: { sell: 0.6 } },
      { fx: { noRenew: true, morale: -6 } },
    ],
    it: ['Contratto in scadenza: {player}', '{player} è in scadenza e non ha ancora rinnovato. Un club è pronto a prenderlo subito, a prezzo ridotto.',
      ['Rinnovo di tre anni', '{player} firma e resta.'],
      ['Lo vendo adesso', '{player} parte subito: meglio qualcosa che niente a giugno.'],
      ['Lo tengo fino a scadenza', '{player} giocherà la stagione e poi saluterà.']],
    en: ['Contract expiring: {player}', '{player}’s contract is running out and he hasn’t renewed. A club is ready to take him now, at a reduced price.',
      ['Three-year renewal', '{player} signs and stays.'],
      ['Sell him now', '{player} leaves at once: better something than nothing in June.'],
      ['Keep him until his contract ends', '{player} will play the season and then say goodbye.']],
  },
  {
    id: 'pl_teenage_offer', cat: 'youth', w: 4, repeat: 30,
    when: { window: true, player: { ageMax: 20, potentialGap: 8 } },
    o: [
      { fx: { sell: 1.6, youngsters: { morale: -4 }, fans: -4 } },
      { fx: { renew: 4, raise: 0.4, morale: 10, potential: 1 } },
    ],
    it: ['Un gigante vuole {player}', 'Un grande club europeo mette sul tavolo una cifra folle per {player}, che ha appena vent’anni.',
      ['Accetto: soldi che cambiano il bilancio', '{player} parte. I conti sorridono, il vivaio un po’ meno.'],
      ['Rifiuto e lo blindo', '{player} firma a lungo e sente la fiducia del club.']],
    en: ['A giant wants {player}', 'A big European club puts an outrageous sum on the table for {player}, who is barely twenty.',
      ['Accept: money that changes the accounts', '{player} leaves. The books are happy, the academy less so.'],
      ['Refuse and tie him down', '{player} signs long term and feels the club’s trust.']],
  },
  {
    id: 'pl_wrong_foot', cat: 'staff', w: 3, repeat: 40,
    when: { player: { depts: ['ATT', 'CEN'], ageMax: 24 } },
    o: [
      { odds: { base: 0.5, pers: { professionista: 0.25, pigro: -0.25 }, good: { attrs: { technique: 4, dribbling: 3 } }, bad: { form: -3, morale: -4 } } },
      { fx: {} },
    ],
    it: ['Il piede debole di {player}', 'Lo staff vuole far lavorare {player} sul piede debole: tre mesi di esercizi specifici.',
      ['Tre mesi di lavoro', '{player} diventa imprevedibile: calcia con tutti e due i piedi.', 'Troppa attenzione al piede debole e {player} perde sicurezza anche con quello forte.'],
      ['Non ne ha bisogno', 'Nessun lavoro extra.']],
    en: ['{player}’s weaker foot', 'The staff want {player} to work on his weaker foot: three months of specific drills.',
      ['Three months of work', '{player} becomes unpredictable: he strikes with both feet.', 'Too much focus on the weak foot and {player} loses confidence even with his strong one.'],
      ['He doesn’t need it', 'No extra work.']],
  },
];
