/* Rivali e fuori dal campo: derby, avversari, e la vita privata di tutti. */

export default [
  {
    id: 'rv_spy_drone', cat: 'rival', w: 3, repeat: 40,
    when: { mdMin: 3 },
    o: [
      { fx: { nextMatch: { control: 1.03 }, budget: -0.1 } },
      { fx: { fans: 3, reputation: -1, nextMatch: { discipline: 1.15 } } },
    ],
    it: ['Il drone sopra il campo', 'Durante l’allenamento a porte chiuse un drone sorvola il campo. Il sospetto: qualcuno spia la tattica.',
      ['Allenamenti in un campo coperto', 'Nessuno vede niente: la tattica resta segreta.'],
      ['Denuncio pubblicamente il rivale', 'Polemica rovente, squadra un po’ nervosa.']],
    en: ['The drone over the pitch', 'During a closed session a drone flies over the pitch. Suspicion: someone is spying on your tactics.',
      ['Train at an indoor pitch', 'Nobody sees anything: the tactics stay secret.'],
      ['Publicly accuse the rival', 'A heated row, a slightly edgy team.']],
  },
  {
    id: 'rv_rival_target', cat: 'rival', w: 3, repeat: 40,
    when: { window: true, player: { rankMax: 5 } },
    o: [
      { fx: { renew: 3, raise: 0.3, morale: 6 } },
      { fx: { sell: 1.25, fans: -10, trust: 2 } },
    ],
    it: ['Il rivale vuole {player}', 'La squadra rivale di sempre fa un’offerta importante per {player}.',
      ['Mai ai rivali: rinnovo', '{player} resta e firma. I tifosi ti adorano.'],
      ['Soldi sono soldi', '{player} va dai rivali. La città non te lo perdonerà.']],
    en: ['The rivals want {player}', 'The arch-rivals make a big offer for {player}.',
      ['Never to the rivals: renew', '{player} stays and signs. The fans adore you.'],
      ['Money is money', '{player} joins the rivals. The city won’t forgive you.']],
  },
  {
    id: 'rv_former_player_return', cat: 'rival', w: 3, repeat: 30,
    when: { mdMin: 2 },
    o: [
      { fx: { nextMatch: { defence: 1.03 } } },
      { fx: { fans: 3, nextMatch: { discipline: 1.15 } } },
    ],
    it: ['L’ex che torna', 'Il prossimo avversario, il {opponent}, ha in rosa un ex giocatore del club, andato via tra le polemiche.',
      ['Marcatura speciale su di lui', 'Lo annullate tatticamente.'],
      ['Lasciamo parlare i tifosi', 'Accoglienza infuocata: clima teso in campo.']],
    en: ['The ex returns', 'The next opponents, {opponent}, have a former club player who left amid controversy.',
      ['Special marking on him', 'You neutralise him tactically.'],
      ['Let the fans do the talking', 'A fiery reception: a tense atmosphere on the pitch.']],
  },
  {
    id: 'rv_match_rumour', cat: 'rival', w: 2, repeat: 80,
    when: { mdFromEndMax: 4 },
    o: [
      { fx: { reputation: 3, teamMorale: 2 } },
      { fx: { reputation: -2 } },
    ],
    it: ['Le voci di combine', 'Circolano voci su una partita “aggiustata” tra due rivali diretti nella corsa all’obiettivo.',
      ['Chiedo pubblicamente controlli', 'Posizione netta e pulita: rispetto nell’ambiente.'],
      ['Non commento voci', 'Silenzio prudente, che qualcuno legge come indifferenza.']],
    en: ['Match-fixing rumours', 'Rumours spread about a “fixed” match between two direct rivals in the race.',
      ['Publicly call for investigations', 'A clear, clean stance: respect in the game.'],
      ['I don’t comment on rumours', 'A cautious silence some read as indifference.']],
  },
  {
    id: 'rv_derby_handshake', cat: 'rival', w: 3, repeat: 20,
    when: { derbyNext: true },
    o: [
      { fx: { reputation: 2, fans: -2, nextMatch: { discipline: 0.85 } } },
      { fx: { fans: 3, nextMatch: { discipline: 1.15 } } },
    ],
    it: ['La stretta di mano', 'Prima del derby l’allenatore avversario propone un gesto di pace pubblico tra i due allenatori.',
      ['Accetto', 'Gesto apprezzato: clima più sereno in campo.'],
      ['Nessuna sceneggiata', 'La curva gradisce, la tensione resta.']],
    en: ['The handshake', 'Before the derby the rival manager proposes a public gesture of peace between the two managers.',
      ['Accept', 'An appreciated gesture: a calmer atmosphere on the pitch.'],
      ['No theatrics', 'The ultras like it, the tension remains.']],
  },
  {
    id: 'rv_poaching_staff', cat: 'staff', w: 3, repeat: 60,
    when: {},
    o: [
      { fx: { budget: -0.4, staff: 2 } },
      { fx: { staff: -8 } },
    ],
    it: ['Il rivale ti ruba lo staff', 'Un club rivale offre il doppio dello stipendio al tuo analista e al tuo preparatore.',
      ['Pareggiamo l’offerta', 'Lo staff resta unito.'],
      ['Chi vuole andare, vada', 'Due persone chiave lasciano lo staff.']],
    en: ['A rival poaches your staff', 'A rival club offers double pay to your analyst and your fitness coach.',
      ['Match the offer', 'The staff stay together.'],
      ['Whoever wants to go can go', 'Two key people leave the staff.']],
  },
  {
    id: 'rv_rival_crisis', cat: 'rival', w: 3, repeat: 30,
    when: { derbyNext: true },
    o: [
      { fx: { nextMatch: { attack: 1.04, block: 0.97 } } },
      { fx: { nextMatch: { control: 1.02 } } },
    ],
    it: ['Il rivale in crisi', 'Il {opponent} arriva al derby con l’allenatore in bilico e lo spogliatoio in rivolta.',
      ['Aggrediamoli dal primo minuto', 'Pressione alta per affondare un avversario fragile.'],
      ['Attenzione: le squadre ferite mordono', 'Approccio prudente e ordinato.']],
    en: ['The rival in crisis', '{opponent} come into the derby with their manager on the brink and a mutinous dressing room.',
      ['Go for them from the first minute', 'High pressure to sink a fragile opponent.'],
      ['Careful: wounded teams bite', 'A cautious, organised approach.']],
  },
  {
    id: 'pv_coach_family', cat: 'private', w: 3, repeat: 60,
    when: {},
    o: [
      { fx: { teamMorale: -2, reputation: 1, trust: -1 } },
      { fx: { reputation: -1, trust: 2 } },
    ],
    it: ['Tua figlia ha la recita', 'Tua figlia ha la recita di fine anno nello stesso giorno della rifinitura prima di una partita importante.',
      ['Vado alla recita: la rifinitura la fa il vice', 'Tua figlia è felicissima. Qualcuno in società storce il naso.'],
      ['Non posso mancare alla rifinitura', 'Il lavoro prima di tutto, con un po’ di amaro in bocca.']],
    en: ['Your daughter’s school play', 'Your daughter’s end-of-year play is on the same day as the final session before an important match.',
      ['Go to the play: my assistant runs the session', 'Your daughter is thrilled. Some at the club frown.'],
      ['I can’t miss the session', 'Work first, with a bitter taste.']],
  },
  {
    id: 'pv_player_baby', cat: 'private', w: 4, repeat: 30,
    when: { player: { ageMin: 23 } },
    o: [
      { fx: { morale: 12, bond: 10, fitness: -6 } },
      { fx: { morale: -8, bond: -8 } },
    ],
    it: ['Sta per nascere il figlio di {player}', 'La compagna di {player} sta per partorire proprio il giorno della trasferta.',
      ['Resta con la famiglia', '{player} non lo dimenticherà mai.'],
      ['Viene in trasferta: la partita è importante', '{player} gioca con la testa altrove e il cuore ferito.']],
    en: ['{player}’s baby is due', '{player}’s partner is about to give birth on the very day of the away trip.',
      ['He stays with his family', '{player} will never forget it.'],
      ['He travels: the match is important', '{player} plays with his mind elsewhere and a heavy heart.']],
  },
  {
    id: 'pv_wedding', cat: 'private', w: 3, repeat: 60,
    when: { player: { ageMin: 24 } },
    o: [
      { fx: { morale: 8, teamMorale: 3, teamFitness: -3 } },
      { fx: { morale: 2 } },
    ],
    it: ['Il matrimonio di {player}', '{player} si sposa e invita tutta la squadra, di sabato sera, a due giorni da una partita.',
      ['Ci andiamo tutti, con giudizio', 'Festa bellissima: il gruppo è più unito.'],
      ['Va solo una delegazione', 'Scelta prudente, {player} capisce.']],
    en: ['{player}’s wedding', '{player} is getting married and invites the whole team on a Saturday night, two days before a match.',
      ['We all go, sensibly', 'A beautiful party: the group is closer.'],
      ['Only a delegation goes', 'A cautious choice, {player} understands.']],
  },
  {
    id: 'pv_car_crash', cat: 'private', w: 2, repeat: 80,
    when: { player: { ageMax: 30 } },
    o: [
      { fx: { injury: 2, morale: 4, bond: 6 } },
      { fx: { injury: 2, suspended: 1, morale: -4 } },
    ],
    it: ['L’incidente in auto', '{player} ha avuto un incidente d’auto andando troppo veloce. Qualche contusione e tanta paura.',
      ['Prima di tutto la sua salute', '{player} si riprende sentendosi sostenuto.'],
      ['Multa: poteva uccidersi', 'Messaggio duro, ma necessario.']],
    en: ['The car crash', '{player} crashed his car while speeding. A few bruises and a big scare.',
      ['His health comes first', '{player} recovers feeling supported.'],
      ['A fine: he could have killed himself', 'A harsh message, but necessary.']],
  },
  {
    id: 'pv_gambling', cat: 'private', w: 2, repeat: 80,
    when: { player: { personality: ['ribelle', 'fragile', 'pigro'] } },
    o: [
      { fx: { morale: 6, bond: 10, form: -2, budget: -0.1 } },
      { fx: { sell: 0.7, teamMorale: -2 } },
    ],
    it: ['Il problema del gioco', 'Scopri che {player} ha accumulato debiti con il gioco d’azzardo.',
      ['Lo aiutiamo con uno specialista', '{player} affronta il problema e ti è grato.'],
      ['Lo mettiamo sul mercato', '{player} viene ceduto: via il rischio.']],
    en: ['The gambling problem', 'You discover {player} has run up gambling debts.',
      ['Help him with a specialist', '{player} faces the problem and is grateful.'],
      ['Put him on the market', '{player} is sold: the risk is gone.']],
  },
  {
    id: 'pv_tv_show', cat: 'private', w: 2, repeat: 80,
    when: { player: { rankMax: 10 } },
    o: [
      { fx: { morale: 5, fans: 2, fitness: -5, consistency: -4 } },
      { fx: { morale: -3 } },
    ],
    it: ['Il reality show', '{player} è stato invitato come ospite fisso in un programma TV del sabato sera.',
      ['Può andare, se non salta allenamenti', 'Popolarità alle stelle, un po’ di concentrazione in meno.'],
      ['Durante la stagione no', '{player} rinuncia, a malincuore.']],
    en: ['The TV show', '{player} has been invited as a regular guest on a Saturday night TV show.',
      ['He can, if he doesn’t miss training', 'Popularity soars, a bit less focus.'],
      ['Not during the season', '{player} gives it up reluctantly.']],
  },
  {
    id: 'pv_tax_issue', cat: 'private', w: 2, repeat: 100,
    when: { player: { rankMax: 8, ageMin: 25 } },
    o: [
      { fx: { morale: -6, trust: 2 } },
      { fx: { morale: 4, reputation: -2 } },
    ],
    it: ['Guai con il fisco', '{player} è indagato per irregolarità fiscali. I giornalisti ti chiedono se continuerà a giocare.',
      ['“È una questione privata, ma serve chiarezza”', 'Posizione equilibrata.'],
      ['“Ha tutta la mia fiducia”', '{player} ti ringrazia; qualcuno ti accusa di superficialità.']],
    en: ['Tax trouble', '{player} is under investigation for tax irregularities. Journalists ask whether he’ll keep playing.',
      ['“It’s a private matter, but clarity is needed”', 'A balanced stance.'],
      ['“He has my full trust”', '{player} thanks you; some accuse you of being careless.']],
  },
  {
    id: 'pv_coach_health', cat: 'private', w: 2, repeat: 100,
    when: { mdMin: 10 },
    o: [
      { fx: { teamMorale: 2, trust: -2 } },
      { fx: { reputation: 1 } },
    ],
    it: ['Lo stress', 'Il medico ti trova la pressione alta: ti consiglia due giorni di riposo.',
      ['Mi fermo due giorni', 'Il vice guida gli allenamenti; torni più lucido.'],
      ['Non ho tempo', 'Continui a lavorare, stringendo i denti.']],
    en: ['Stress', 'The doctor finds your blood pressure is high and advises two days of rest.',
      ['Take two days off', 'Your assistant runs training; you return sharper.'],
      ['I don’t have time', 'You keep working, gritting your teeth.']],
  },
  {
    id: 'pv_charity_foundation', cat: 'private', w: 2, repeat: 120,
    when: {},
    o: [
      { fx: { reputation: 3, fans: 4, budget: -0.1 } },
      { fx: {} },
    ],
    it: ['La tua fondazione', 'Ti propongono di aprire una fondazione per portare il calcio nei quartieri difficili.',
      ['Lo faccio', 'Un progetto bello che ti fa conoscere ovunque.'],
      ['Magari più avanti', 'Il progetto aspetta.']],
    en: ['Your foundation', 'You’re invited to set up a foundation bringing football to deprived neighbourhoods.',
      ['I’ll do it', 'A fine project that makes you known everywhere.'],
      ['Maybe later', 'The project waits.']],
  },
  {
    id: 'pv_player_mourning', cat: 'private', w: 2, repeat: 100,
    when: { player: {} },
    o: [
      { fx: { morale: 8, bond: 15, fitness: -4, teamMorale: 3 } },
      { fx: { morale: -8, bond: -10 } },
    ],
    it: ['Un lutto per {player}', '{player} ha perso una persona cara. Vorrebbe tornare a casa per una settimana.',
      ['Tutto il tempo che serve', '{player} torna quando è pronto, e gioca per chi non c’è più.'],
      ['Tre giorni, poi torna', '{player} torna, ma ha il cuore altrove.']],
    en: ['A bereavement for {player}', '{player} has lost a loved one. He’d like to go home for a week.',
      ['As long as he needs', '{player} returns when ready, and plays for the one who’s gone.'],
      ['Three days, then back', '{player} returns, but his heart is elsewhere.']],
  },
  {
    id: 'pv_nightlife_city', cat: 'private', w: 3, repeat: 40,
    when: { player: { ageMax: 25, personality: ['ribelle', 'ambizioso', 'pigro'] } },
    o: [
      { fx: { morale: -4, consistency: 6, fitness: 4 } },
      { odds: { base: 0.45, good: { morale: 4 }, bad: { form: -4, fitness: -10 } } },
    ],
    it: ['La vita notturna', 'Le voci dicono che {player} frequenta troppo i locali del centro. In allenamento sembra stanco.',
      ['Coprifuoco per lui', '{player} protesta, ma recupera energie.'],
      ['Mi fido: è maggiorenne', '{player} ripaga la fiducia.', '{player} esagera: gambe e testa ne risentono.']],
    en: ['The nightlife', 'Rumours say {player} spends too much time in city-centre clubs. In training he looks tired.',
      ['A curfew for him', '{player} protests, but recovers energy.'],
      ['I trust him: he’s an adult', '{player} repays the trust.', '{player} overdoes it: legs and head suffer.']],
  },
  {
    id: 'pv_house_move', cat: 'private', w: 2, repeat: 80,
    when: { player: { foreign: true, newSigning: true } },
    o: [
      { fx: { morale: 6, fitness: -3, budget: -0.05 } },
      { fx: { morale: -3 } },
    ],
    it: ['La casa nuova', '{player} vive ancora in albergo e non trova casa. Chiede aiuto al club.',
      ['L’ufficio del club gli trova casa', '{player} si sistema e si sente a casa.'],
      ['Se la deve cavare', '{player} resta in albergo.']],
    en: ['A new home', '{player} still lives in a hotel and can’t find a house. He asks the club for help.',
      ['The club office finds him a home', '{player} settles in and feels at home.'],
      ['He has to manage', '{player} stays in the hotel.']],
  },
  {
    id: 'pv_book_player', cat: 'private', w: 2, repeat: 100,
    when: { player: { ageMin: 30, rankMax: 10 } },
    o: [
      { fx: { morale: 5, fans: 3 } },
      { fx: { morale: -2, trust: 1 } },
    ],
    it: ['L’autobiografia', '{player} pubblica l’autobiografia. Un capitolo parla male di un ex allenatore del club.',
      ['È la sua storia', '{player} apprezza. Il libro vende.'],
      ['Gli chiedo di togliere quel capitolo', 'La società ringrazia, {player} un po’ meno.']],
    en: ['The autobiography', '{player} publishes his autobiography. One chapter criticises a former club manager.',
      ['It’s his story', '{player} appreciates it. The book sells.'],
      ['Ask him to remove that chapter', 'The board is grateful, {player} less so.']],
  },
  {
    id: 'pv_political_statement', cat: 'private', w: 2, repeat: 100,
    when: { player: { ageMin: 22 } },
    o: [
      { fx: { morale: 5, trust: -3, fans: -2 } },
      { fx: { morale: -6, trust: 2 } },
    ],
    it: ['La presa di posizione', '{player} ha pubblicato un messaggio su una questione sociale che divide il paese.',
      ['È libero di esprimersi', '{player} ti ringrazia; la società avrebbe preferito silenzio.'],
      ['Gli chiedo di rimuovere il post', 'Polemica spenta, ma {player} si sente censurato.']],
    en: ['The public stance', '{player} posted a message on a social issue that divides the country.',
      ['He’s free to express himself', '{player} thanks you; the board would have preferred silence.'],
      ['Ask him to remove the post', 'Row defused, but {player} feels censored.']],
  },
  {
    id: 'pv_luxury_car', cat: 'private', w: 2, repeat: 60,
    when: { player: { ageMax: 23 } },
    o: [
      { fx: { morale: -3, consistency: 4 } },
      { fx: { morale: 2, fans: -2 } },
    ],
    it: ['L’auto di lusso', '{player}, al primo contratto importante, arriva al centro sportivo con un’auto da mezzo milione.',
      ['Gli parlo di umiltà', '{player} capisce il messaggio.'],
      ['Sono soldi suoi', 'Nessun problema, ma i tifosi mormorano.']],
    en: ['The luxury car', '{player}, on his first big contract, arrives at the training ground in a half-million car.',
      ['Talk to him about humility', '{player} gets the message.'],
      ['It’s his money', 'No problem, but the fans mutter.']],
  },
  {
    id: 'pv_coach_interview_life', cat: 'private', w: 2, repeat: 100,
    when: { repMin: 45 },
    o: [
      { fx: { reputation: 2, fans: 2 } },
      { fx: {} },
    ],
    it: ['Un’intervista personale', 'Un settimanale vuole un’intervista sulla tua vita privata e la tua famiglia.',
      ['Racconto un po’ di me', 'I tifosi scoprono l’uomo oltre l’allenatore.'],
      ['La mia vita privata resta privata', 'Nessuna intervista.']],
    en: ['A personal interview', 'A weekly magazine wants an interview about your private life and family.',
      ['Share a bit about myself', 'The fans discover the man behind the manager.'],
      ['My private life stays private', 'No interview.']],
  },
  {
    id: 'pv_teammate_girlfriend', cat: 'private', w: 2, repeat: 100,
    when: { player: { ageMax: 30 } },
    o: [
      { fx: { teamMorale: -3, morale: -4 } },
      { odds: { base: 0.5, good: { teamMorale: 3 }, bad: { teamMorale: -6 } } },
    ],
    it: ['Il gossip nello spogliatoio', 'Un giornale di gossip scrive di una relazione tra {player} e l’ex compagna di un compagno di squadra.',
      ['Separo i due negli allenamenti', 'Tensione contenuta, ma il clima resta pesante.'],
      ['Li metto a parlare davanti a me', 'Chiariscono da uomini.', 'Il confronto degenera.']],
    en: ['Dressing room gossip', 'A gossip magazine reports a relationship between {player} and a teammate’s ex-partner.',
      ['Keep the two apart in training', 'Tension contained, but the mood stays heavy.'],
      ['Make them talk in front of me', 'They sort it out like men.', 'The confrontation gets ugly.']],
  },
  {
    id: 'pv_pet_training', cat: 'private', w: 1, repeat: 150,
    when: {},
    o: [
      { fx: { teamMorale: 4 } },
      { fx: {} },
    ],
    it: ['Il cane al campo', 'Un giocatore chiede di portare il cane agli allenamenti: dice che rilassa tutti.',
      ['Benvenuto, cane', 'Il cane diventa la mascotte: clima disteso.'],
      ['Niente animali al centro sportivo', 'Regola rispettata.']],
    en: ['A dog at training', 'A player asks to bring his dog to training: he says it relaxes everyone.',
      ['Welcome, dog', 'The dog becomes the mascot: a relaxed mood.'],
      ['No animals at the training ground', 'Rule respected.']],
  },
];
