/* Tattica, nazionale e mercato: le scelte di campo e quelle fuori stagione. */

export default [
  {
    id: 'st_analyst_formation', cat: 'style', w: 4, repeat: 25,
    when: { mdMin: 4, winless: 2 },
    o: [
      { odds: { base: 0.5, good: { familiarity: 4, teamForm: 1 }, bad: { familiarity: -6 } } },
      { fx: { trust: 1 } },
    ],
    it: ['Il modulo dell’analista', 'L’analista presenta dati che suggeriscono un modulo diverso contro le squadre che pressano alto.',
      ['Lo proviamo in settimana', 'I dati avevano ragione: la squadra respira meglio.', 'La squadra si confonde: meglio tornare al vecchio assetto.'],
      ['Mi fido del mio sistema', 'Nessun cambio.']],
    en: ['The analyst’s formation', 'The analyst presents data suggesting a different formation against high-pressing teams.',
      ['Try it this week', 'The data were right: the team breathes better.', 'The team gets confused: better go back to the old shape.'],
      ['I trust my system', 'No change.']],
  },
  {
    id: 'st_set_piece_coach', cat: 'style', w: 4, repeat: 60,
    when: { noFlag: 'setPieceCoach' },
    o: [
      { fx: { budget: -0.4, setFlag: 'setPieceCoach', nextMatch: { aerial: 1.08 } } },
      { fx: {} },
    ],
    it: ['L’allenatore delle palle inattive', 'Un tecnico specializzato in calci piazzati offre i suoi servizi: “Il trenta per cento dei gol nasce da palla ferma”.',
      ['Lo prendiamo', 'Schemi nuovi su angoli e punizioni.'],
      ['Non serve', 'Nessuno specialista.']],
    en: ['The set-piece coach', 'A set-piece specialist offers his services: “Thirty per cent of goals come from dead balls”.',
      ['Hire him', 'New routines for corners and free kicks.'],
      ['Not needed', 'No specialist.']],
  },
  {
    id: 'st_press_fatigue', cat: 'style', w: 5, repeat: 20,
    when: { mdMin: 8, styles: ['gegenpressing', 'totale'] },
    o: [
      { fx: { teamFitness: 8, nextMatch: { press: 0.9 } } },
      { fx: { teamFitness: -5, nextMatch: { press: 1.05 } } },
    ],
    it: ['Le gambe non girano', 'Il pressing alto per tutta la stagione sta presentando il conto: la squadra arriva stanca negli ultimi minuti.',
      ['Una settimana di pressing più basso', 'Energie recuperate, meno recuperi alti.'],
      ['Non si cambia: è la nostra identità', 'Identità mantenuta, fatica in aumento.']],
    en: ['Heavy legs', 'Pressing high all season is taking its toll: the team is tired in the closing minutes.',
      ['A week of lower pressing', 'Energy recovered, fewer high turnovers.'],
      ['No change: it’s our identity', 'Identity kept, fatigue rising.']],
  },
  {
    id: 'st_opponent_scouting', cat: 'style', w: 5, repeat: 10,
    when: { mdMin: 1 },
    o: [
      { fx: { nextMatch: { defence: 1.04 }, teamFitness: -2 } },
      { fx: { nextMatch: { attack: 1.04 }, teamFitness: -2 } },
      { fx: { teamFitness: 3 } },
    ],
    it: ['Preparare la partita', 'Il {opponent} è una squadra con idee chiare. Su cosa concentri la settimana?',
      ['Neutralizzare i loro punti di forza', 'La squadra conosce a memoria le mosse avversarie.'],
      ['Colpire i loro punti deboli', 'La squadra sa dove fare male.'],
      ['Pensiamo a noi e al recupero fisico', 'Gambe fresche e testa libera.']],
    en: ['Preparing the match', '{opponent} are a team with clear ideas. What does the week focus on?',
      ['Neutralise their strengths', 'The team knows the opponent’s moves by heart.'],
      ['Exploit their weaknesses', 'The team knows where to hurt them.'],
      ['Focus on ourselves and recovery', 'Fresh legs and a clear head.']],
  },
  {
    id: 'st_new_tactic_idea', cat: 'style', w: 3, repeat: 40,
    when: { mdMin: 6 },
    o: [
      { odds: { base: 0.45, good: { nextMatch: { attack: 1.08 }, familiarity: 2 }, bad: { nextMatch: { control: 0.94 } } } },
      { fx: {} },
    ],
    it: ['L’idea notturna', 'Stanotte ti è venuta un’idea tattica rivoluzionaria per la prossima partita. Il vice è scettico.',
      ['La provo subito', 'Mossa geniale: l’avversario non capisce nulla.', 'L’idea non funziona: la squadra è spaesata.'],
      ['La tengo nel cassetto', 'Nessun rischio.']],
    en: ['The midnight idea', 'Last night you had a revolutionary tactical idea for the next match. Your assistant is sceptical.',
      ['Try it right away', 'A stroke of genius: the opponent can’t work it out.', 'The idea doesn’t work: the team is lost.'],
      ['Keep it in the drawer', 'No risk.']],
  },
  {
    id: 'st_long_ball_pitch', cat: 'style', w: 3, repeat: 30,
    when: { mdMin: 3, styles: ['tikitaka', 'falsonove'] },
    o: [
      { fx: { nextMatch: { direct: 1.1, control: 0.97 } } },
      { fx: { nextMatch: { control: 0.95 } } },
    ],
    it: ['Il campo pesante', 'La prossima trasferta è su un campo pesante e irregolare: il palleggio corto rischia di impantanarsi.',
      ['Per una volta palla lunga', 'Adattamento pragmatico.'],
      ['Il nostro calcio si gioca ovunque', 'Coerenza, ma il pallone rimbalza male.']],
    en: ['The heavy pitch', 'The next away game is on a heavy, bumpy pitch: short passing risks getting bogged down.',
      ['For once, go long', 'A pragmatic adaptation.'],
      ['Our football works anywhere', 'Consistent, but the ball bounces badly.']],
  },
  {
    id: 'st_defensive_errors', cat: 'style', w: 4, repeat: 20,
    when: { last: 'L', mdMin: 3 },
    o: [
      { fx: { nextMatch: { defence: 1.05, attack: 0.96 }, familiarity: 2 } },
      { fx: { nextMatch: { line: 0.9, counter: 1.05 } } },
    ],
    it: ['Troppi gol presi', 'Ultimamente la difesa concede troppo. Il vice propone due strade.',
      ['Una settimana solo di lavoro difensivo', 'Più solidi, meno pericolosi davanti.'],
      ['Difesa più bassa e ripartenze', 'Meno spazio alle spalle, più contropiedi.']],
    en: ['Conceding too many', 'Lately the defence concedes too much. Your assistant suggests two routes.',
      ['A week of defensive work only', 'More solid, less dangerous up front.'],
      ['A deeper line and counters', 'Less space behind, more counter-attacks.']],
  },
  {
    id: 'st_goal_drought', cat: 'style', w: 4, repeat: 20,
    when: { mdMin: 4, winless: 2 },
    o: [
      { fx: { nextMatch: { attack: 1.06, defence: 0.96 } } },
      { fx: { nextMatch: { aerial: 1.08 } } },
      { fx: { teamMorale: 3 } },
    ],
    it: ['Non segniamo più', 'La squadra crea poco e segna ancora meno.',
      ['Più uomini in area', 'Più occasioni, più rischi dietro.'],
      ['Allenamento sulle palle inattive', 'Un’arma in più.'],
      ['Serenità: i gol arriveranno', 'Il gruppo si sente meno sotto pressione.']],
    en: ['We can’t score', 'The team creates little and scores even less.',
      ['More bodies in the box', 'More chances, more risk at the back.'],
      ['Work on set pieces', 'An extra weapon.'],
      ['Stay calm: the goals will come', 'The group feels less pressure.']],
  },
  {
    id: 'st_winter_style', cat: 'style', w: 3, repeat: 40,
    when: { mdMin: 15, mdMax: 24 },
    o: [
      { fx: { familiarity: -5, teamFitness: 4 } },
      { fx: { familiarity: 3 } },
    ],
    it: ['La lavagna di gennaio', 'La sosta invernale è il momento giusto per cambiare qualcosa nel sistema di gioco.',
      ['Cambio qualcosa, sfruttando la sosta', 'Novità assimilate con calma, qualche automatismo da rifare.'],
      ['Consolido quello che c’è', 'La squadra perfeziona il suo gioco.']],
    en: ['The January whiteboard', 'The winter break is the right time to change something in the system.',
      ['Change something, using the break', 'New ideas absorbed calmly, some automatisms to rebuild.'],
      ['Consolidate what we have', 'The team refines its game.']],
  },
  {
    id: 'st_wing_backs_tired', cat: 'style', w: 3, repeat: 30,
    when: { styles: ['quinti', 'fasce'], mdMin: 6 },
    o: [
      { fx: { teamFitness: 5, nextMatch: { wide: 0.94 } } },
      { fx: { nextMatch: { wide: 1.05 }, teamFitness: -4 } },
    ],
    it: ['Gli esterni sono cotti', 'Gli esterni corrono chilometri ogni partita: lo staff segnala segni di affaticamento.',
      ['Turnover sugli esterni', 'Esterni più freschi, un po’ meno spinta.'],
      ['Stringono i denti', 'Spinta massima, fatica crescente.']],
    en: ['The wing-backs are spent', 'The wide players run miles every match: the staff report signs of fatigue.',
      ['Rotate the wide players', 'Fresher wide men, a little less drive.'],
      ['They grit their teeth', 'Maximum drive, rising fatigue.']],
  },
  {
    id: 'st_captain_tactics', cat: 'style', w: 3, repeat: 30,
    when: { player: { captain: true, ageMin: 27 } },
    o: [
      { fx: { bond: 10, familiarity: 3, trust: -1 } },
      { fx: { bond: -5 } },
    ],
    it: ['Il capitano propone', '{player} ti propone un piccolo aggiustamento tattico che, dice, i giocatori sentirebbero loro.',
      ['Lo adotto', 'Il gruppo sente la tattica propria: più convinzione.'],
      ['Ringrazio, ma decido io', '{player} ci resta un po’ male.']],
    en: ['The captain suggests', '{player} suggests a small tactical tweak that, he says, the players would feel was theirs.',
      ['Adopt it', 'The group owns the tactics: more conviction.'],
      ['Thank him, but I decide', '{player} is a bit hurt.']],
  },
  {
    id: 'st_video_mistakes', cat: 'style', w: 3, repeat: 20,
    when: { last: 'L' },
    o: [
      { fx: { familiarity: 4, teamMorale: -3 } },
      { fx: { teamMorale: 2 } },
    ],
    it: ['Il video degli errori', 'Il vice ha montato un video con tutti gli errori dell’ultima partita.',
      ['Lo guardiamo tutti insieme', 'Utile, anche se umiliante.'],
      ['Solo un video delle cose buone', 'Fiducia ricostruita.']],
    en: ['The mistakes video', 'Your assistant has cut a video of every mistake from the last match.',
      ['We all watch it together', 'Useful, if humiliating.'],
      ['Only a video of the good things', 'Confidence rebuilt.']],
  },
  {
    id: 'st_underdog_plan', cat: 'style', w: 4, repeat: 15,
    when: { mdMin: 1, objective: ['survival', 'safe', 'midTable', 'topHalf'] },
    o: [
      { fx: { nextMatch: { block: 1.12, attack: 0.9 } } },
      { fx: { nextMatch: { attack: 1.05, line: 1.1 } } },
    ],
    it: ['Contro una grande', 'Il {opponent} sulla carta è più forte. Come la prepari?',
      ['Blocco basso e pazienza', 'Squadra corta, poche concessioni.'],
      ['Li aggrediamo: niente paura', 'Coraggio: si può vincere, si può anche soffrire.']],
    en: ['Against a big side', 'On paper {opponent} are stronger. How do you prepare?',
      ['A low block and patience', 'A compact team, conceding little.'],
      ['Go at them: no fear', 'Courage: you can win, you can also suffer.']],
  },
  {
    id: 'st_favourite_plan', cat: 'style', w: 4, repeat: 15,
    when: { mdMin: 1, objective: ['title', 'ucl', 'promotion'] },
    o: [
      { fx: { nextMatch: { control: 1.04 } } },
      { fx: { nextMatch: { tempo: 1.05, press: 1.08 }, teamFitness: -3 } },
    ],
    it: ['Da favoriti', 'Contro il {opponent} siete favoriti. Il rischio è sottovalutare la partita.',
      ['Palleggio e pazienza', 'Controllo del gioco.'],
      ['Ritmo altissimo per chiuderla subito', 'Partenza forte, energie consumate.']],
    en: ['As favourites', 'Against {opponent} you’re favourites. The risk is underestimating the game.',
      ['Possession and patience', 'Control of the game.'],
      ['A frantic pace to kill it early', 'A strong start, energy spent.']],
  },
  {
    id: 'st_referee_style', cat: 'style', w: 3, repeat: 20,
    when: { mdMin: 2 },
    o: [
      { fx: { nextMatch: { discipline: 0.8, press: 0.95 } } },
      { fx: {} },
    ],
    it: ['L’arbitro fiscale', 'L’arbitro della prossima partita è famoso per estrarre molti cartellini.',
      ['Chiedo entrate pulite e niente proteste', 'Meno cartellini, un po’ meno aggressività.'],
      ['Si gioca come sempre', 'Nessun adattamento.']],
    en: ['The strict referee', 'The next referee is known for showing lots of cards.',
      ['Ask for clean tackles and no dissent', 'Fewer cards, a little less aggression.'],
      ['Play as always', 'No adjustment.']],
  },
  {
    id: 'nt_break_fatigue', cat: 'national', w: 4, repeat: 20,
    when: { mdMin: 3, player: { rankMax: 6, capsMin: 5 } },
    o: [
      { fx: { fitness: 12, form: -1 } },
      { fx: { fitness: -6, form: 1 } },
    ],
    it: ['Il ritorno dalla nazionale', '{player} torna dalla nazionale dopo un volo intercontinentale, due giorni prima della partita.',
      ['Parte dalla panchina', '{player} riposa: tornerà fresco.'],
      ['Titolare: è in forma', '{player} gioca con il fuso orario addosso.']],
    en: ['Back from international duty', '{player} returns from international duty after an intercontinental flight, two days before the match.',
      ['He starts on the bench', '{player} rests: he’ll be fresh.'],
      ['He starts: he’s in form', '{player} plays with jet lag.']],
  },
  {
    id: 'nt_coach_call', cat: 'national', w: 3, repeat: 30,
    when: { player: { rankMax: 10, ageMin: 22, ageMax: 30 } },
    o: [
      { fx: { morale: 10, attrs: { composure: 1 }, reputation: 1 } },
      { fx: { morale: -2 } },
    ],
    it: ['Il ct chiama', 'Il commissario tecnico della nazionale ti telefona: vuole informazioni su {player} per una possibile convocazione.',
      ['Ne parlo benissimo', '{player} viene convocato ed è al settimo cielo.'],
      ['Onestamente non è ancora pronto', 'Nessuna convocazione.']],
    en: ['The national coach calls', 'The national team coach phones you: he wants information about {player} for a possible call-up.',
      ['Speak very highly of him', '{player} gets called up and is over the moon.'],
      ['Honestly, he’s not ready yet', 'No call-up.']],
  },
  {
    id: 'nt_retire_national', cat: 'national', w: 2, repeat: 80,
    when: { player: { ageMin: 31 } },
    o: [
      { fx: { fitness: 10, morale: 3, injuryProne: -5 } },
      { fx: { morale: 4 } },
    ],
    it: ['Addio alla nazionale?', '{player} ti chiede un consiglio: lasciare la nazionale per allungare la carriera nel club?',
      ['Sì, pensa al club', '{player} lascia la nazionale e arriva più fresco alle partite.'],
      ['Finché può, giochi con la maglia del paese', '{player} continua con orgoglio.']],
    en: ['Retire from international football?', '{player} asks your advice: quit the national team to extend his club career?',
      ['Yes, think of the club', '{player} retires internationally and is fresher for matches.'],
      ['As long as he can, play for his country', '{player} carries on with pride.']],
  },
  {
    id: 'nt_injured_on_duty', cat: 'national', w: 3, repeat: 30,
    when: { player: { rankMax: 8 } },
    o: [
      { fx: { injury: 3, trust: 1, reputation: -1 } },
      { fx: { injury: 3, bond: 5 } },
    ],
    it: ['Infortunato in nazionale', '{player} si è fatto male con la nazionale. I giornali accusano il ct di averlo spremuto.',
      ['Attacco pubblicamente la federazione', 'La società apprezza la difesa degli interessi del club.'],
      ['Penso solo al recupero del ragazzo', '{player} apprezza la vicinanza.']],
    en: ['Injured on international duty', '{player} got injured with the national team. The papers accuse the coach of overworking him.',
      ['Publicly criticise the federation', 'The board appreciates you defending the club’s interests.'],
      ['I only care about his recovery', '{player} appreciates your support.']],
  },
  {
    id: 'nt_tournament_summer', cat: 'national', w: 3, repeat: 60,
    when: { mdFromEndMax: 6, player: { rankMax: 8, ageMin: 23 } },
    o: [
      { fx: { fitness: 8, morale: -4 } },
      { fx: { morale: 6, fitness: -4 } },
    ],
    it: ['Il grande torneo estivo', '{player} sarà al grande torneo per nazionali in estate. Ti chiede di gestirlo a fine stagione.',
      ['Minuti ridotti nelle ultime giornate', '{player} arriverà fresco al torneo, un po’ deluso di giocare meno.'],
      ['Gioca tutto fino alla fine', '{player} felice, ma stanco.']],
    en: ['The big summer tournament', '{player} will play at the big international tournament this summer. He asks you to manage his minutes late in the season.',
      ['Reduced minutes in the final rounds', '{player} will be fresh for the tournament, a bit sad to play less.'],
      ['He plays everything until the end', '{player} happy, but tired.']],
  },
  {
    id: 'nt_dual_nationality', cat: 'national', w: 2, repeat: 100,
    when: { player: { ageMax: 23, foreign: true } },
    o: [
      { fx: { morale: 6, bond: 6 } },
      { fx: { morale: 2 } },
    ],
    it: ['Due nazionali', '{player} può scegliere tra due nazionali e ti chiede un consiglio.',
      ['Lo aiuto a scegliere con il cuore', '{player} ti ringrazia per l’ascolto.'],
      ['Scelga quella che gioca di più', 'Consiglio pratico.']],
    en: ['Two national teams', '{player} can choose between two national teams and asks your advice.',
      ['Help him choose with his heart', '{player} thanks you for listening.'],
      ['Choose the one that gives him minutes', 'Practical advice.']],
  },
  {
    id: 'nt_break_friendly_club', cat: 'national', w: 3, repeat: 30,
    when: { mdMin: 5 },
    o: [
      { fx: { familiarity: 4, teamFitness: -3 } },
      { fx: { teamFitness: 5 } },
    ],
    it: ['La sosta per le nazionali', 'Metà squadra è via con le nazionali. Con chi resta come usi la sosta?',
      ['Lavoro tattico intenso', 'Chi resta impara meglio il sistema.'],
      ['Riposo e piccoli infortuni curati', 'Gambe fresche per la ripresa.']],
    en: ['The international break', 'Half the squad is away with national teams. How do you use the break with those left?',
      ['Intense tactical work', 'Those left learn the system better.'],
      ['Rest and treat knocks', 'Fresh legs for the restart.']],
  },
  {
    id: 'mk_deadline_day', cat: 'market', w: 4, repeat: 25,
    when: { window: true, mdMin: 1 },
    o: [
      { fx: { signVeteran: { level: 1 }, budgetPct: -0.15 } },
      { fx: { trust: 2 } },
    ],
    it: ['L’ultimo giorno di mercato', 'Ultime ore di mercato: il direttore sportivo ha la possibilità di chiudere un giocatore esperto, subito pronto.',
      ['Chiudiamo l’affare', 'Arriva un rinforzo di esperienza per questa stagione.'],
      ['Nessun colpo last minute', 'La rosa resta quella.']],
    en: ['Deadline day', 'The last hours of the window: the sporting director can close a deal for an experienced, ready-made player.',
      ['Close the deal', 'An experienced reinforcement arrives for this season.'],
      ['No last-minute deals', 'The squad stays as it is.']],
  },
  {
    id: 'mk_free_agent_veteran', cat: 'market', w: 4, repeat: 30,
    when: { injuredMin: 2 },
    o: [
      { fx: { signVeteran: { level: -2, personality: 'professionista' } } },
      { fx: {} },
    ],
    it: ['Lo svincolato', 'Con tre infortunati, il procuratore di un veterano svincolato ti propone il suo assistito, anche solo fino a fine stagione.',
      ['Lo prendiamo', 'Un professionista esperto rinforza la rosa.'],
      ['Ci arrangiamo con i nostri', 'Nessun arrivo.']],
    en: ['The free agent', 'With three injured, a veteran free agent’s agent offers his client, even just until the end of the season.',
      ['Sign him', 'An experienced professional strengthens the squad.'],
      ['We’ll make do with our own', 'No arrival.']],
  },
  {
    id: 'mk_swap_offer', cat: 'market', w: 3, repeat: 30,
    when: { window: true, player: { starter: false, rankMax: 18, ageMin: 24 } },
    o: [
      { fx: { sell: 0.6, signVeteran: { level: 0 } } },
      { fx: { morale: -3 } },
    ],
    it: ['Lo scambio', 'Un club propone uno scambio: {player}, che gioca poco, per un loro giocatore esperto di pari livello.',
      ['Accetto lo scambio', 'Rosa rinnovata: arriva un giocatore pronto.'],
      ['{player} resta', '{player} rimane, ancora in panchina.']],
    en: ['The swap', 'A club proposes a swap: {player}, who hardly plays, for one of their experienced players of similar level.',
      ['Accept the swap', 'A refreshed squad: a ready player arrives.'],
      ['{player} stays', '{player} remains, still on the bench.']],
  },
  {
    id: 'mk_release_clause', cat: 'market', w: 3, repeat: 40,
    when: { window: true, player: { rankMax: 4, ageMax: 27 } },
    o: [
      { fx: { sell: 1.5, fans: -6, teamMorale: -4 } },
      { fx: { renew: 4, raise: 0.4, budgetPct: -0.2, morale: 8 } },
    ],
    it: ['La clausola rescissoria', 'Un club ricchissimo è pronto a pagare la clausola di {player}. Hai poche ore per decidere.',
      ['Lasciamo che la paghino', '{player} parte, le casse si riempiono.'],
      ['Alziamo la clausola con un rinnovo', 'Costa caro, ma {player} resta blindato.']],
    en: ['The release clause', 'A very rich club is ready to pay {player}’s release clause. You have a few hours to decide.',
      ['Let them pay it', '{player} leaves, the coffers fill.'],
      ['Raise the clause with a new contract', 'Expensive, but {player} is locked in.']],
  },
  {
    id: 'mk_agent_complains', cat: 'market', w: 3, repeat: 30,
    when: { player: { starter: false, rankMax: 14, ageMin: 22 } },
    o: [
      { fx: { promiseStarts: { need: 2, within: 5 }, morale: 6 } },
      { fx: { loanOut: true } },
      { fx: { morale: -8, bond: -6 } },
    ],
    it: ['Il procuratore di {player}', 'Il procuratore di {player} ti chiama: il suo assistito vuole giocare, altrimenti a gennaio chiederà di andare via.',
      ['Gli darò spazio', 'Il procuratore si calma. Ora le partite vanno date.'],
      ['Lo mando in prestito', '{player} va a giocare altrove.'],
      ['Nessuna garanzia', 'Il procuratore minaccia battaglia.']],
    en: ['{player}’s agent', '{player}’s agent calls: his client wants to play, otherwise he’ll ask to leave in January.',
      ['I’ll give him chances', 'The agent calms down. Now the matches must come.'],
      ['Loan him out', '{player} goes to play elsewhere.'],
      ['No guarantees', 'The agent threatens a fight.']],
  },
  {
    id: 'mk_sell_to_balance', cat: 'finance', w: 3, repeat: 60,
    when: { window: true, budgetMax: 2, player: { rankMax: 8, ageMin: 27 } },
    o: [
      { fx: { sell: 1.05, trust: 5 } },
      { fx: { trust: -5 } },
    ],
    it: ['Serve vendere', 'Il bilancio chiede una cessione importante entro fine mercato. La società indica {player}.',
      ['Accetto: va venduto', 'Il bilancio si sistema, la squadra perde un titolare.'],
      ['Mi oppongo', 'La società dovrà trovare i soldi altrove, e non la prende bene.']],
    en: ['We need to sell', 'The accounts require a major sale by the end of the window. The club names {player}.',
      ['Agree: he goes', 'The books balance, the team loses a starter.'],
      ['Oppose it', 'The club must find the money elsewhere, and isn’t happy.']],
  },
  {
    id: 'mk_loan_recall', cat: 'market', w: 3, repeat: 40,
    when: { window: true, injuredMin: 2 },
    o: [
      { fx: { signVeteran: { level: -3 }, budget: -0.2 } },
      { fx: {} },
    ],
    it: ['Richiamare un prestito', 'Uno dei giocatori in prestito altrove sta giocando bene. Con gli infortuni potresti richiamarlo.',
      ['Lo richiamo', 'Un giocatore in più per l’emergenza.'],
      ['Resta dov’è a crescere', 'Nessun richiamo.']],
    en: ['Recall a loan', 'One of your players out on loan is doing well. With the injuries you could recall him.',
      ['Recall him', 'One more player for the emergency.'],
      ['He stays where he is to develop', 'No recall.']],
  },
  {
    id: 'mk_scouting_report', cat: 'market', w: 3, repeat: 30,
    when: { window: true },
    o: [
      { fx: { staff: 4, budget: -0.1 } },
      { fx: {} },
    ],
    it: ['Il dossier degli osservatori', 'Gli osservatori hanno preparato un dossier su trenta giocatori sottovalutati in giro per l’Europa.',
      ['Lo studio in dettaglio', 'Ora conosci meglio il mercato.'],
      ['Mi basta il direttore sportivo', 'Nessun approfondimento.']],
    en: ['The scouts’ dossier', 'The scouts have prepared a dossier on thirty undervalued players across Europe.',
      ['Study it in detail', 'You now know the market better.'],
      ['The sporting director is enough', 'No deep dive.']],
  },
  {
    id: 'mk_fan_favourite_sale', cat: 'market', w: 3, repeat: 40,
    when: { window: true, player: { ageMin: 28, rankMax: 12, starter: false } },
    o: [
      { fx: { sell: 0.9, fans: -6 } },
      { fx: { fans: 3, morale: 4 } },
    ],
    it: ['Vendere il beniamino', '{player} gioca poco ma è amatissimo dai tifosi. Arriva un’offerta.',
      ['Vendiamo: servono soldi e spazio', 'Scelta razionale, tifosi arrabbiati.'],
      ['Resta: è un simbolo', '{player} resta, e i tifosi ringraziano.']],
    en: ['Selling the favourite', '{player} plays little but is adored by the fans. An offer arrives.',
      ['Sell: we need money and space', 'A rational choice, angry fans.'],
      ['He stays: he’s a symbol', '{player} stays, and the fans are grateful.']],
  },
  {
    id: 'mk_january_striker', cat: 'market', w: 3, repeat: 40,
    when: { window: true, mdMin: 10, winless: 2 },
    o: [
      { fx: { signVeteran: { level: 2, role: 'PUN' }, budgetPct: -0.3 } },
      { fx: { teamMorale: 2 } },
    ],
    it: ['Un attaccante a gennaio', 'La squadra non segna. Il direttore sportivo può prendere una punta esperta, ma costa.',
      ['Prendiamolo', 'Arriva un centravanti pronto a fare gol subito.'],
      ['Crediamo nei nostri', 'Gli attaccanti apprezzano la fiducia.']],
    en: ['A January striker', 'The team can’t score. The sporting director can sign an experienced striker, but he’s expensive.',
      ['Sign him', 'A centre-forward arrives, ready to score right away.'],
      ['We believe in ours', 'The strikers appreciate the trust.']],
  },
  {
    id: 'mk_defender_needed', cat: 'market', w: 3, repeat: 40,
    when: { window: true, mdMin: 10, streakL: 2 },
    o: [
      { fx: { signVeteran: { level: 1, role: 'DC' }, budgetPct: -0.25 } },
      { fx: {} },
    ],
    it: ['Un difensore d’esperienza', 'Troppi gol presi. Un difensore esperto è disponibile a condizioni ragionevoli.',
      ['Lo prendiamo', 'Esperienza in più al centro della difesa.'],
      ['Si lavora con quelli che ci sono', 'Nessun acquisto.']],
    en: ['An experienced defender', 'Too many goals conceded. An experienced defender is available on reasonable terms.',
      ['Sign him', 'More experience at the heart of the defence.'],
      ['We work with what we have', 'No signing.']],
  },
  {
    id: 'mk_keeper_backup', cat: 'market', w: 2, repeat: 60,
    when: { window: true },
    o: [
      { fx: { signVeteran: { level: -4, role: 'POR', personality: 'leader' } } },
      { fx: {} },
    ],
    it: ['Il terzo portiere', 'Un vecchio portiere a fine carriera si offre come terzo portiere e uomo spogliatoio.',
      ['Lo prendiamo', 'Un leader silenzioso entra nello spogliatoio.'],
      ['Non serve', 'Nessun arrivo.']],
    en: ['The third goalkeeper', 'An old goalkeeper at the end of his career offers himself as third keeper and dressing-room presence.',
      ['Sign him', 'A quiet leader joins the dressing room.'],
      ['Not needed', 'No arrival.']],
  },
];
