/* Momenti della stagione: la corsa all'obiettivo, l'ultimatum, la serie
   cadetta, le grandi notti, il finale. */

export default [
  {
    id: 'ss_ultimatum_speech', cat: 'dressing', w: 8, repeat: 10,
    when: { ultimatum: true },
    o: [
      { odds: { base: 0.55, teamMorale: 0.006, good: { teamMorale: 8, nextMatch: { attack: 1.05 } }, bad: { teamMorale: -6 } } },
      { fx: { teamMorale: 3, nextMatch: { block: 1.05 } } },
      { fx: { teamMorale: -3, trust: 3 } },
    ],
    it: ['L’ultimatum', 'La società ti ha dato un ultimatum. I giocatori lo sanno. Cosa dici allo spogliatoio?',
      ['“Non giocate per me, giocate per voi”', 'Il gruppo risponde compatto.', 'Il discorso suona come una resa: la squadra è spenta.'],
      ['“Prima non prendiamo gol, poi il resto”', 'Squadra corta e concentrata.'],
      ['Non ne parlo: si lavora e basta', 'La società apprezza il sangue freddo, il gruppo è teso.']],
    en: ['The ultimatum', 'The board has given you an ultimatum. The players know. What do you tell the dressing room?',
      ['“Don’t play for me, play for yourselves”', 'The group responds as one.', 'The speech sounds like surrender: the team is flat.'],
      ['“First we stop conceding, then the rest”', 'A compact, focused team.'],
      ['I don’t mention it: we just work', 'The board appreciates the composure, the group is tense.']],
  },
  {
    id: 'ss_relegation_battle', cat: 'board', w: 6, repeat: 15,
    when: { mdMin: 20, objective: ['survival', 'safe'], gapMin: 2 },
    o: [
      { fx: { budgetPct: -0.2, signVeteran: { level: 1 } } },
      { fx: { teamMorale: 4, nextMatch: { block: 1.06 } } },
      { odds: { base: 0.45, good: { teamMorale: 8, fans: 6 }, bad: { fans: -4 } } },
    ],
    it: ['La lotta per non retrocedere', 'La zona retrocessione è vicina. La società chiede proposte concrete.',
      ['Un giocatore d’esperienza per la volata', 'Arriva un veterano abituato a queste battaglie.'],
      ['Ritiro chiuso fino alla fine', 'Squadra isolata e concentrata.'],
      ['Chiedo alla città di riempire lo stadio', 'Lo stadio diventa una bolgia.', 'L’appello cade nel vuoto.']],
    en: ['The relegation battle', 'The relegation zone is close. The board wants concrete proposals.',
      ['An experienced player for the run-in', 'A veteran used to these battles arrives.'],
      ['A closed training camp until the end', 'An isolated, focused team.'],
      ['Ask the city to fill the stadium', 'The stadium becomes a cauldron.', 'The appeal falls on deaf ears.']],
  },
  {
    id: 'ss_title_race', cat: 'dressing', w: 6, repeat: 15,
    when: { mdMin: 22, posMax: 3, level: 1 },
    o: [
      { fx: { teamMorale: 5, nextMatch: { attack: 1.03 }, teamFitness: -2 } },
      { fx: { teamFitness: 5, nextMatch: { control: 1.02 } } },
    ],
    it: ['La volata per il titolo', 'Siete in corsa per il titolo. Ogni giornata è una finale.',
      ['Carico emotivo: “la storia è qui”', 'Squadra a mille, qualche energia in meno.'],
      ['Gestione delle forze: turnover mirato', 'Gambe fresche per il finale.']],
    en: ['The title race', 'You’re in the title race. Every matchday is a final.',
      ['Emotional charge: “history is here”', 'A fired-up team, a bit less energy.'],
      ['Manage energy: targeted rotation', 'Fresh legs for the finale.']],
  },
  {
    id: 'ss_promotion_push', cat: 'board', w: 6, repeat: 15,
    when: { mdMin: 20, level: 2, posMax: 6 },
    o: [
      { fx: { budgetPct: -0.2, signVeteran: { level: 2 } } },
      { fx: { trust: 3, teamMorale: 2 } },
    ],
    it: ['Il sogno della promozione', 'La promozione è a portata di mano. Il presidente è pronto a investire subito.',
      ['Un rinforzo di categoria superiore', 'Arriva un giocatore che fa la differenza in questa serie.'],
      ['Il gruppo che ci ha portato qui basta', 'Fiducia nel gruppo.']],
    en: ['The promotion dream', 'Promotion is within reach. The chairman is ready to invest right away.',
      ['A signing from a higher level', 'A player who makes the difference at this level arrives.'],
      ['The group that got us here is enough', 'Faith in the group.']],
  },
  {
    id: 'ss_season_opening', cat: 'board', w: 6, repeat: 45,
    when: { mdMax: 0 },
    o: [
      { fx: { trust: 3, teamMorale: -2 } },
      { fx: { teamMorale: 4, trust: -2 } },
      { fx: { fans: 5, trust: -1 } },
    ],
    it: ['Il primo discorso della stagione', 'Primo giorno di raduno: squadra, staff e dirigenza ti ascoltano.',
      ['Parlo di obiettivi e responsabilità', 'La società apprezza. I giocatori sentono subito la pressione.'],
      ['Parlo di gruppo e di divertimento', 'Il gruppo parte sereno. La società avrebbe voluto più ambizione.'],
      ['Parlo alla città: “Riempite lo stadio”', 'Entusiasmo in città.']],
    en: ['The first speech of the season', 'First day of pre-season: team, staff and board are listening.',
      ['Talk about goals and responsibility', 'The board likes it. The players feel the pressure straight away.'],
      ['Talk about the group and enjoyment', 'The group starts relaxed. The board wanted more ambition.'],
      ['Speak to the city: “Fill the stadium”', 'Enthusiasm in the city.']],
  },
  {
    id: 'ss_halfway_review', cat: 'board', w: 6, repeat: 45,
    when: { mdMin: 17, mdMax: 21 },
    o: [
      { fx: { trust: 2, familiarity: 2 } },
      { fx: { budgetPct: 0.1, trust: -2 } },
    ],
    it: ['Il bilancio di metà stagione', 'A metà campionato la società ti chiede un’analisi. Cosa chiedi per il girone di ritorno?',
      ['Nulla: continuità', 'La società apprezza la stabilità.'],
      ['Qualche soldo per migliorare la rosa', 'Budget leggermente aumentato, ma la società ora si aspetta di più.']],
    en: ['The mid-season review', 'Halfway through the season the board asks for an analysis. What do you ask for the second half?',
      ['Nothing: continuity', 'The board appreciates the stability.'],
      ['Some money to improve the squad', 'A slightly bigger budget, but the board now expects more.']],
  },
  {
    id: 'ss_final_day_rotation', cat: 'style', w: 4, repeat: 45,
    when: { mdFromEndMax: 2, gapMax: -3 },
    o: [
      { fx: { youngsters: { morale: 8, potential: 1 }, fans: 2, nextMatch: { control: 0.96 } } },
      { fx: { senior: { morale: 3 } } },
    ],
    it: ['Obiettivo già raggiunto', 'L’obiettivo è centrato con anticipo. Le ultime partite possono servire ad altro.',
      ['Spazio ai giovani', 'I ragazzi assaggiano la prima squadra.'],
      ['Gioca chi ha meritato tutto l’anno', 'Premiati i titolari.']],
    en: ['Target already met', 'The target has been met early. The last matches can serve another purpose.',
      ['Give the youngsters a chance', 'The kids get a taste of the first team.'],
      ['Those who earned it all year play', 'The regulars are rewarded.']],
  },
  {
    id: 'ss_losing_streak_retreat', cat: 'dressing', w: 5, repeat: 20,
    when: { streakL: 3 },
    o: [
      { fx: { teamMorale: 5, teamFitness: 3, budget: -0.2 } },
      { odds: { base: 0.5, good: { teamMorale: 6, familiarity: 4 }, bad: { teamMorale: -6 } } },
    ],
    it: ['Tre sconfitte di fila', 'La squadra ha perso le ultime tre. Serve una scossa.',
      ['Tre giorni di ritiro in un posto isolato', 'Aria nuova e testa sgombra.'],
      ['Cambio metà degli allenamenti e dei riferimenti', 'La scossa funziona.', 'Troppa confusione: la crisi si aggrava.']],
    en: ['Three defeats in a row', 'The team has lost the last three. A jolt is needed.',
      ['Three days of retreat somewhere remote', 'Fresh air and clear heads.'],
      ['Change half the training routines', 'The jolt works.', 'Too much confusion: the crisis deepens.']],
  },
  {
    id: 'ss_winning_streak_bonus', cat: 'finance', w: 4, repeat: 30,
    when: { streakW: 4 },
    o: [
      { fx: { teamMorale: 5, budget: -0.4 } },
      { fx: { trust: 3 } },
    ],
    it: ['La striscia vincente', 'Quattro vittorie di fila. I giocatori chiedono un premio straordinario.',
      ['Premio concesso', 'La squadra è ancora più motivata.'],
      ['Il premio vero è la classifica', 'La società risparmia.']],
    en: ['The winning streak', 'Four wins in a row. The players ask for a special bonus.',
      ['Bonus granted', 'The team is even more motivated.'],
      ['The real prize is the table', 'The club saves money.']],
  },
  {
    id: 'ss_second_division_pitch', cat: 'style', w: 4, repeat: 20,
    when: { level: 2, styles: ['tikitaka', 'totale', 'falsonove'] },
    o: [
      { fx: { familiarity: -4, nextMatch: { direct: 1.08 } } },
      { fx: { nextMatch: { control: 0.97 }, reputation: 1 } },
    ],
    it: ['I campi della serie cadetta', 'Campi piccoli, avversari fisici: il tuo calcio fatica in questa categoria.',
      ['Mi adatto alla categoria', 'Più pragmatismo, meno estetica.'],
      ['Imponiamo il nostro calcio ovunque', 'Coerenza, qualche difficoltà.']],
    en: ['Second-tier pitches', 'Small pitches, physical opponents: your football struggles at this level.',
      ['Adapt to the division', 'More pragmatism, less beauty.'],
      ['We impose our football everywhere', 'Consistency, some difficulties.']],
  },
  {
    id: 'ss_big_match_week', cat: 'style', w: 4, repeat: 12,
    when: { mdMin: 1, objective: ['title', 'ucl', 'europe'] },
    o: [
      { fx: { nextMatch: { control: 1.03 }, teamFitness: -3 } },
      { fx: { teamFitness: 4 } },
    ],
    it: ['La settimana del big match', 'Contro il {opponent} ci si gioca molto. Come imposti la settimana?',
      ['Settimana intensa di preparazione', 'Squadra pronta tatticamente.'],
      ['Settimana leggera: serve freschezza', 'Gambe al massimo.']],
    en: ['Big match week', 'A lot is at stake against {opponent}. How do you plan the week?',
      ['An intense week of preparation', 'A tactically ready team.'],
      ['A light week: freshness matters', 'Legs at their best.']],
  },
  {
    id: 'ss_season_end_trip', cat: 'dressing', w: 3, repeat: 45,
    when: { mdFromEndMax: 1 },
    o: [
      { fx: { teamMorale: 6, budget: -0.3 } },
      { fx: {} },
    ],
    it: ['La festa di fine stagione', 'Si avvicina la fine: i giocatori propongono un viaggio di squadra dopo l’ultima partita.',
      ['Il club lo organizza', 'Il gruppo chiude la stagione unito.'],
      ['Ognuno in vacanza per conto suo', 'Nessuna festa.']],
    en: ['The end-of-season party', 'The end approaches: the players propose a team trip after the last match.',
      ['The club organises it', 'The group ends the season united.'],
      ['Everyone takes their own holidays', 'No party.']],
  },
  {
    id: 'ss_ultimatum_board_visit', cat: 'board', w: 6, repeat: 10,
    when: { ultimatum: true },
    o: [
      { fx: { trust: 4, familiarity: -5 } },
      { fx: { teamMorale: 4, trust: -2 } },
    ],
    it: ['Il presidente al campo', 'Durante l’ultimatum il presidente si presenta all’allenamento e vuole parlare alla squadra.',
      ['Gli lascio la parola', 'Il presidente carica la squadra a modo suo; qualcuno è confuso.'],
      ['Gli chiedo di non farlo: parlo io', 'Il gruppo vede un allenatore che non si nasconde.']],
    en: ['The chairman at training', 'During the ultimatum the chairman turns up at training and wants to address the team.',
      ['Let him speak', 'The chairman fires up the team in his own way; some are confused.'],
      ['Ask him not to: I’ll speak', 'The group sees a manager who doesn’t hide.']],
  },
  {
    id: 'ss_home_form', cat: 'style', w: 3, repeat: 25,
    when: { mdMin: 8, winless: 2 },
    o: [
      { fx: { fans: 3, nextMatch: { attack: 1.04, block: 0.97 } } },
      { fx: { nextMatch: { defence: 1.03 } } },
    ],
    it: ['Il fattore campo', 'La squadra ha smesso di vincere. Il vice suggerisce di cambiare approccio nelle prossime partite.',
      ['Più aggressivi, soprattutto in casa', 'La squadra attacca di più, rischiando qualcosa.'],
      ['Prima la solidità', 'Squadra più ordinata.']],
    en: ['Home advantage', 'The team has stopped winning. Your assistant suggests a different approach for the next matches.',
      ['More aggressive, especially at home', 'The team attacks more, taking some risks.'],
      ['Solidity first', 'A tidier team.']],
  },
  {
    id: 'ss_captain_armband_crisis', cat: 'dressing', w: 3, repeat: 30,
    when: { streakL: 2, player: { captain: true } },
    o: [
      { fx: { morale: 4, bond: 5, teamMorale: 2 } },
      { odds: { base: 0.5, pers: { leader: 0.2 }, good: { teamMorale: 5 }, bad: { morale: -8 } } },
    ],
    it: ['Il capitano in difficoltà', 'Anche {player}, il capitano, sta giocando male. I tifosi chiedono di togliergli la fascia.',
      ['Lo confermo davanti a tutti', '{player} si sente protetto.'],
      ['Gli chiedo di dimostrare di meritarla', '{player} risponde da capitano.', '{player} vive la richiesta come un’accusa.']],
    en: ['The captain struggling', 'Even {player}, the captain, is playing badly. The fans want the armband taken from him.',
      ['Confirm him in front of everyone', '{player} feels protected.'],
      ['Ask him to prove he deserves it', '{player} responds like a captain.', '{player} takes it as an accusation.']],
  },
  {
    id: 'ss_derby_won_party', cat: 'fans', w: 4, repeat: 20,
    when: { last: 'W', mdMin: 1 },
    o: [
      { fx: { fans: 5, teamFitness: -3, teamMorale: 3 } },
      { fx: { teamFitness: 2 } },
    ],
    it: ['La festa per la vittoria', 'La città festeggia la vittoria. I tifosi invitano la squadra alla festa in piazza.',
      ['Tutti in piazza', 'Festa indimenticabile, gambe pesanti il giorno dopo.'],
      ['Solo un saluto: domani si lavora', 'Festa breve.']],
    en: ['The victory party', 'The city celebrates the win. The fans invite the team to the party in the square.',
      ['Everyone to the square', 'An unforgettable party, heavy legs the next day.'],
      ['Just a wave: work tomorrow', 'A short party.']],
  },
  {
    id: 'ss_january_squad_review', cat: 'market', w: 5, repeat: 45,
    when: { window: true, mdMin: 10 },
    o: [
      { fx: { trust: 2, budgetPct: 0.05 } },
      { fx: { youngsters: { morale: 4 } } },
    ],
    it: ['La rosa a gennaio', 'Il direttore sportivo ti chiede la lista dei giocatori da cedere e dei ruoli da rinforzare.',
      ['Lista dettagliata e ragionata', 'Il direttore è colpito: la società ti affida più margine.'],
      ['Nessun taglio: credo in questa rosa', 'I giocatori si sentono tutti importanti.']],
    en: ['The squad in January', 'The sporting director asks for a list of players to sell and positions to strengthen.',
      ['A detailed, reasoned list', 'The director is impressed: the club gives you more leeway.'],
      ['No cuts: I believe in this squad', 'The players all feel important.']],
  },
  {
    id: 'ss_media_pressure_title', cat: 'press', w: 4, repeat: 20,
    when: { mdMin: 25, posMax: 2 },
    o: [
      { fx: { teamMorale: -2, nextMatch: { control: 1.03 } } },
      { fx: { teamMorale: 4, reputation: 1 } },
    ],
    it: ['Tutti parlano di titolo', 'Ogni domanda in conferenza riguarda la possibilità di vincere il campionato.',
      ['“Non ne parliamo”', 'Squadra concentrata, un po’ tesa.'],
      ['“Sì, vogliamo vincere”', 'Il gruppo si sente legittimato a sognare.']],
    en: ['Everyone’s talking about the title', 'Every press conference question is about winning the league.',
      ['“We’re not talking about it”', 'A focused, slightly tense team.'],
      ['“Yes, we want to win”', 'The group feels allowed to dream.']],
  },
  {
    id: 'ss_injury_crisis_youth', cat: 'youth', w: 5, repeat: 20,
    when: { injuredMin: 4 },
    o: [
      { fx: { youthPromote: 2 } },
      { fx: { signVeteran: { level: -1 }, budget: -0.3 } },
    ],
    it: ['Emergenza infortuni', 'Quattro infortunati: la rosa è cortissima.',
      ['Promuovo due ragazzi della Primavera', 'Due giovani salgono in prima squadra.'],
      ['Uno svincolato per l’emergenza', 'Arriva un giocatore esperto.']],
    en: ['Injury crisis', 'Four players injured: the squad is very thin.',
      ['Promote two youth players', 'Two youngsters join the first team.'],
      ['A free agent for the emergency', 'An experienced player arrives.']],
  },
  {
    id: 'ss_rival_sacked', cat: 'rival', w: 3, repeat: 30,
    when: { mdMin: 8 },
    o: [
      { fx: { reputation: 2 } },
      { fx: { reputation: -1, fans: 2 } },
    ],
    it: ['Il collega esonerato', 'Un allenatore rivale è stato esonerato. I giornalisti chiedono un tuo commento.',
      ['Parole di stima per il collega', 'Gesto apprezzato da tutto l’ambiente.'],
      ['“Il calcio è questo”', 'Risposta fredda, che piace ai tifosi più duri.']],
    en: ['A colleague sacked', 'A rival manager has been sacked. Journalists ask for your comment.',
      ['Words of esteem for the colleague', 'A gesture appreciated across the game.'],
      ['“That’s football”', 'A cold answer that pleases the harder fans.']],
  },
  {
    id: 'ss_coach_rest_decision', cat: 'staff', w: 3, repeat: 30,
    when: { mdMin: 10 },
    o: [
      { fx: { staff: 4, trust: -1 } },
      { fx: { trust: 1 } },
    ],
    it: ['Delegare', 'Lo staff ti suggerisce di delegare di più: allenamenti del mattino al vice, tu solo sulla strategia.',
      ['Delego', 'Lo staff cresce in responsabilità.'],
      ['Voglio seguire tutto io', 'Controllo totale, più stanchezza.']],
    en: ['Delegating', 'The staff suggest you delegate more: morning sessions to your assistant, you on strategy only.',
      ['Delegate', 'The staff grow in responsibility.'],
      ['I want to oversee everything', 'Total control, more fatigue.']],
  },
  {
    id: 'ss_attendance_record', cat: 'fans', w: 3, repeat: 40,
    when: { fansMin: 70 },
    o: [
      { fx: { budget: 0.8, fans: 2 } },
      { fx: { fans: 4 } },
    ],
    it: ['Il record di spettatori', 'Lo stadio ha segnato il record stagionale di spettatori. La società vuole alzare i prezzi della prossima partita.',
      ['Alziamo i prezzi', 'Incasso record.'],
      ['Prezzi invariati: è il nostro pubblico', 'I tifosi apprezzano.']],
    en: ['Attendance record', 'The stadium set the season’s attendance record. The club wants to raise prices for the next match.',
      ['Raise the prices', 'Record takings.'],
      ['Prices unchanged: it’s our crowd', 'The fans appreciate it.']],
  },
  {
    id: 'ss_title_celebration_early', cat: 'dressing', w: 3, repeat: 45,
    when: { mdFromEndMax: 4, posMax: 1, gapMax: -1 },
    o: [
      { fx: { teamMorale: 6, nextMatch: { control: 0.96 } } },
      { fx: { nextMatch: { control: 1.03 } } },
    ],
    it: ['Festeggiare in anticipo?', 'Il traguardo è vicinissimo. In città già si preparano le bandiere e i giocatori sono distratti.',
      ['Lasciamoli godere', 'Entusiasmo incontenibile, concentrazione in calo.'],
      ['Nessuno festeggia prima del tempo', 'Squadra concentrata fino all’ultimo.']],
    en: ['Celebrate early?', 'The finish line is very close. The city is already preparing flags and the players are distracted.',
      ['Let them enjoy it', 'Uncontainable joy, dropping concentration.'],
      ['Nobody celebrates early', 'A team focused to the end.']],
  },
  {
    id: 'ss_wage_cap_request', cat: 'finance', w: 3, repeat: 45,
    when: { mdMin: 12 },
    o: [
      { fx: { trust: 4, senior: { morale: -5 } } },
      { fx: { trust: -3, senior: { morale: 3 } } },
    ],
    it: ['Il tetto agli ingaggi', 'La società vuole introdurre un tetto agli stipendi per i rinnovi futuri.',
      ['Sono d’accordo', 'La società ringrazia. I senatori in scadenza sono preoccupati.'],
      ['Così perdiamo i migliori', 'I senatori apprezzano la difesa.']],
    en: ['The wage cap', 'The club wants to introduce a salary cap for future renewals.',
      ['I agree', 'The club thanks you. Senior players nearing expiry are worried.'],
      ['That way we’ll lose our best', 'The senior players appreciate your stand.']],
  },
  {
    id: 'ss_rain_postponement', cat: 'staff', w: 2, repeat: 60,
    when: { mdMin: 8, mdMax: 28 },
    o: [
      { fx: { teamFitness: 5, familiarity: 1 } },
      { fx: { teamFitness: -2 } },
    ],
    it: ['Il campo allagato', 'Una bomba d’acqua ha allagato il centro sportivo: tre giorni senza campi.',
      ['Palestra, video e recupero', 'Tre giorni che ricaricano le energie.'],
      ['Ci alleniamo sul sintetico di un club amatoriale', 'Allenamenti su un campo duro.']],
    en: ['The flooded pitch', 'A cloudburst has flooded the training ground: three days without pitches.',
      ['Gym, video and recovery', 'Three days that recharge the batteries.'],
      ['Train on an amateur club’s artificial pitch', 'Sessions on a hard surface.']],
  },
  {
    id: 'ss_new_coach_rumour', cat: 'board', w: 4, repeat: 30,
    when: { trustMax: 40, mdMin: 8 },
    o: [
      { fx: { teamMorale: 3, trust: -2 } },
      { odds: { base: 0.5, rep: 0.006, good: { trust: 8 }, bad: { trust: -6 } } },
    ],
    it: ['Il sostituto già scelto?', 'I giornali scrivono che la società ha già contattato il tuo sostituto.',
      ['Lo dico alla squadra e ci compattiamo', 'Il gruppo si stringe intorno a te.'],
      ['Chiedo alla società di smentire', 'La società smentisce pubblicamente.', 'La società non smentisce: il segnale è chiaro.']],
    en: ['The replacement already chosen?', 'The papers say the board has already contacted your replacement.',
      ['Tell the team and pull together', 'The group rallies around you.'],
      ['Ask the board to deny it', 'The board publicly denies it.', 'The board doesn’t deny it: the signal is clear.']],
  },
  {
    id: 'ss_cup_rotation', cat: 'style', w: 3, repeat: 20,
    when: { mdMin: 3 },
    o: [
      { fx: { teamFitness: 5, youngsters: { morale: 3 } } },
      { fx: { teamFitness: -3, fans: 2 } },
    ],
    it: ['Coppa o campionato?', 'Il calendario è fitto tra campionato e coppe. Su cosa punti?',
      ['Priorità al campionato: turnover in coppa', 'Titolari freschi per la domenica.'],
      ['Si gioca sempre per vincere', 'I tifosi apprezzano, le gambe meno.']],
    en: ['Cup or league?', 'The schedule is packed with league and cup games. What’s the priority?',
      ['League first: rotate in the cup', 'Fresh starters for the weekend.'],
      ['We always play to win', 'The fans like it, the legs less so.']],
  },
  {
    id: 'ss_ball_boy_trick', cat: 'rival', w: 2, repeat: 60,
    when: { mdMin: 3 },
    o: [
      { fx: { nextMatch: { tempo: 0.95 }, reputation: -2 } },
      { fx: { reputation: 1 } },
    ],
    it: ['I raccattapalle', 'Il magazziniere propone di istruire i raccattapalle a rallentare il gioco quando siete in vantaggio.',
      ['Facciamolo', 'Tempo guadagnato, polemiche sui giornali.'],
      ['Non è il nostro stile', 'Nessun trucco.']],
    en: ['The ball boys', 'The kit man suggests instructing the ball boys to slow the game when you’re ahead.',
      ['Do it', 'Time gained, controversy in the papers.'],
      ['It’s not our style', 'No tricks.']],
  },
  {
    id: 'ss_team_photo', cat: 'dressing', w: 2, repeat: 60,
    when: { mdMax: 2 },
    o: [
      { fx: { teamMorale: 3, fans: 2 } },
      { fx: {} },
    ],
    it: ['La foto ufficiale', 'Il club organizza la foto ufficiale in centro città con i tifosi.',
      ['Tutti in città', 'Una bella giornata con i tifosi.'],
      ['Foto al centro sportivo', 'Scatto veloce.']],
    en: ['The official photo', 'The club organises the official team photo in the city centre with the fans.',
      ['Everyone into town', 'A lovely day with the fans.'],
      ['Photo at the training ground', 'A quick shot.']],
  },
  {
    id: 'ss_last_home_game', cat: 'fans', w: 4, repeat: 45,
    when: { mdFromEndMax: 2 },
    o: [
      { fx: { fans: 6, teamMorale: 3 } },
      { fx: { fans: 2 } },
    ],
    it: ['L’ultima in casa', 'Ultima partita in casa della stagione: il club vuole un giro di campo con le famiglie dei giocatori.',
      ['Giro di campo con tutti', 'Uno stadio in festa.'],
      ['Solo un saluto dal centrocampo', 'Saluto sobrio.']],
    en: ['The last home game', 'The season’s last home match: the club wants a lap of honour with the players’ families.',
      ['A lap of honour with everyone', 'A stadium in celebration.'],
      ['Just a wave from the centre circle', 'A modest farewell.']],
  },
  {
    id: 'ss_scouting_opponent_leak', cat: 'rival', w: 2, repeat: 60,
    when: { mdMin: 3 },
    o: [
      { fx: { nextMatch: { control: 1.04 }, reputation: -2 } },
      { fx: { reputation: 3 } },
    ],
    it: ['Il dossier dell’avversario', 'Un ex collaboratore del {opponent} ti offre il loro dossier tattico completo.',
      ['Lo prendo', 'Conosci ogni mossa, ma se si viene a sapere…'],
      ['Lo rifiuto e avviso il collega', 'Gesto di lealtà che fa il giro dell’ambiente.']],
    en: ['The opponent’s dossier', 'A former {opponent} staff member offers you their complete tactical dossier.',
      ['Take it', 'You know every move, but if it gets out…'],
      ['Refuse and warn my colleague', 'A gesture of loyalty that goes around the game.']],
  },
  {
    id: 'ss_sponsor_bonus_goals', cat: 'finance', w: 2, repeat: 60,
    when: {},
    o: [
      { fx: { budget: 0.5, nextMatch: { attack: 1.03, block: 0.97 } } },
      { fx: {} },
    ],
    it: ['Il bonus dello sponsor', 'Lo sponsor offre un premio per ogni gol segnato nelle prossime partite.',
      ['Accettiamo: più attacco', 'La squadra spinge di più, rischiando dietro.'],
      ['Non cambiamo il nostro gioco per uno sponsor', 'Nessun premio.']],
    en: ['The sponsor’s bonus', 'The sponsor offers a bonus for every goal scored in the next matches.',
      ['Accept: more attack', 'The team pushes more, taking risks at the back.'],
      ['We don’t change our game for a sponsor', 'No bonus.']],
  },
];
