/* Il vivaio e i ragazzi: talenti, famiglie, procuratori, esordi. */

export default [
  {
    id: 'yt_prodigy_report', cat: 'youth', w: 4, repeat: 30,
    when: {},
    o: [
      { fx: { youthPromote: 1, youthQuality: 8, trust: 2 } },
      { fx: { youngsters: { morale: 2 } } },
    ],
    it: ['Il gioiello della Primavera', 'L’allenatore della Primavera ti segnala un sedicenne “come non se ne vedono da anni”.',
      ['Lo aggrego subito alla prima squadra', 'Il ragazzo si allena con i grandi e brucia le tappe.'],
      ['Resta con i suoi coetanei', 'Crescerà senza fretta.']],
    en: ['The academy gem', 'The youth team coach tells you about a sixteen-year-old “like we haven’t seen in years”.',
      ['Bring him straight into the first team', 'The kid trains with the seniors and progresses fast.'],
      ['He stays with his age group', 'He’ll develop without hurry.']],
  },
  {
    id: 'yt_parent_pressure', cat: 'youth', w: 4, repeat: 30,
    when: { player: { ageMax: 20 } },
    o: [
      { fx: { morale: -6, bond: 6, trust: 1 } },
      { fx: { morale: 5, promiseStarts: { need: 1, within: 4 }, teamMorale: -2 } },
    ],
    it: ['Il padre di {player}', 'Il padre di {player} ti aspetta fuori dal centro sportivo: pretende che suo figlio giochi titolare.',
      ['Gli spiego che decido io, con rispetto', 'Il ragazzo apprezza che tu lo protegga dalle pressioni.'],
      ['Gli prometto spazio per il figlio', 'Il padre se ne va soddisfatto. Ora la promessa pesa.']],
    en: ['{player}’s father', '{player}’s father is waiting for you outside the training ground: he demands his son starts.',
      ['Explain respectfully that I decide', 'The kid appreciates you shielding him from the pressure.'],
      ['Promise him playing time for his son', 'The father leaves satisfied. Now the promise weighs.']],
  },
  {
    id: 'yt_vulture_agent', cat: 'youth', w: 4, repeat: 30,
    when: { player: { ageMax: 20, potentialGap: 6 } },
    o: [
      { fx: { renew: 4, raise: 0.6, morale: 6 } },
      { odds: { base: 0.45, bond: 0.006, good: { bond: 10, morale: 4 }, bad: { morale: -10, sell: 1.1 } } },
    ],
    it: ['Il procuratore avvoltoio', 'Un procuratore famoso sta convincendo {player} a lasciare il club per un contratto all’estero.',
      ['Rinnovo di cinque anni con aumento', '{player} firma: il club protegge il suo talento.'],
      ['Ci parlo io: qui crescerà di più', '{player} sceglie di restare.', '{player} si lascia convincere e parte per una cifra.']],
    en: ['The vulture agent', 'A famous agent is persuading {player} to leave the club for a contract abroad.',
      ['A five-year deal with a raise', '{player} signs: the club protects its talent.'],
      ['I’ll talk to him: he’ll grow more here', '{player} chooses to stay.', '{player} is persuaded and leaves for a fee.']],
  },
  {
    id: 'yt_school_exams', cat: 'youth', w: 3, repeat: 60,
    when: { player: { ageMin: 18, ageMax: 19 } },
    o: [
      { fx: { fitness: -6, morale: 6, bond: 6 } },
      { fx: { fitness: 3, morale: -4 } },
    ],
    it: ['La maturità di {player}', '{player} deve sostenere gli esami di maturità e chiede qualche giorno per studiare.',
      ['Vai: la scuola è importante', '{player} supera gli esami e ti ringrazia.'],
      ['Studia la sera, di giorno ci si allena', '{player} si allena, ma è stanco e nervoso.']],
    en: ['{player}’s final exams', '{player} has to sit his school-leaving exams and asks for a few days to study.',
      ['Go: school matters', '{player} passes and thanks you.'],
      ['Study at night, train by day', '{player} trains, but he’s tired and stressed.']],
  },
  {
    id: 'yt_youth_tournament', cat: 'youth', w: 3, repeat: 60,
    when: { mdMin: 10, mdMax: 30 },
    o: [
      { fx: { youngsters: { potential: 1, morale: 4, fitness: -5 } } },
      { fx: { youngsters: { morale: -3 } } },
    ],
    it: ['Il torneo giovanile', 'La Primavera è invitata a un torneo internazionale prestigioso. Vorrebbe portare anche i ragazzi aggregati alla prima squadra.',
      ['Mandiamoli', 'I ragazzi fanno esperienza internazionale e tornano più sicuri.'],
      ['Restano con me', 'I ragazzi restano delusi.']],
    en: ['The youth tournament', 'The youth team is invited to a prestigious international tournament. They’d like to take the kids training with the first team.',
      ['Send them', 'The kids gain international experience and return more confident.'],
      ['They stay with me', 'The kids are disappointed.']],
  },
  {
    id: 'yt_youth_coach_offer', cat: 'youth', w: 3, repeat: 80,
    when: {},
    o: [
      { fx: { budget: -0.4, academyInvest: true } },
      { fx: {} },
    ],
    it: ['Un allenatore per i giovani', 'Un tecnico famoso per aver lanciato decine di talenti è disponibile per il settore giovanile.',
      ['Lo prendiamo', 'I prossimi ragazzi del vivaio saranno migliori.'],
      ['Troppo caro', 'Il vivaio resta com’è.']],
    en: ['A coach for the kids', 'A coach famous for launching dozens of talents is available for the academy.',
      ['Hire him', 'The next academy graduates will be better.'],
      ['Too expensive', 'The academy stays as it is.']],
  },
  {
    id: 'yt_homegrown_captain', cat: 'youth', w: 3, repeat: 60,
    when: { player: { academy: true, ageMax: 22 } },
    o: [
      { fx: { captain: true, morale: 12, fans: 5, senior: { morale: -4 } } },
      { fx: { morale: -2 } },
    ],
    it: ['Un capitano del vivaio', 'I tifosi sognano {player}, cresciuto nel vivaio, con la fascia al braccio.',
      ['Gli do la fascia', 'Scelta romantica: tifosi in delirio, senatori perplessi.'],
      ['È ancora presto', 'Il sogno può aspettare.']],
    en: ['A homegrown captain', 'The fans dream of {player}, an academy product, wearing the armband.',
      ['Give him the armband', 'A romantic choice: fans in raptures, seniors puzzled.'],
      ['It’s too early', 'The dream can wait.']],
  },
  {
    id: 'yt_talent_offer_scouts', cat: 'youth', w: 3, repeat: 40,
    when: { window: true, player: { ageMax: 19, appsMax: 2 } },
    o: [
      { fx: { sell: 1.2 } },
      { fx: { morale: 6, potential: 1 } },
    ],
    it: ['Gli osservatori per {player}', 'Un grande club straniero vuole comprare {player}, che non ha ancora esordito.',
      ['Vendiamo', 'Soldi subito per un ragazzo che non ha ancora giocato.'],
      ['Crederemo noi in lui', '{player} resta e si sente valorizzato.']],
    en: ['Scouts for {player}', 'A big foreign club wants to buy {player}, who hasn’t made his debut yet.',
      ['Sell', 'Money now for a kid who hasn’t played yet.'],
      ['We’ll believe in him', '{player} stays and feels valued.']],
  },
  {
    id: 'yt_youth_indiscipline', cat: 'youth', w: 3, repeat: 40,
    when: { player: { ageMax: 21, personality: ['ribelle', 'pigro'] } },
    o: [
      { odds: { base: 0.5, good: { consistency: 10, attrs: { role: 1 } }, bad: { morale: -10, potential: -2 } }, fx: { suspended: 1 } },
      { fx: { bond: 6, morale: 3 } },
    ],
    it: ['Il ragazzo va raddrizzato', '{player} ha talento ma pochissima disciplina: ritardi, allenamenti a metà, risposte sgarbate.',
      ['Punizione esemplare', 'Il ragazzo capisce e cambia atteggiamento.', 'Il ragazzo si offende e smette di crescere.'],
      ['Un percorso con il mental coach', '{player} si apre e il rapporto migliora.']],
    en: ['The kid needs straightening out', '{player} has talent but very little discipline: lateness, half-hearted sessions, rude replies.',
      ['An exemplary punishment', 'The kid understands and changes his attitude.', 'The kid takes offence and stops developing.'],
      ['A programme with the mental coach', '{player} opens up and your relationship improves.']],
  },
  {
    id: 'yt_youth_league_final', cat: 'youth', w: 3, repeat: 50,
    when: { mdMin: 28 },
    o: [
      { fx: { youngsters: { morale: 8, potential: 1 }, fans: 3, teamFitness: -1 } },
      { fx: {} },
    ],
    it: ['La finale della Primavera', 'La Primavera gioca la finale del campionato giovanile. I ragazzi ti chiedono di esserci.',
      ['Vado in tribuna con tutta la prima squadra', 'I ragazzi giocano con il cuore: una serata speciale.'],
      ['Non posso, c’è da preparare la partita', 'I ragazzi capiscono, ma speravano.']],
    en: ['The youth final', 'The youth team plays the final of the youth league. The kids ask you to be there.',
      ['Go to the stands with the whole first team', 'The kids play with heart: a special night.'],
      ['I can’t, there’s a match to prepare', 'The kids understand, but they hoped.']],
  },
  {
    id: 'yt_position_experiment', cat: 'youth', w: 3, repeat: 40,
    when: { player: { ageMax: 20, roles: ['CC', 'TRQ', 'PUN'] } },
    o: [
      { odds: { base: 0.55, good: { newRole: 'ALA', attrs: { pace: 3, dribbling: 3 }, potential: 2 }, bad: { newRole: 'ALA', potential: -1 } } },
      { fx: {} },
    ],
    it: ['{player} esterno?', 'Nella Primavera {player} ha giocato largo con ottimi risultati. Lo staff propone di cambiargli ruolo.',
      ['Proviamo da ala', 'Nuovo ruolo, nuovo potenziale.', 'Esperimento non riuscito.'],
      ['Resta nel suo ruolo', 'Nessun cambiamento.']],
    en: ['{player} out wide?', 'In the youth team {player} played wide with excellent results. The staff propose a position change.',
      ['Try him as a winger', 'A new role, new potential.', 'The experiment fails.'],
      ['He stays in his position', 'No change.']],
  },
  {
    id: 'yt_scholarship', cat: 'youth', w: 2, repeat: 100,
    when: {},
    o: [
      { fx: { budget: -0.2, youthPromote: 1, fans: 2 } },
      { fx: {} },
    ],
    it: ['Il ragazzo del quartiere', 'Un ragazzo del quartiere intorno allo stadio si allena da solo contro il muro ogni sera. Gli osservatori dicono che ha qualcosa.',
      ['Gli diamo una possibilità', 'Il ragazzo entra nella rosa: la città adora questa storia.'],
      ['Non abbiamo posto', 'Il ragazzo continua contro il muro.']],
    en: ['The kid from the neighbourhood', 'A kid from the area around the stadium practises alone against a wall every evening. The scouts say he has something.',
      ['Give him a chance', 'The kid joins the squad: the city loves the story.'],
      ['We have no room', 'The kid keeps kicking against the wall.']],
  },
  {
    id: 'yt_injury_young_star', cat: 'youth', w: 3, repeat: 40,
    when: { player: { ageMax: 20, injured: true } },
    o: [
      { fx: { morale: 8, bond: 8, budget: -0.1 } },
      { fx: { morale: -4 } },
    ],
    it: ['Il primo infortunio di {player}', 'È il primo infortunio serio di {player}. Il ragazzo è spaventato.',
      ['Lo seguo personalmente nel recupero', '{player} si sente protetto: il legame si rafforza.'],
      ['Se ne occupa lo staff medico', '{player} affronta il recupero da solo.']],
    en: ['{player}’s first injury', 'It’s {player}’s first serious injury. The kid is scared.',
      ['Follow his recovery personally', '{player} feels protected: your bond grows.'],
      ['The medical staff handle it', '{player} faces the recovery alone.']],
  },
  {
    id: 'yt_social_youth', cat: 'youth', w: 3, repeat: 40,
    when: { player: { ageMax: 21 } },
    o: [
      { fx: { morale: -5, consistency: 5 } },
      { fx: { morale: 3, fans: 2 } },
    ],
    it: ['{player} influencer', '{player} ha centinaia di migliaia di follower e passa ore a girare video.',
      ['Regole sui social in orario di lavoro', '{player} è meno distratto.'],
      ['È la sua generazione', '{player} continua, i tifosi lo seguono.']],
    en: ['{player} the influencer', '{player} has hundreds of thousands of followers and spends hours making videos.',
      ['Social media rules during work hours', '{player} is less distracted.'],
      ['It’s his generation', '{player} carries on, the fans follow him.']],
  },
  {
    id: 'yt_youth_selection', cat: 'youth', w: 3, repeat: 40,
    when: { player: { ageMax: 20 } },
    o: [
      { fx: { fitness: -8, morale: 8, potential: 1 } },
      { fx: { morale: -6 } },
    ],
    it: ['La nazionale giovanile', '{player} è convocato con la nazionale giovanile per un torneo di dieci giorni.',
      ['Vai', '{player} torna con esperienza internazionale.'],
      ['Chiedo di lasciarlo al club', '{player} è deluso.']],
    en: ['The youth national team', '{player} is called up by the youth national team for a ten-day tournament.',
      ['Go', '{player} returns with international experience.'],
      ['Ask for him to stay with the club', '{player} is disappointed.']],
  },
  {
    id: 'yt_b_team', cat: 'youth', w: 2, repeat: 120,
    when: { budgetMin: 5 },
    o: [
      { fx: { budgetPct: -0.25, academyInvest: true, youngsters: { potential: 2 } } },
      { fx: {} },
    ],
    it: ['La seconda squadra', 'La società valuta di iscrivere una seconda squadra in una serie minore per far giocare i giovani.',
      ['Sì, creiamola', 'I giovani giocheranno partite vere: crescita più rapida.'],
      ['Troppo impegnativo', 'Nessuna seconda squadra.']],
    en: ['The B team', 'The club is considering entering a second team in a lower league to give youngsters games.',
      ['Yes, let’s create it', 'The youngsters will play real matches: faster development.'],
      ['Too demanding', 'No B team.']],
  },
  {
    id: 'yt_player_trial', cat: 'youth', w: 3, repeat: 40,
    when: {},
    o: [
      { odds: { base: 0.4, good: { youthPromote: 1, youthQuality: 10 }, bad: { budget: -0.1 } } },
      { fx: {} },
    ],
    it: ['Il provino', 'Un procuratore propone un provino per un diciassettenne africano sconosciuto.',
      ['Facciamolo provare', 'Il ragazzo impressiona tutti: firma.', 'Il ragazzo non è all’altezza.'],
      ['Non facciamo provini', 'Nessun provino.']],
    en: ['The trial', 'An agent proposes a trial for an unknown seventeen-year-old from Africa.',
      ['Let’s try him', 'The kid impresses everyone: he signs.', 'The kid isn’t good enough.'],
      ['We don’t do trials', 'No trial.']],
  },
  {
    id: 'yt_academy_poached', cat: 'youth', w: 3, repeat: 60,
    when: {},
    o: [
      { fx: { budget: -0.5, youngsters: { morale: 4 } } },
      { fx: { youngsters: { potential: -1 } } },
    ],
    it: ['I ragazzi rubati', 'Un club rivale sta offrendo soldi alle famiglie dei migliori quindicenni del vivaio.',
      ['Offriamo contratti e borse di studio', 'I ragazzi restano.'],
      ['Non entriamo in queste aste', 'Due talenti se ne vanno.']],
    en: ['Poached kids', 'A rival club is offering money to the families of the academy’s best fifteen-year-olds.',
      ['Offer contracts and scholarships', 'The kids stay.'],
      ['We don’t enter these auctions', 'Two talents leave.']],
  },
  {
    id: 'yt_debut_nerves', cat: 'youth', w: 3, repeat: 30,
    when: { player: { ageMax: 20, appsMax: 1, starter: true } },
    o: [
      { fx: { morale: 6, form: 2 } },
      { fx: { morale: -3, form: -1 } },
    ],
    it: ['La vigilia dell’esordio', '{player} farà il suo esordio da titolare. La notte prima non riesce a dormire.',
      ['Gli scrivo un messaggio personale', '{player} entra in campo tranquillo.'],
      ['Deve imparare a gestire la tensione', '{player} entra in campo teso.']],
    en: ['The night before the debut', '{player} will make his first start. The night before he can’t sleep.',
      ['Send him a personal message', '{player} takes the field calmly.'],
      ['He has to learn to handle nerves', '{player} takes the field tense.']],
  },
  {
    id: 'yt_old_coach_advice', cat: 'youth', w: 2, repeat: 80,
    when: { player: { ageMax: 21, potentialGap: 5 } },
    o: [
      { fx: { potential: 2, fitness: -4 } },
      { fx: {} },
    ],
    it: ['Lezioni private', 'Un vecchio campione del ruolo si offre di dare lezioni private a {player}.',
      ['Accettiamo', '{player} impara segreti che nessun allenamento insegna.'],
      ['Non serve', 'Nessuna lezione.']],
    en: ['Private lessons', 'An old star of the same position offers to give {player} private lessons.',
      ['Accept', '{player} learns secrets no training session teaches.'],
      ['Not needed', 'No lessons.']],
  },
  {
    id: 'yt_scout_south_america', cat: 'youth', w: 2, repeat: 100,
    when: { budgetMin: 2 },
    o: [
      { odds: { base: 0.5, good: { youthPromote: 1, youthQuality: 14, budget: -1 }, bad: { budget: -1 } } },
      { fx: {} },
    ],
    it: ['Il talento sudamericano', 'Gli osservatori hanno trovato un diciassettenne in Sudamerica: servono un milione e un po’ di fortuna.',
      ['Proviamo', 'Arriva un talento vero.', 'Soldi spesi per un ragazzo che non si adatta.'],
      ['Troppo rischioso', 'Nessun acquisto.']],
    en: ['The South American talent', 'The scouts found a seventeen-year-old in South America: it takes a million and some luck.',
      ['Go for it', 'A real talent arrives.', 'Money spent on a kid who can’t adapt.'],
      ['Too risky', 'No signing.']],
  },
  {
    id: 'yt_youth_bench', cat: 'youth', w: 3, repeat: 20,
    when: { mdMin: 5 },
    o: [
      { fx: { youngsters: { morale: 5 }, nextMatch: { control: 0.99 } } },
      { fx: { senior: { morale: 2 } } },
    ],
    it: ['I ragazzi in panchina', 'Il responsabile del vivaio chiede di portare in panchina due ragazzi della Primavera.',
      ['Li porto', 'I ragazzi respirano l’aria della prima squadra.'],
      ['Panchina ai più esperti', 'Nessuna novità.']],
    en: ['Kids on the bench', 'The academy director asks you to put two youth players on the bench.',
      ['Take them', 'The kids get a taste of the first team.'],
      ['The bench goes to experienced players', 'Nothing new.']],
  },
  {
    id: 'yt_growth_spurt_potential', cat: 'youth', w: 3, repeat: 40,
    when: { player: { ageMax: 21, avgMin: 6.7, appsMin: 3 } },
    o: [
      { fx: { potential: 3, morale: 6 } },
      { fx: { potential: 1 } },
    ],
    it: ['{player} sorprende tutti', 'Lo staff è impressionato dalla crescita di {player}: vorrebbe dargli più responsabilità.',
      ['Più minuti e compiti importanti', '{player} risponde: il suo tetto sale.'],
      ['Con calma', 'Crescita graduale.']],
    en: ['{player} surprises everyone', 'The staff are impressed by {player}’s progress and want to give him more responsibility.',
      ['More minutes and key tasks', '{player} responds: his ceiling rises.'],
      ['Take it slowly', 'Gradual growth.']],
  },
  {
    id: 'yt_loan_return_star', cat: 'youth', w: 3, repeat: 40,
    when: { mdMin: 17, mdMax: 22, player: { ageMax: 22, starter: false } },
    o: [
      { fx: { loanOut: true, potential: 3 } },
      { fx: { morale: -4, potential: 1 } },
    ],
    it: ['Prestito a gennaio', 'A gennaio una squadra di metà classifica chiede {player} in prestito per sei mesi da titolare.',
      ['Mandiamolo', '{player} gioca con continuità e tornerà cresciuto.'],
      ['Resta qui', '{player} resta, ma giocherà poco.']],
    en: ['A January loan', 'In January a mid-table side asks for {player} on loan for six months as a starter.',
      ['Send him', '{player} plays regularly and will come back improved.'],
      ['He stays', '{player} stays, but will play little.']],
  },
  {
    id: 'yt_youth_captain_speech', cat: 'youth', w: 2, repeat: 80,
    when: {},
    o: [
      { fx: { youngsters: { morale: 6 }, teamMorale: 2 } },
      { fx: {} },
    ],
    it: ['La lezione ai ragazzi', 'Il responsabile del vivaio ti chiede di parlare a tutti i ragazzi delle giovanili.',
      ['Ci vado volentieri', 'I ragazzi pendono dalle tue labbra: messaggio arrivato.'],
      ['Manderò il mio vice', 'Incontro più tiepido.']],
    en: ['A talk to the kids', 'The academy director asks you to speak to all the youth players.',
      ['Gladly', 'The kids hang on your every word: message received.'],
      ['I’ll send my assistant', 'A lukewarm meeting.']],
  },
];
